export const SENTENCES = {
  Haus: {
    n: "Das Haus ist groß.",
    a: "Wir kaufen das Haus.",
    d: "Er wohnt in dem Haus.",
    g: "Die Tür des Hauses ist rot.",
  },
  Sonne: {
    n: "Die Sonne scheint hell.",
    a: "Ich genieße die Sonne.",
    d: "Er liegt in der Sonne.",
    g: "Die Wärme der Sonne ist angenehm.",
  },
  Katze: {
    n: "Die Katze schläft viel.",
    a: "Ich füttere die Katze.",
    d: "Er spielt mit der Katze.",
    g: "Das Fell der Katze ist weich.",
  },
  Vogel: {
    n: "Der Vogel singt schön.",
    a: "Ich beobachte den Vogel.",
    d: "Er füttert den Vogel.",
    g: "Das Gefieder des Vogels ist bunt.",
  },
  Auto: {
    n: "Das Auto fährt schnell.",
    a: "Ich wasche das Auto.",
    d: "Er fährt mit dem Auto.",
    g: "Die Farbe des Autos ist blau.",
  },
  Tisch: {
    n: "Der Tisch ist aus Holz.",
    a: "Ich kaufe den Tisch.",
    d: "Wir essen an dem Tisch.",
    g: "Die Beine des Tisches sind stabil.",
  },
  Apfel: {
    n: "Der Apfel ist rot und süß.",
    a: "Ich esse den Apfel.",
    d: "Er macht Saft aus dem Apfel.",
    g: "Die Schale des Apfels ist dünn.",
  },
  Buch: {
    n: "Das Buch ist spannend.",
    a: "Ich lese das Buch.",
    d: "Sie lernt aus dem Buch.",
    g: "Der Autor des Buches ist bekannt.",
  },
  Computer: {
    n: "Der Computer ist schnell.",
    a: "Ich kaufe den Computer.",
    d: "Er arbeitet an dem Computer.",
    g: "Die Tastatur des Computers ist neu.",
  },
  Stadt: {
    n: "Die Stadt ist lebendig.",
    a: "Ich besuche die Stadt.",
    d: "Er wohnt in der Stadt.",
    g: "Die Geschichte der Stadt ist lang.",
  },
  Hund: {
    n: "Der Hund bellt laut.",
    a: "Ich streichle den Hund.",
    d: "Ich spiele mit dem Hund.",
    g: "Das Halsband des Hundes ist neu.",
  },
  Blume: {
    n: "Die Blume ist wunderschön.",
    a: "Ich kaufe die Blume.",
    d: "Er gießt die Blume mit Wasser.",
    g: "Der Duft der Blume ist toll.",
  },
  Telefon: {
    n: "Das Telefon klingelt laut.",
    a: "Er nimmt das Telefon.",
    d: "Wir reden über das Telefon.",
    g: "Das Modell des Telefons ist neu.",
  },
  Wasser: {
    n: "Das Wasser ist kalt.",
    a: "Ich trinke das Wasser.",
    d: "Er kocht mit dem Wasser.",
    g: "Die Qualität des Wassers ist gut.",
  },
  Kaffee: {
    n: "Der Kaffee duftet köstlich.",
    a: "Ich trinke den Kaffee morgens.",
    d: "Er wacht mit dem Kaffee auf.",
    g: "Der Geschmack des Kaffees ist stark.",
  },
  Fenster: {
    n: "Das Fenster ist sauber.",
    a: "Ich öffne das Fenster.",
    d: "Er schaut durch das Fenster.",
    g: "Das Glas des Fensters ist klar.",
  },
  Schule: {
    n: "Die Schule ist groß.",
    a: "Er mag die Schule.",
    d: "Sie geht in die Schule.",
    g: "Die Lehrer der Schule sind nett.",
  },
  Lampe: {
    n: "Die Lampe leuchtet hell.",
    a: "Kannst du die Lampe bringen?",
    d: "Er sitzt unter der Lampe.",
    g: "Das Design der Lampe gefällt mir.",
  },
  Brot: {
    n: "Das Brot ist frisch.",
    a: "Ich esse das Brot.",
    d: "Er isst Käse mit dem Brot.",
    g: "Die Kruste des Brotes ist knusprig.",
  },
  Garten: {
    n: "Der Garten ist sehr gepflegt.",
    a: "Er pflegt den Garten.",
    d: "Wir sitzen in dem Garten.",
    g: "Die Pflanzen des Gartens wachsen.",
  },
  Wald: {
    n: "Der Wald ist sehr ruhig.",
    a: "Ich liebe den Wald.",
    d: "Er spaziert in dem Wald.",
    g: "Die Bäume des Waldes sind hoch.",
  },
  Himmel: {
    n: "Der Himmel ist strahlend blau.",
    a: "Ich betrachte den Himmel.",
    d: "Er fliegt am Himmel.",
    g: "Die Farbe des Himmels ist schön.",
  },
  Maus: {
    n: "Die Maus ist sehr klein.",
    a: "Die Katze fängt die Maus.",
    d: "Sie spielt mit der Maus.",
    g: "Der Käse der Maus ist weg.",
  },
  Gesicht: {
    n: "Das Gesicht ist freundlich.",
    a: "Ich wasche das Gesicht.",
    d: "Mit dem Gesicht stimmt etwas nicht.",
    g: "Der Ausdruck des Gesichts ist ernst.",
  },
  Brücke: {
    n: "Die Brücke führt über den Fluss.",
    a: "Wir überqueren die Brücke.",
    d: "Er steht auf der Brücke.",
    g: "Die Länge der Brücke ist beachtlich.",
  },
  Geld: {
    n: "Das Geld liegt im Portemonnaie.",
    a: "Er spart sein Geld.",
    d: "Sie bezahlt mit dem Geld.",
    g: "Der Wert des Geldes sinkt.",
  },
  Auge: {
    n: "Das Auge ist blau.",
    a: "Der Arzt untersucht das Auge.",
    d: "Er hat etwas in dem Auge.",
    g: "Die Farbe des Auges ist hell.",
  },
  Hand: {
    n: "Die Hand ist verletzt.",
    a: "Er reicht mir die Hand.",
    d: "Sie schreibt mit der Hand.",
    g: "Die Finger der Hand sind lang.",
  },
  Stuhl: {
    n: "Der Stuhl ist bequem.",
    a: "Ich trage den Stuhl.",
    d: "Er sitzt auf dem Stuhl.",
    g: "Die Lehne des Stuhls ist weich.",
  },
  Kühlschrank: {
    n: "Der Kühlschrank ist voll.",
    a: "Ich öffne den Kühlschrank.",
    d: "Die Milch steht in dem Kühlschrank.",
    g: "Der Preis des Kühlschrankes war hoch.",
  },
  Uhr: {
    n: "Die Uhr geht genau.",
    a: "Ich brauche die Uhr heute.",
    d: "Er schaut auf die Uhr.",
    g: "Das Zifferblatt der Uhr ist weiß.",
  },
  Fisch: {
    n: "Der Fisch schwimmt im Wasser.",
    a: "Ich esse den Fisch.",
    d: "Er angelt nach dem Fisch.",
    g: "Die Schuppen des Fisches glänzen.",
  },
  Flugzeug: {
    n: "Das Flugzeug fliegt hoch.",
    a: "Ich sehe das Flugzeug am Himmel.",
    d: "Er reist mit dem Flugzeug.",
    g: "Die Geschwindigkeit des Flugzeugs ist hoch.",
  },
  Geschenk: {
    n: "Das Geschenk ist für dich.",
    a: "Er bringt das Geschenk mit.",
    d: "Wir freuen uns über das Geschenk.",
    g: "Die Verpackung des Geschenks ist bunt.",
  },
  Laptop: {
    n: "Der Laptop ist neu.",
    a: "Ich benutze den Laptop.",
    d: "Er arbeitet an dem Laptop.",
    g: "Der Akku des Laptops ist leer.",
  },
  Straße: {
    n: "Die Straße ist breit.",
    a: "Ich überquere die Straße.",
    d: "Er läuft auf der Straße.",
    g: "Das Ende der Straße ist nah.",
  },
  Zimmer: {
    n: "Das Zimmer ist hell.",
    a: "Ich reserviere das Zimmer.",
    d: "Sie schläft in dem Zimmer.",
    g: "Die Einrichtung des Zimmers ist modern.",
  },
  Kleid: {
    n: "Das Kleid ist elegant.",
    a: "Sie kauft das Kleid.",
    d: "Sie sieht toll aus in dem Kleid.",
    g: "Der Stoff des Kleids ist Seide.",
  },
  Hose: {
    n: "Die Hose passt gut.",
    a: "Ich wasche die Hose.",
    d: "Mit der Hose bin ich zufrieden.",
    g: "Die Farbe der Hose ist schwarz.",
  },
  Spielzeug: {
    n: "Das Spielzeug liegt am Boden.",
    a: "Das Kind mag das Spielzeug.",
    d: "Sie spielt mit dem Spielzeug.",
    g: "Die Qualität des Spielzeugs ist gut.",
  },
  Berg: {
    n: "Der Berg ist sehr hoch.",
    a: "Ich besteige den Berg.",
    d: "Er wandert auf dem Berg.",
    g: "Die Spitze des Berges ist weiß.",
  },
  See: {
    n: "Der See ist tief.",
    a: "Ich sehe den See.",
    d: "Wir schwimmen in dem See.",
    g: "Das Ufer des Sees ist steinig.",
  },
  Mond: {
    n: "Der Mond leuchtet hell.",
    a: "Ich sehe den Mond nachts.",
    d: "Es gibt kein Leben auf dem Mond.",
    g: "Das Licht des Mondes ist silbern.",
  },
  Tür: {
    n: "Die Tür ist offen.",
    a: "Ich öffne die Tür.",
    d: "Er klopft an die Tür.",
    g: "Der Schlüssel der Tür ist weg.",
  },
  Zahn: {
    n: "Der Zahn tut weh.",
    a: "Der Arzt zieht den Zahn.",
    d: "Er hat Schmerzen an dem Zahn.",
    g: "Die Wurzel des Zahnes ist lang.",
  },
  Wolke: {
    n: "Die Wolke verdeckt die Sonne.",
    a: "Ich beobachte die Wolke.",
    d: "Es regnet aus der Wolke.",
    g: "Die Form der Wolke ist seltsam.",
  },
  Boden: {
    n: "Der Boden ist sauber.",
    a: "Ich wische den Boden.",
    d: "Sie sitzt auf dem Boden.",
    g: "Das Material des Bodens ist Holz.",
  },
  Nase: {
    n: "Die Nase läuft.",
    a: "Er putzt sich die Nase.",
    d: "Er hat einen Pickel auf der Nase.",
    g: "Die Form der Nase ist gerade.",
  },
  Mütze: {
    n: "Die Mütze hält warm.",
    a: "Ich setze die Mütze auf.",
    d: "Er geht mit der Mütze raus.",
    g: "Die Farbe der Mütze ist rot.",
  },
  Zunge: {
    n: "Die Zunge ist ein Muskel.",
    a: "Er zeigt die Zunge.",
    d: "Er hat sich an der Zunge verbrannt.",
    g: "Die Oberfläche der Zunge ist rau.",
  },
  Kamera: {
    n: "Die Kamera macht gute Fotos.",
    a: "Ich kaufe die Kamera.",
    d: "Er fotografiert mit der Kamera.",
    g: "Das Objektiv der Kamera ist teuer.",
  },
  Gitarre: {
    n: "Die Gitarre klingt gut.",
    a: "Ich spiele die Gitarre.",
    d: "Er übt auf der Gitarre.",
    g: "Die Saiten der Gitarre sind neu.",
  },
  Musik: {
    n: "Die Musik ist laut.",
    a: "Ich höre die Musik.",
    d: "Sie tanzt zu der Musik.",
    g: "Der Rhythmus der Musik ist schnell.",
  },
  Blatt: {
    n: "Das Blatt fällt vom Baum.",
    a: "Ich nehme das Blatt.",
    d: "Auf dem Blatt steht ein Name.",
    g: "Die Adern des Blatts sind grün.",
  },
  Sofa: {
    n: "Das Sofa ist bequem.",
    a: "Wir kaufen das Sofa.",
    d: "Er liegt auf dem Sofa.",
    g: "Der Bezug des Sofas ist aus Leder.",
  },
  Glas: {
    n: "Das Glas ist zerbrechlich.",
    a: "Ich fülle das Glas.",
    d: "Er trinkt aus dem Glas.",
    g: "Der Rand des Glases ist dünn.",
  },
  Zoo: {
    n: "Der Zoo ist heute gut besucht.",
    a: "Wir besuchen den Zoo.",
    d: "Er arbeitet in dem Zoo.",
    g: "Die Tiere des Zoos sind gesund.",
  },
  Familie: {
    n: "Die Familie ist glücklich.",
    a: "Er liebt seine Familie.",
    d: "Sie hilft der Familie.",
    g: "Das Haus der Familie ist groß.",
  },
  Tasche: {
    n: "Die Tasche ist schwer.",
    a: "Ich trage die Tasche.",
    d: "In der Tasche ist mein Schlüssel.",
    g: "Der Henkel der Tasche ist kaputt.",
  },
  Dach: {
    n: "Das Dach ist steil.",
    a: "Der Handwerker repariert das Dach.",
    d: "Auf dem Dach sitzt ein Vogel.",
    g: "Die Ziegel des Dachs sind rot.",
  },
  Hemd: {
    n: "Das Hemd ist gebügelt.",
    a: "Er trägt das Hemd.",
    d: "Mit dem Hemd sieht er gut aus.",
    g: "Die Knöpfe des Hemds sind weiß.",
  },
  Park: {
    n: "Der Park ist grün.",
    a: "Ich besuche den Park.",
    d: "Wir laufen in dem Park.",
    g: "Die Bänke des Parks sind neu.",
  },
  Bahn: {
    n: "Die Bahn kommt pünktlich.",
    a: "Ich nehme die Bahn.",
    d: "Er fährt mit der Bahn.",
    g: "Der Fahrplan der Bahn hat sich geändert.",
  },
  Brille: {
    n: "Die Brille ist sauber.",
    a: "Ich putze die Brille.",
    d: "Er liest mit der Brille.",
    g: "Das Gestell der Brille ist modern.",
  },
  Schnee: {
    n: "Der Schnee schmilzt.",
    a: "Ich mag den Schnee.",
    d: "Die Kinder spielen im Schnee.",
    g: "Die Pracht des Schnees ist weiß.",
  },
  Treppe: {
    n: "Die Treppe ist aus Stein.",
    a: "Er steigt die Treppe hoch.",
    d: "Er steht auf der Treppe.",
    g: "Das Geländer der Treppe ist stabil.",
  },
  Küche: {
    n: "Die Küche ist modern.",
    a: "Ich putze die Küche.",
    d: "Er kocht in der Küche.",
    g: "Die Geräte der Küche sind neu.",
  },
  Fluss: {
    n: "Der Fluss fließt schnell.",
    a: "Wir überqueren den Fluss.",
    d: "Er angelt an dem Fluss.",
    g: "Das Wasser des Flusses ist klar.",
  },
  Ei: {
    n: "Das Ei ist gekocht.",
    a: "Ich schäle das Ei.",
    d: "Sie backt mit dem Ei.",
    g: "Die Schale des Eis ist weiß.",
  },
  Lehrer: {
    n: "Der Lehrer ist freundlich.",
    a: "Ich frage den Lehrer.",
    d: "Die Schüler hören dem Lehrer zu.",
    g: "Das Pult des Lehrers ist ordentlich.",
  },
  Lehrerin: {
    n: "Die Lehrerin erklärt gut.",
    a: "Ich besuche die Lehrerin.",
    d: "Die Kinder antworten der Lehrerin.",
    g: "Die Tasche der Lehrerin ist braun.",
  },
  Tafel: {
    n: "Die Tafel ist schwarz.",
    a: "Er schreibt an die Tafel.",
    d: "Auf der Tafel steht eine Aufgabe.",
    g: "Die Oberfläche der Tafel ist glatt.",
  },
  Feder: {
    n: "Die Feder ist sehr leicht.",
    a: "Ich finde die Feder.",
    d: "Er schreibt mit der Feder.",
    g: "Das Kleid der Feder ist weich.",
  },
  Schlüssel: {
    n: "Der Schlüssel passt ins Schloss.",
    a: "Ich suche den Schlüssel.",
    d: "Er öffnet die Tür mit dem Schlüssel.",
    g: "Der Bart des Schlüssels ist aus Metall.",
  },
  Spiegel: {
    n: "Der Spiegel ist groß.",
    a: "Ich putze den Spiegel.",
    d: "Sie betrachtet sich in dem Spiegel.",
    g: "Der Rahmen des Spiegels ist golden.",
  },
  Hut: {
    n: "Der Hut steht ihm gut.",
    a: "Er setzt den Hut auf.",
    d: "Er geht mit dem Hut spazieren.",
    g: "Die Krempe des Hutes ist breit.",
  },
  Kuchen: {
    n: "Der Kuchen schmeckt köstlich.",
    a: "Ich backe einen Kuchen.",
    d: "Sie hilft mir bei dem Kuchen.",
    g: "Die Glasur des Kuchens ist süß.",
  },
  Schlange: {
    n: "Die Schlange ist gefährlich.",
    a: "Ich sehe die Schlange.",
    d: "Er hat Angst vor der Schlange.",
    g: "Die Haut der Schlange ist schuppig.",
  },
  Schuh: {
    n: "Der Schuh ist bequem.",
    a: "Ich binde den Schuh.",
    d: "Er läuft in dem Schuh.",
    g: "Die Sohle des Schuhes ist abgenutzt.",
  },
  Fahrrad: {
    n: "Das Fahrrad ist schnell.",
    a: "Ich fahre das Fahrrad.",
    d: "Er kommt mit dem Fahrrad.",
    g: "Das Rad des Fahrrads ist platt.",
  },
  Messer: {
    n: "Das Messer ist scharf.",
    a: "Ich nehme das Messer.",
    d: "Er schneidet mit dem Messer.",
    g: "Die Klinge des Messers glänzt.",
  },
  Schal: {
    n: "Der Schal ist warm.",
    a: "Ich trage den Schal.",
    d: "Sie geht mit dem Schal raus.",
    g: "Das Muster des Schales ist bunt.",
  },
  Handschuh: {
    n: "Der Handschuh schützt vor Kälte.",
    a: "Er zieht den Handschuh an.",
    d: "Er sucht nach dem Handschuh.",
    g: "Das Leder des Handschuhes ist weich.",
  },
  Papier: {
    n: "Das Papier ist weiß.",
    a: "Ich brauche das Papier.",
    d: "Er schreibt auf dem Papier.",
    g: "Der Rand des Papiers ist glatt.",
  },
  Brief: {
    n: "Der Brief ist angekommen.",
    a: "Ich schreibe einen Brief.",
    d: "Er antwortet auf den Brief.",
    g: "Der Inhalt des Briefes ist wichtig.",
  },
  Schlafzimmer: {
    n: "Das Schlafzimmer ist gemütlich.",
    a: "Ich renoviere das Schlafzimmer.",
    d: "Sie schläft in dem Schlafzimmer.",
    g: "Das Fenster des Schlafzimmers ist offen.",
  },
  Handy: {
    n: "Das Handy klingelt.",
    a: "Ich benutze das Handy.",
    d: "Er telefoniert mit dem Handy.",
    g: "Das Display des Handys ist kaputt.",
  },
  Keller: {
    n: "Der Keller ist dunkel.",
    a: "Ich räume den Keller auf.",
    d: "Die Vorräte sind im Keller.",
    g: "Die Tür des Kellers ist abgeschlossen.",
  },
  Müll: {
    n: "Der Müll stinkt.",
    a: "Ich bringe den Müll raus.",
    d: "Es liegt viel Glas im Müll.",
    g: "Die Tonne des Mülles ist voll.",
  },
  Mauer: {
    n: "Die Mauer ist stabil.",
    a: "Er baut eine Mauer.",
    d: "Ein Vogel sitzt auf der Mauer.",
    g: "Die Steine der Mauer sind grau.",
  },
  Eule: {
    n: "Die Eule jagt nachts.",
    a: "Ich sehe eine Eule.",
    d: "Die Maus flieht vor der Eule.",
    g: "Die Augen der Eule sind groß.",
  },
  Bahnsteig: {
    n: "Der Bahnsteig ist voll.",
    a: "Wir betreten den Bahnsteig.",
    d: "Wir warten auf dem Bahnsteig.",
    g: "Die Nummer des Bahnsteiges ist vier.",
  },
  Bier: {
    n: "Das Bier ist kalt.",
    a: "Er trinkt das Bier.",
    d: "Er sitzt bei einem Bier.",
    g: "Der Geschmack des Bieres ist herb.",
  },
  Stift: {
    n: "Der Stift schreibt blau.",
    a: "Ich benutze den Stift.",
    d: "Er zeichnet mit dem Stift.",
    g: "Die Mine des Stiftes ist leer.",
  },
  Löffel: {
    n: "Der Löffel ist aus Silber.",
    a: "Ich nehme den Löffel.",
    d: "Er isst die Suppe mit dem Löffel.",
    g: "Die Form des Löffels ist rund.",
  },
  Schere: {
    n: "Die Schere ist scharf.",
    a: "Ich benutze die Schere.",
    d: "Sie schneidet mit der Schere.",
    g: "Der Griff der Schere ist blau.",
  },
  Kissen: {
    n: "Das Kissen ist weich.",
    a: "Ich brauche das Kissen.",
    d: "Er schläft auf dem Kissen.",
    g: "Der Bezug des Kissens ist sauber.",
  },
  Regen: {
    n: "Der Regen fällt leise.",
    a: "Ich mag den Regen.",
    d: "Wir spazieren im Regen.",
    g: "Das Geräusch des Regens beruhigt.",
  },
  Papiere: {
    n: "Die Papiere liegen hier.",
    a: "Ich ordne die Papiere.",
    d: "Er arbeitet mit den Papieren.",
    g: "Die Ordnung der Papiere ist wichtig.",
  },
  Schuhe: {
    n: "Die Schuhe passen gut.",
    a: "Ich kaufe die Schuhe.",
    d: "Ich laufe in den Schuhen.",
    g: "Die Farbe der Schuhe ist schwarz.",
  },
  Pferd: {
    n: "Das Pferd galoppiert.",
    a: "Er reitet das Pferd.",
    d: "Sie gibt dem Pferd einen Apfel.",
    g: "Der Rücken des Pferds ist stark.",
  },
  Kuh: {
    n: "Die Kuh gibt Milch.",
    a: "Der Bauer melkt die Kuh.",
    d: "Er steht neben der Kuh.",
    g: "Das Euter der Kuh ist voll.",
  },
  Huhn: {
    n: "Das Huhn legt ein Ei.",
    a: "Ich füttere das Huhn.",
    d: "Er läuft hinter dem Huhn her.",
    g: "Das Gefieder des Huhns ist weiß.",
  },
  Hahn: {
    n: "Der Hahn kräht morgens.",
    a: "Ich sehe den Hahn.",
    d: "Die Hennen folgen dem Hahn.",
    g: "Der Kamm des Hahnes ist rot.",
  },
  Schaf: {
    n: "Das Schaf hat viel Wolle.",
    a: "Der Schäfer hütet das Schaf.",
    d: "Er steht bei dem Schaf.",
    g: "Die Wolle des Schafs ist warm.",
  },
  Ziege: {
    n: "Die Ziege meckert laut.",
    a: "Er beobachtet die Ziege.",
    d: "Er gibt der Ziege Futter.",
    g: "Die Hörner der Ziege sind krumm.",
  },
  Ente: {
    n: "Die Ente schwimmt auf dem See.",
    a: "Ich füttere die Ente.",
    d: "Wir schauen der Ente zu.",
    g: "Der Schnabel der Ente ist gelb.",
  },
  Hase: {
    n: "Der Hase hoppelt über das Feld.",
    a: "Ich sehe den Hasen.",
    d: "Der Hund rennt hinter dem Hasen her.",
    g: "Die Ohren des Hasen sind lang.",
  },
  Fuchs: {
    n: "Der Fuchs ist ein Listentier.",
    a: "Der Jäger sieht den Fuchs.",
    d: "Die Gans hat Angst vor dem Fuchs.",
    g: "Der Schwanz des Fuchses ist buschig.",
  },
  Wolf: {
    n: "Der Wolf heult nachts.",
    a: "Ich fürchte den Wolf.",
    d: "Rotkäppchen begegnet dem Wolf.",
    g: "Das Gebiss des Wolfes ist gefährlich.",
  },
  Bär: {
    n: "Der Bär frisst Honig.",
    a: "Wir beobachten den Bären.",
    d: "Er steht vor dem Bären.",
    g: "Die Kraft des Bären ist groß.",
  },
  Eichhörnchen: {
    n: "Das Eichhörnchen sammelt Nüsse.",
    a: "Ich sehe das Eichhörnchen.",
    d: "Wir folgen dem Eichhörnchen.",
    g: "Der Schwanz des Eichhörnchens ist lang.",
  },
  Igel: {
    n: "Der Igel hat viele Stacheln.",
    a: "Ich finde einen Igel.",
    d: "Er hilft dem Igel im Winter.",
    g: "Die Stacheln des Igels sind spitz.",
  },
  Elefant: {
    n: "Der Elefant ist sehr schwer.",
    a: "Wir sehen den Elefanten.",
    d: "Die Kinder reiten auf dem Elefanten.",
    g: "Der Rüssel des Elefanten ist lang.",
  },
  Löwe: {
    n: "Der Löwe ist der König der Tiere.",
    a: "Ich sehe den Löwen im Zoo.",
    d: "Er steht gegenüber dem Löwen.",
    g: "Die Mähne des Löwen ist prachtvoll.",
  },
  Tiger: {
    n: "Der Tiger hat Streifen.",
    a: "Ich bewundere den Tiger.",
    d: "Wir stehen vor dem Tiger.",
    g: "Das Fell des Tigers ist gemustert.",
  },
  Affe: {
    n: "Der Affe klettert auf den Baum.",
    a: "Ich füttere den Affen.",
    d: "Wir schauen dem Affen zu.",
    g: "Die Bewegungen des Affen sind flink.",
  },
  Giraffe: {
    n: "Die Giraffe hat einen langen Hals.",
    a: "Ich sehe die Giraffe.",
    d: "Er gibt der Giraffe Blätter.",
    g: "Der Hals der Giraffe ist beeindruckend.",
  },
  Zebra: {
    n: "Das Zebra hat schwarz-weiße Streifen.",
    a: "Ich beobachte das Zebra.",
    d: "Wir stehen bei dem Zebra.",
    g: "Die Streifen des Zebras sind einzigartig.",
  },
  Pinguin: {
    n: "Der Pinguin lebt in der Antarktis.",
    a: "Ich mag den Pinguin.",
    d: "Es ist kalt bei dem Pinguin.",
    g: "Der Gang des Pinguins ist watschelig.",
  },
  Kamel: {
    n: "Das Kamel kann lange ohne Wasser leben.",
    a: "Er reitet das Kamel.",
    d: "Sie gibt dem Kamel Heu.",
    g: "Die Höcker des Kamels speichern Fett.",
  },
  Biene: {
    n: "Die Biene sammelt Nektar.",
    a: "Ich beobachte die Biene.",
    d: "Er wird von der Biene gestochen.",
    g: "Der Honig der Biene ist süß.",
  },
  Schmetterling: {
    n: "Der Schmetterling ist bunt.",
    a: "Ich sehe den Schmetterling.",
    d: "Er folgt dem Schmetterling.",
    g: "Die Flügel des Schmetterlings sind zart.",
  },
  Frosch: {
    n: "Der Frosch springt ins Wasser.",
    a: "Ich fange den Frosch.",
    d: "Er spielt mit dem Frosch.",
    g: "Das Quaken des Frosches ist laut.",
  },
  Krokodil: {
    n: "Das Krokodil liegt im Fluss.",
    a: "Ich sehe das Krokodil.",
    d: "Er flieht vor dem Krokodil.",
    g: "Das Maul des Krokodils ist riesig.",
  },
  Esel: {
    n: "Der Esel trägt schwere Lasten.",
    a: "Er führt den Esel.",
    d: "Er hilft dem Esel.",
    g: "Das Schreien des Esels ist laut.",
  },
  Papagei: {
    n: "Der Papagei kann sprechen.",
    a: "Ich kaufe einen Papagei.",
    d: "Er bringt dem Papagei Wörter bei.",
    g: "Die Farben des Papageis sind bunt.",
  },
  Känguru: {
    n: "Das Känguru springt weit.",
    a: "Ich sehe das Känguru.",
    d: "Das Baby sitzt im Känguru.",
    g: "Der Beutel des Kängurus ist praktisch.",
  },
  Koala: {
    n: "Der Koala schläft auf dem Eukalyptusbaum.",
    a: "Ich mag den Koala.",
    d: "Wir schauen dem Koala zu.",
    g: "Die Nase des Koalas ist groß.",
  },
  Delphin: {
    n: "Der Delphin springt aus dem Wasser.",
    a: "Ich beobachte den Delphin.",
    d: "Er schwimmt mit dem Delphin.",
    g: "Die Intelligenz des Delphins ist bekannt.",
  },
  Wal: {
    n: "Der Wal ist das größte Säugetier.",
    a: "Wir sehen den Wal.",
    d: "Wir folgen dem Wal mit dem Schiff.",
    g: "Der Gesang des Wals ist faszinierend.",
  },
  Krabbe: {
    n: "Die Krabbe läuft seitwärts.",
    a: "Ich sehe eine Krabbe am Strand.",
    d: "Er spielt mit der Krabbe.",
    g: "Die Scheren der Krabbe sind scharf.",
  },
  Schildkröte: {
    n: "Die Schildkröte bewegt sich langsam.",
    a: "Ich füttere die Schildkröte.",
    d: "Er hilft der Schildkröte.",
    g: "Der Panzer der Schildkröte ist hart.",
  },
  Arzt: {
    n: "Der Arzt untersucht den Patienten.",
    a: "Ich besuche den Arzt.",
    d: "Er vertraut dem Arzt.",
    g: "Die Praxis des Arztes ist modern.",
  },
  Ärztin: {
    n: "Die Ärztin schreibt ein Rezept.",
    a: "Ich rufe die Ärztin an.",
    d: "Er antwortet der Ärztin.",
    g: "Die Tasche der Ärztin ist weiß.",
  },
  Kellner: {
    n: "Der Kellner bringt das Essen.",
    a: "Ich rufe den Kellner.",
    d: "Ich gebe dem Kellner Trinkgeld.",
    g: "Die Kleidung des Kellners ist schick.",
  },
  Kellnerin: {
    n: "Die Kellnerin ist sehr aufmerksam.",
    a: "Wir fragen die Kellnerin.",
    d: "Er dankt der Kellnerin.",
    g: "Das Lächeln der Kellnerin ist freundlich.",
  },
  Polizist: {
    n: "Der Polizist regelt den Verkehr.",
    a: "Ich frage den Polizisten nach dem Weg.",
    d: "Er zeigt dem Polizisten seinen Ausweis.",
    g: "Die Uniform des Polizisten ist blau.",
  },
  Polizistin: {
    n: "Die Polizistin hilft den Bürgern.",
    a: "Ich sehe die Polizistin.",
    d: "Wir antworten der Polizistin.",
    g: "Das Auto der Polizistin parkt dort.",
  },
  Verkäufer: {
    n: "Der Verkäufer berät die Kunden.",
    a: "Ich frage den Verkäufer.",
    d: "Sie dankt dem Verkäufer.",
    g: "Die Geduld des Verkäufers ist groß.",
  },
  Verkäuferin: {
    n: "Die Verkäuferin scannt die Ware.",
    a: "Ich sehe die Verkäuferin.",
    d: "Er gibt der Verkäuferin das Geld.",
    g: "Die Freundlichkeit der Verkäuferin hilft.",
  },
  Ingenieur: {
    n: "Der Ingenieur plant das Gebäude.",
    a: "Ich brauche einen Ingenieur.",
    d: "Wir arbeiten mit dem Ingenieur.",
    g: "Die Zeichnung des Ingenieurs ist präzise.",
  },
  Ingenieurin: {
    n: "Die Ingenieurin leitet das Projekt.",
    a: "Wir treffen die Ingenieurin.",
    d: "Er hilft der Ingenieurin.",
    g: "Der Plan der Ingenieurin ist fertig.",
  },
  Koch: {
    n: "Der Koch bereitet das Menü zu.",
    a: "Ich kenne den Koch.",
    d: "Wir schauen dem Koch zu.",
    g: "Die Mütze des Koches ist weiß.",
  },
  Köchin: {
    n: "Die Köchin würzt die Suppe.",
    a: "Ich mag die Köchin.",
    d: "Er hilft der Köchin.",
    g: "Das Rezept der Köchin ist geheim.",
  },
  Bäcker: {
    n: "Der Bäcker backt frisches Brot.",
    a: "Ich besuche den Bäcker.",
    d: "Er kauft bei dem Bäcker ein.",
    g: "Die Backstube des Bäckers ist heiß.",
  },
  Bäckerin: {
    n: "Die Bäckerin verkauft Brötchen.",
    a: "Ich sehe die Bäckerin.",
    d: "Er dankt der Bäckerin.",
    g: "Das Mehl der Bäckerin ist hochwertig.",
  },
  Friseurin: {
    n: "Die Friseurin schneidet die Haare.",
    a: "Ich brauche eine Friseurin.",
    d: "Er vertraut der Friseurin.",
    g: "Der Salon der Friseurin ist modern.",
  },
  Mechaniker: {
    n: "Der Mechaniker repariert das Auto.",
    a: "Ich rufe den Mechaniker.",
    d: "Er hilft dem Mechaniker.",
    g: "Das Werkzeug des Mechanikers ist schwer.",
  },
  Künstlerin: {
    n: "Die Künstlerin malt ein Bild.",
    a: "Ich bewundere die Künstlerin.",
    d: "Er schreibt der Künstlerin.",
    g: "Das Atelier der Künstlerin ist hell.",
  },
  Architekt: {
    n: "Der Architekt entwirft das Haus.",
    a: "Wir engagieren den Architekten.",
    d: "Wir sprechen mit dem Architekten.",
    g: "Das Büro des Architekten ist in der Stadt.",
  },
  Schüler: {
    n: "Der Schüler lernt für den Test.",
    a: "Ich kenne den Schüler.",
    d: "Der Lehrer hilft dem Schüler.",
    g: "Das Heft des Schülers ist voll.",
  },
  Schülerin: {
    n: "Die Schülerin schreibt eine Hausaufgabe.",
    a: "Ich sehe die Schülerin.",
    d: "Er antwortet der Schülerin.",
    g: "Die Tasche der Schülerin ist neu.",
  },
  Student: {
    n: "Der Student besucht die Vorlesung.",
    a: "Ich kenne den Studenten.",
    d: "Das Buch gehört dem Studenten.",
    g: "Die Wohnung des Studenten ist klein.",
  },
  Studentin: {
    n: "Die Studentin schreibt ihre Masterarbeit.",
    a: "Ich sehe die Studentin.",
    d: "Er hilft der Studentin.",
    g: "Das Fahrrad der Studentin ist rot.",
  },
  Krankenschwester: {
    n: "Die Krankenschwester hilft den Patienten.",
    a: "Ich rufe die Krankenschwester.",
    d: "Er dankt der Krankenschwester.",
    g: "Die Geduld der Krankenschwester ist groß.",
  },
  Krankenpflegerin: {
    n: "Die Krankenpflegerin kontrolliert den Puls.",
    a: "Ich sehe die Krankenpflegerin.",
    d: "Sie hilft der Krankenpflegerin.",
    g: "Der Kittel der Krankenpflegerin ist sauber.",
  },
  Bauer: {
    n: "Der Bauer bestellt das Feld.",
    a: "Ich kenne den Bauern.",
    d: "Die Ernte gehört dem Bauern.",
    g: "Der Hof des Bauern ist groß.",
  },
  Bäuerin: {
    n: "Die Bäuerin füttert die Tiere.",
    a: "Ich besuche die Bäuerin.",
    d: "Er hilft der Bäuerin.",
    g: "Der Traktor der Bäuerin ist alt.",
  },
  Pilot: {
    n: "Der Pilot fliegt das Flugzeug.",
    a: "Ich sehe den Piloten.",
    d: "Wir vertrauen dem Piloten.",
    g: "Die Uniform des Piloten ist dunkelblau.",
  },
  Sekretärin: {
    n: "Die Sekretärin organisiert die Termine.",
    a: "Ich frage die Sekretärin.",
    d: "Er gibt der Sekretärin das Dokument.",
    g: "Der Schreibtisch der Sekretärin ist ordentlich.",
  },
  Journalistin: {
    n: "Die Journalistin schreibt einen Artikel.",
    a: "Ich interviewe die Journalistin.",
    d: "Er folgt der Journalistin.",
    g: "Die Kamera der Journalistin ist teuer.",
  },
  Musiker: {
    n: "Der Musiker spielt Geige.",
    a: "Ich höre dem Musiker zu.",
    d: "Wir applaudieren dem Musiker.",
    g: "Das Instrument des Musikers ist alt.",
  },
  Busfahrer: {
    n: "Der Busfahrer stoppt an der Haltestelle.",
    a: "Ich grüße den Busfahrer.",
    d: "Er dankt dem Busfahrer.",
    g: "Der Sitz des Busfahrers ist gefedert.",
  },
  Feuerwehrmann: {
    n: "Der Feuerwehrmann löscht das Feuer.",
    a: "Ich sehe den Feuerwehrmann.",
    d: "Wir helfen dem Feuerwehrmann.",
    g: "Der Helm des Feuerwehrmanns glänzt.",
  },
  Postbote: {
    n: "Der Postbote bringt die Briefe.",
    a: "Ich sehe den Postboten.",
    d: "Er gibt dem Postboten ein Paket.",
    g: "Die Tasche des Postboten ist gelb.",
  },
  Fotograf: {
    n: "Der Fotograf macht ein Porträt.",
    a: "Ich engagiere den Fotografen.",
    d: "Wir schauen dem Fotografen zu.",
    g: "Das Studio des Fotografen ist groß.",
  },
  Vertrag: {
    n: "Der Vertrag liegt zur Unterschrift bereit.",
    a: "Er unterschreibt den Vertrag morgen.",
    d: "Mit dem Vertrag ist alles geregelt.",
    g: "Die Bedingungen des Vertrags sind fair.",
  },
  Bewerbung: {
    n: "Die Bewerbung muss bis Freitag raus sein.",
    a: "Sie schickt die Bewerbung per E-Mail.",
    d: "Mit der Bewerbung legt er sein Zeugnis bei.",
    g: "Der Inhalt der Bewerbung ist sehr gut.",
  },
  Rechnung: {
    n: "Die Rechnung kommt nächste Woche.",
    a: "Er bezahlt die Rechnung sofort.",
    d: "Mit der Rechnung weist man den Kauf nach.",
    g: "Der Betrag der Rechnung ist zu hoch.",
  },
  Versicherung: {
    n: "Die Versicherung übernimmt die Kosten.",
    a: "Er kündigt die Versicherung.",
    d: "Mit der Versicherung ist man auf der sicheren Seite.",
    g: "Die Bedingungen der Versicherung sind klar.",
  },
  Krankenhaus: {
    n: "Das Krankenhaus ist neu.",
    a: "Ich besuche das Krankenhaus.",
    d: "Er arbeitet in dem Krankenhaus.",
    g: "Die Ärzte des Krankenhauses sind gut.",
  },
  Medikament: {
    n: "Das Medikament hilft gegen Schmerzen.",
    a: "Ich nehme das Medikament ein.",
    d: "Er fragt nach dem Medikament.",
    g: "Die Wirkung des Medikaments ist stark.",
  },
  Rezept: {
    n: "Das Rezept ist vom Arzt.",
    a: "Er bringt das Rezept zur Apotheke.",
    d: "Mit dem Rezept bekommt er die Medizin.",
    g: "Die Unterschrift des Rezepts ist wichtig.",
  },
  Termin: {
    n: "Der Termin ist morgen.",
    a: "Ich habe den Termin vergessen.",
    d: "Er kommt zu dem Termin.",
    g: "Die Uhrzeit des Termins ist 10 Uhr.",
  },
  Gehalt: {
    n: "Das Gehalt wird am Ende des Monats gezahlt.",
    a: "Er verhandelt das Gehalt beim Vorstellungsgespräch.",
    d: "Mit dem Gehalt kann sie die Miete zahlen.",
    g: "Die Höhe des Gehalts hängt von der Erfahrung ab.",
  },
  Urlaub: {
    n: "Der Urlaub war wunderschön und erholsam.",
    a: "Ich plane den Urlaub für den Sommer.",
    d: "Im Urlaub schläft man lange aus.",
    g: "Das Ende des Urlaubs macht mich traurig.",
  },
  Reisepass: {
    n: "Der Reisepass ist noch zehn Jahre gültig.",
    a: "Ich zeige den Reisepass an der Grenze.",
    d: "Ohne den Reisepass kommt man nicht rein.",
    g: "Die Nummer des Reisepasses steht vorne.",
  },
  Koffer: {
    n: "Der Koffer ist zu schwer für das Flugzeug.",
    a: "Ich packe den Koffer für den Urlaub.",
    d: "Er schleppt mit dem Koffer durch den Bahnhof.",
    g: "Das Schloss des Koffers ist kaputt.",
  },
  Hotel: {
    n: "Das Hotel liegt direkt am Strand.",
    a: "Ich buche das Hotel für zwei Nächte.",
    d: "Im Hotel gibt es ein schönes Restaurant.",
    g: "Das Zimmer des Hotels ist sehr sauber.",
  },
  Flughafen: {
    n: "Der Flughafen ist sehr modern.",
    a: "Wir fahren zum Flughafen mit dem Bus.",
    d: "Am Flughafen gibt es viele Geschäfte.",
    g: "Das Terminal des Flughafens ist riesig.",
  },
  Grenze: {
    n: "Die Grenze zwischen den Ländern ist offen.",
    a: "Wir überqueren die Grenze um Mitternacht.",
    d: "An der Grenze kontrolliert man den Pass.",
    g: "Der Übergang der Grenze dauert lange.",
  },
  Gewitter: {
    n: "Das Gewitter zieht auf.",
    a: "Ich sehe das Gewitter kommen.",
    d: "Nach dem Gewitter ist die Luft frisch.",
    g: "Der Donner des Gewitters ist laut.",
  },
  Temperatur: {
    n: "Die Temperatur steigt schnell.",
    a: "Ich messe die Temperatur.",
    d: "Bei dieser Temperatur friere ich.",
    g: "Der Anstieg der Temperatur ist messbar.",
  },
  Umgebung: {
    n: "Die Umgebung ist sehr ruhig.",
    a: "Wir erkunden die Umgebung.",
    d: "In dieser Umgebung fühle ich mich wohl.",
    g: "Die Schönheit der Umgebung fasziniert mich.",
  },
  Gesellschaft: {
    n: "Die Gesellschaft verändert sich.",
    a: "Er kritisiert die Gesellschaft.",
    d: "In der Gesellschaft gibt es viele Regeln.",
    g: "Die Probleme der Gesellschaft sind komplex.",
  },
  Wirtschaft: {
    n: "Die Wirtschaft wächst langsam.",
    a: "Er studiert Wirtschaft.",
    d: "Die Krise schadet der Wirtschaft.",
    g: "Die Lage der Wirtschaft ist stabil.",
  },
  Ball: {
    n: "Der Ball rollt ins Tor.",
    a: "Er schießt den Ball.",
    d: "Das Kind spielt mit dem Ball.",
    g: "Die Farbe des Balles ist gelb.",
  },
  Fußball: {
    n: "Der Fußball ist ein beliebter Sport.",
    a: "Ich schaue gerne Fußball.",
    d: "Er ist Profi beim Fußball.",
    g: "Die Regeln des Fußballs sind einfach.",
  },
  Schwimmbad: {
    n: "Das Schwimmbad ist im Sommer voll.",
    a: "Wir besuchen das Schwimmbad.",
    d: "Er schwimmt in dem Schwimmbad.",
    g: "Das Wasser des Schwimmbads ist warm.",
  },
  Stadion: {
    n: "Das Stadion ist ausverkauft.",
    a: "Wir sehen das Stadion.",
    d: "Die Fans singen im Stadion.",
    g: "Die Architektur des Stadions ist modern.",
  },
  Mannschaft: {
    n: "Die Mannschaft spielt sehr gut.",
    a: "Ich unterstütze die Mannschaft.",
    d: "Er gehört zu der Mannschaft.",
    g: "Der Erfolg der Mannschaft ist wichtig.",
  },
  Wind: {
    n: "Der Wind weht stark.",
    a: "Ich spüre den Wind.",
    d: "Er steht im Wind.",
    g: "Die Stärke des Windes nimmt zu.",
  },
  Nebel: {
    n: "Der Nebel ist sehr dicht.",
    a: "Ich sehe durch den Nebel nichts.",
    d: "Im Nebel fahren wir langsam.",
    g: "Die Dichte des Nebels ist gefährlich.",
  },
  Frost: {
    n: "Der Frost überzieht die Wiese.",
    a: "Ich mag den Frost nicht.",
    d: "Bei Frost muss man vorsichtig fahren.",
    g: "Die Kälte des Frostes ist beißend.",
  },
  Sturm: {
    n: "Der Sturm entwurzelt Bäume.",
    a: "Ich höre den Sturm draußen.",
    d: "In dem Sturm fliegen Blätter.",
    g: "Die Gewalt des Sturmes ist groß.",
  },
  Mutter: {
    n: "Die Mutter kocht gerne.",
    a: "Ich liebe die Mutter.",
    d: "Er hilft der Mutter.",
    g: "Das Lachen der Mutter ist ansteckend.",
  },
  Vater: {
    n: "Der Vater arbeitet viel.",
    a: "Ich respektiere den Vater.",
    d: "Er fährt mit dem Vater.",
    g: "Der Beruf des Vaters ist Ingenieur.",
  },
  Kind: {
    n: "Das Kind spielt draußen.",
    a: "Ich sehe das Kind.",
    d: "Sie hilft dem Kind.",
    g: "Die Mutter des Kindes kommt.",
  },
  Bruder: {
    n: "Der Bruder ist nett.",
    a: "Ich besuche den Bruder.",
    d: "Er spielt mit dem Bruder.",
    g: "Das Zimmer des Bruders ist groß.",
  },
  Schwester: {
    n: "Die Schwester ist lustig.",
    a: "Ich mag die Schwester.",
    d: "Er streitet mit der Schwester.",
    g: "Das Buch der Schwester ist neu.",
  },
  Opa: {
    n: "Der Opa erzählt Geschichten.",
    a: "Ich besuche den Opa.",
    d: "Er hilft dem Opa.",
    g: "Die Brille des Opas liegt hier.",
  },
  Oma: {
    n: "Die Oma backt Kuchen.",
    a: "Ich liebe die Oma.",
    d: "Er schenkt der Oma Blumen.",
    g: "Der Garten der Oma ist schön.",
  },
  Baby: {
    n: "Das Baby schläft im Bett.",
    a: "Ich halte das Baby.",
    d: "Sie spielt mit dem Baby.",
    g: "Das Lächeln des Babys ist süß.",
  },
  Arztpraxis: {
    n: "Die Arztpraxis ist im ersten Stock.",
    a: "Ich betrete die Arztpraxis.",
    d: "In der Arztpraxis warten viele Leute.",
    g: "Die Tür der Arztpraxis ist geschlossen.",
  },
  Fieber: {
    n: "Das Fieber steigt auf 39 Grad.",
    a: "Er bekommt das Fieber nach dem Regen.",
    d: "Bei Fieber soll man viel trinken.",
    g: "Die Messung des Fiebers zeigt 38,5 Grad.",
  },
  Husten: {
    n: "Der Husten kommt und geht.",
    a: "Der Arzt behandelt den Husten mit Sirup.",
    d: "Beim Husten nimmt er eine Tablette.",
    g: "Das Mittel gegen den Husten hilft sofort.",
  },
  Kopfschmerz: {
    n: "Der Kopfschmerz ist nach der Tablette weg.",
    a: "Sie klagt über den Kopfschmerz seit Stunden.",
    d: "Bei Kopfschmerz legt sie sich hin.",
    g: "Die Ursache des Kopfschmerzes ist unklar.",
  },
  Apotheke: {
    n: "Die Apotheke hat Notdienst.",
    a: "Ich gehe in die Apotheke.",
    d: "In der Apotheke kaufe ich Medizin.",
    g: "Das Schild der Apotheke leuchtet.",
  },
  Suppe: {
    n: "Die Suppe ist heiß und lecker.",
    a: "Er löffelt die Suppe langsam.",
    d: "Mit der Suppe wärmt man sich auf.",
    g: "Der Geschmack der Suppe ist würzig.",
  },
  Salat: {
    n: "Der Salat ist frisch und knackig.",
    a: "Sie bereitet den Salat vor dem Essen zu.",
    d: "Mit dem Salat isst er das Steak.",
    g: "Das Dressing des Salats ist selbstgemacht.",
  },
  Käse: {
    n: "Der Käse ist schon ein bisschen alt.",
    a: "Er schneidet den Käse in kleine Stücke.",
    d: "Mit dem Käse belegt er das Brot.",
    g: "Der Geruch des Käses ist intensiv.",
  },
  Butter: {
    n: "Die Butter ist weich.",
    a: "Ich kaufe die Butter.",
    d: "Ich streiche Brot mit der Butter.",
    g: "Der Preis der Butter ist gestiegen.",
  },
  Fleisch: {
    n: "Das Fleisch ist zart.",
    a: "Er isst kein Fleisch.",
    d: "In dem Fleisch sind Gewürze.",
    g: "Die Qualität des Fleischs ist gut.",
  },
  Obst: {
    n: "Das Obst liegt in der Schale.",
    a: "Wir essen viel Obst.",
    d: "In dem Obst sind Vitamine.",
    g: "Die Frische des Obsts ist wichtig.",
  },
  Arm: {
    n: "Der Arm tut nach dem Sport weh.",
    a: "Er bricht sich den Arm beim Skateboard.",
    d: "Mit dem Arm winkt er ihr zu.",
    g: "Die Muskeln des Arms sind stark.",
  },
  Bein: {
    n: "Das Bein ist nach dem Laufen müde.",
    a: "Sie streckt das Bein nach vorne.",
    d: "Mit dem Bein tritt er gegen den Ball.",
    g: "Der Knochen des Beins ist sehr stabil.",
  },
  Kopf: {
    n: "Der Kopf ist rund.",
    a: "Er schüttelt den Kopf.",
    d: "Er hat Schmerzen im Kopf.",
    g: "Die Form des Kopfes ist symmetrisch.",
  },
  Rücken: {
    n: "Der Rücken schmerzt nach langem Sitzen.",
    a: "Sie stärkt den Rücken mit Sport.",
    d: "Am Rücken trägt er einen Rucksack.",
    g: "Die Mitte des Rückens ist besonders empfindliche.",
  },
  Bauch: {
    n: "Der Bauch ist voll.",
    a: "Er streichelt sich den Bauch.",
    d: "Er hat Schmerzen in dem Bauch.",
    g: "Der Umfang des Bauches nimmt zu.",
  },
  Ohr: {
    n: "Das Ohr hört Geräusche.",
    a: "Ich reinige das Ohr.",
    d: "Sie hat einen Ring am Ohr.",
    g: "Die Muschel des Ohrs ist klein.",
  },
  Mund: {
    n: "Der Mund lacht.",
    a: "Er öffnet den Mund.",
    d: "Er hat Essen in dem Mund.",
    g: "Die Mundwinkel des Mundes gehen nach oben.",
  },
  Haar: {
    n: "Das Haar ist glänzend.",
    a: "Sie kämmt das Haar.",
    d: "Er hat graue Stellen im Haar.",
    g: "Die Farbe des Haars ist braun.",
  },
  Schulter: {
    n: "Die Schulter schmerzt seit gestern.",
    a: "Er massiert die Schulter seiner Frau.",
    d: "An der Schulter trägt sie eine Tasche.",
    g: "Die Muskeln der Schulter sind verspannt.",
  },
  Knie: {
    n: "Das Knie schwillt nach dem Sturz an.",
    a: "Er verletzt sich das Knie beim Fußball.",
    d: "Am Knie trägt sie eine Bandage.",
    g: "Die Schwellung des Knies geht langsam weg.",
  },
  Fuß: {
    n: "Der Fuß ist groß.",
    a: "Er verletzt den Fuß.",
    d: "Er steht auf einem Fuß.",
    g: "Die Zehen des Fußes sind kurz.",
  },
  Finger: {
    n: "Der Finger zeigt auf das Bild.",
    a: "Er schneidet sich in den Finger.",
    d: "Er hat einen Ring am Finger.",
    g: "Der Nagel des Fingers ist sauber.",
  },
  Herz: {
    n: "Das Herz schlägt schnell nach dem Rennen.",
    a: "Der Arzt untersucht das Herz.",
    d: "Mit dem Herz fühlt man die Liebe.",
    g: "Der Rhythmus des Herzens ist regelmäßig.",
  },
  Blut: {
    n: "Das Blut ist rot.",
    a: "Der Arzt nimmt Blut ab.",
    d: "In dem Blut ist viel Eisen.",
    g: "Die Gruppe des Bluts ist A-positiv.",
  },
  Schmerz: {
    n: "Der Schmerz lässt nach.",
    a: "Ich spüre einen Schmerz.",
    d: "Er weint vor Schmerz.",
    g: "Die Intensität des Schmerzes ist hoch.",
  },
  Allergie: {
    n: "Die Allergie gegen Pollen beginnt im Frühling.",
    a: "Der Arzt diagnostiziert die Allergie.",
    d: "Bei der Allergie helfen spezielle Tropfen.",
    g: "Die Symptome der Allergie sind unangenehm.",
  },
  Impfung: {
    n: "Die Impfung schützt vor vielen Krankheiten.",
    a: "Das Kind bekommt die Impfung beim Arzt.",
    d: "Nach der Impfung ist der Arm etwas schmerzhaft.",
    g: "Der Termin der Impfung ist nächste Woche.",
  },
  Operation: {
    n: "Die Operation dauert drei Stunden.",
    a: "Er übersteht die Operation gut.",
    d: "Nach der Operation bleibt er im Krankenhaus.",
    g: "Das Ergebnis der Operation ist sehr gut.",
  },
  Kartoffel: {
    n: "Die Kartoffel ist in Deutschland sehr beliebt.",
    a: "Er schält die Kartoffel für das Abendessen.",
    d: "Mit der Kartoffel macht man viele Gerichte.",
    g: "Die Schale der Kartoffel ist essbar.",
  },
  Tomate: {
    n: "Die Tomate ist reif und rot.",
    a: "Sie schneidet die Tomate für den Salat.",
    d: "Mit der Tomate macht er eine Soße.",
    g: "Der Saft der Tomate ist sehr schmackhaft.",
  },
  Zwiebel: {
    n: "Die Zwiebel macht beim Schneiden die Augen nass.",
    a: "Er brät die Zwiebel in der Pfanne an.",
    d: "Mit der Zwiebel schmeckt die Suppe besser.",
    g: "Der Geruch der Zwiebel ist sehr stark.",
  },
  Möhre: {
    n: "Die Möhre ist gesund.",
    a: "Ich esse eine Möhre.",
    d: "Er kocht mit der Möhre.",
    g: "Die Farbe der Möhre ist orange.",
  },
  Gurke: {
    n: "Die Gurke ist sehr erfrischend im Sommer.",
    a: "Sie legt die Gurke in den Salat.",
    d: "Mit der Gurke macht man leckere Sandwiches.",
    g: "Der Duft der Gurke ist frisch und grün.",
  },
  Paprika: {
    n: "Die Paprika ist bunt und lecker.",
    a: "Er schneidet die Paprika in Streifen.",
    d: "Mit der Paprika gibt es viele Vitamine.",
    g: "Die Farbe der Paprika ist kräftig rot.",
  },
  Pilz: {
    n: "Der Pilz wächst im Wald.",
    a: "Ich sammle den Pilz.",
    d: "In dem Pilz steckt ein Wurm.",
    g: "Der Hut des Pilzes ist braun.",
  },
  Banane: {
    n: "Die Banane ist das perfekte Sportessen.",
    a: "Er isst die Banane vor dem Training.",
    d: "Mit der Banane macht sie einen Smoothie.",
    g: "Die Schale der Banane ist gelb und weich.",
  },
  Orange: {
    n: "Die Orange ist saftig.",
    a: "Ich schäle die Orange.",
    d: "In der Orange ist viel Vitamin C.",
    g: "Der Saft der Orange schmeckt gut.",
  },
  Erdbeere: {
    n: "Die Erdbeere schmeckt süß und frisch.",
    a: "Das Kind pflückt die Erdbeere im Garten.",
    d: "Mit der Erdbeere macht sie einen Kuchen.",
    g: "Der Duft der Erdbeere ist wunderbar.",
  },
  Trauben: {
    n: "Die Trauben sind süß.",
    a: "Ich wasche die Trauben.",
    d: "Er nascht von den Trauben.",
    g: "Die Farbe der Trauben ist grün.",
  },
  Zitrone: {
    n: "Die Zitrone ist sauer.",
    a: "Ich presse die Zitrone aus.",
    d: "Er trinkt Tee mit Zitrone.",
    g: "Die Schale der Zitrone ist gelb.",
  },
  Reis: {
    n: "Der Reis ist fertig gekocht.",
    a: "Sie wäscht den Reis vor dem Kochen.",
    d: "Mit dem Reis isst man das Curry.",
    g: "Die Konsistenz des Reises ist sehr wichtig.",
  },
  Nudeln: {
    n: "Die Nudeln kochen in zehn Minuten.",
    a: "Er kocht die Nudeln mit Soße.",
    d: "Mit Nudeln macht man viele leckere Gerichte.",
    g: "Die Zubereitung der Nudeln ist einfach.",
  },
  Joghurt: {
    n: "Der Joghurt schmeckt nach Erdbeere.",
    a: "Ich esse den Joghurt.",
    d: "Er rührt in dem Joghurt.",
    g: "Das Haltbarkeitsdatum des Joghurts ist heute.",
  },
  Milch: {
    n: "Die Milch ist schon zwei Tage alt.",
    a: "Er trinkt die Milch direkt aus dem Glas.",
    d: "Mit der Milch macht sie den Kakao.",
    g: "Der Fettgehalt der Milch ist unterschiedlich.",
  },
  Saft: {
    n: "Der Saft ist frisch gepresst.",
    a: "Er trinkt den Saft zum Frühstück.",
    d: "Mit dem Saft nimmt sie die Tablette.",
    g: "Der Geschmack des Saftes ist süß.",
  },
  Tee: {
    n: "Der Tee ist noch zu heiß zum Trinken.",
    a: "Sie trinkt den Tee am Morgen.",
    d: "Mit dem Tee wärmt man sich im Winter auf.",
    g: "Der Geschmack des Tees ist mild und angenehm.",
  },
  Wein: {
    n: "Der Wein kommt aus Frankreich.",
    a: "Sie bestellt den Wein im Restaurant.",
    d: "Mit dem Wein stößt man auf den Geburtstag an.",
    g: "Der Jahrgang des Weins ist sehr gut.",
  },
  Zucker: {
    n: "Der Zucker löst sich schnell im Wasser.",
    a: "Sie gibt den Zucker in den Kaffee.",
    d: "Mit zu viel Zucker ist der Tee zu süß.",
    g: "Die Menge des Zuckers ist wichtig beim Backen.",
  },
  Salz: {
    n: "Das Salz fehlt in der Suppe.",
    a: "Er streut das Salz auf die Eier.",
    d: "Mit dem Salz würzt sie das Fleisch.",
    g: "Die Menge des Salzes soll man begrenzen.",
  },
  Öl: {
    n: "Das Öl ist für den Salat.",
    a: "Sie erhitzt das Öl in der Pfanne.",
    d: "Mit dem Öl brät er das Gemüse an.",
    g: "Der Geschmack des Öls ist mild.",
  },
  Schokolade: {
    n: "Die Schokolade schmilzt in der Sonne.",
    a: "Das Kind isst die Schokolade zu schnell.",
    d: "Mit Schokolade backt man tolle Kuchen.",
    g: "Der Kakaogehalt der Schokolade ist hoch.",
  },
  Eis: {
    n: "Das Eis schmeckt im Sommer am besten.",
    a: "Ich esse ein Eis.",
    d: "Die Kinder freuen sich auf dem Eis.",
    g: "Die Kälte des Eis ist erfrischend.",
  },
  Pizza: {
    n: "Die Pizza ist knusprig.",
    a: "Ich bestelle eine Pizza.",
    d: "Ich esse bei einer Pizza.",
    g: "Der Belag der Pizza ist reichlich.",
  },
  Hamburger: {
    n: "Der Hamburger ist saftig.",
    a: "Ich esse einen Hamburger.",
    d: "Mit dem Hamburger ist er zufrieden.",
    g: "Das Fleisch des Hamburgers ist gegrillt.",
  },
  Hähnchen: {
    n: "Das Hähnchen brät im Ofen.",
    a: "Ich esse das Hähnchen.",
    d: "Er isst Reis mit dem Hähnchen.",
    g: "Die Haut des Hähnchens ist knusprig.",
  },
  Schrank: {
    n: "Der Schrank ist voller alter Kleider.",
    a: "Wir kaufen einen neuen Schrank für das Schlafzimmer.",
    d: "Im Schrank hängen alle Jacken.",
    g: "Die Tür des Schranks klemmt ein bisschen.",
  },
  Regal: {
    n: "Das Regal hängt schief an der Wand.",
    a: "Er baut das Regal alleine auf.",
    d: "Im Regal stehen viele Bücher.",
    g: "Die Bretter des Regals sind aus Holz.",
  },
  Vorhang: {
    n: "Der Vorhang lässt kein Licht herein.",
    a: "Sie zieht den Vorhang auf.",
    d: "Hinter dem Vorhang steht ein Sessel.",
    g: "Die Länge des Vorhangs ist perfekt.",
  },
  Teppich: {
    n: "Der Teppich im Wohnzimmer ist sehr weich.",
    a: "Sie kauft einen roten Teppich.",
    d: "Das Kind liegt auf dem Teppich und spielt.",
    g: "Die Farbe des Teppichs passt zum Sofa.",
  },
  Bett: {
    n: "Das Bett ist gemütlich.",
    a: "Ich mache das Bett.",
    d: "Sie schläft in dem Bett.",
    g: "Die Decke des Betts ist warm.",
  },
  Badezimmer: {
    n: "Das Badezimmer ist frisch renoviert.",
    a: "Ich putze das Badezimmer.",
    d: "Er ist in dem Badezimmer.",
    g: "Die Fliesen des Badezimmers sind hellblau.",
  },
  Waschmaschine: {
    n: "Die Waschmaschine läuft schon zwei Stunden.",
    a: "Sie stellt die Waschmaschine an.",
    d: "Mit der Waschmaschine wäscht er alles.",
    g: "Das Programm der Waschmaschine ist fertig.",
  },
  Herd: {
    n: "Der Herd ist noch heiß.",
    a: "Sie kauft einen neuen Herd.",
    d: "Am Herd kocht er jeden Abend.",
    g: "Die Platte des Herds ist schmutzig.",
  },
  Mikrowelle: {
    n: "Die Mikrowelle piept, wenn das Essen fertig ist.",
    a: "Er wärmt die Suppe in der Mikrowelle auf.",
    d: "Mit der Mikrowelle geht es sehr schnell.",
    g: "Die Türe der Mikrowelle ist durchsichtig.",
  },
  Spülmaschine: {
    n: "Die Spülmaschine ist noch nicht fertig.",
    a: "Sie räumt die Spülmaschine aus.",
    d: "In der Spülmaschine werden alle Teller sauber.",
    g: "Das Programm der Spülmaschine dauert eine Stunde.",
  },
  Heizung: {
    n: "Die Heizung wärmt den Raum.",
    a: "Er stellt die Heizung an.",
    d: "Er sitzt neben der Heizung.",
    g: "Das Rohr der Heizung ist heiß.",
  },
  Balkon: {
    n: "Der Balkon bietet eine tolle Aussicht.",
    a: "Sie bepflanzt den Balkon mit Blumen.",
    d: "Auf dem Balkon trinken wir Kaffee.",
    g: "Das Geländer des Balkons ist neu gestrichen.",
  },
  Garage: {
    n: "Die Garage ist für zwei Autos zu klein.",
    a: "Er fährt das Auto in die Garage.",
    d: "In der Garage repariert er sein Fahrrad.",
    g: "Die Tür der Garage öffnet automatisch.",
  },
  Klingel: {
    n: "Die Klingel funktioniert nicht mehr.",
    a: "Er drückt die Klingel zweimal.",
    d: "Sie hört die Klingel und öffnet die Tür.",
    g: "Das Geräusch der Klingel ist zu laut.",
  },
  Steckdose: {
    n: "Die Steckdose ist hinter dem Sofa versteckt.",
    a: "Er braucht eine Steckdose für den Laptop.",
    d: "An der Steckdose lädt er das Handy.",
    g: "Der Strom der Steckdose ist ausgefallen.",
  },
  Baum: {
    n: "Der Baum ist sehr alt.",
    a: "Ich pflanze den Baum.",
    d: "Er sitzt unter dem Baum.",
    g: "Die Rinde des Baumes ist rau.",
  },
  Strand: {
    n: "Der Strand ist sandig.",
    a: "Ich besuche den Strand.",
    d: "Wir liegen an dem Strand.",
    g: "Der Sand des Strandes ist weiß.",
  },
  Meer: {
    n: "Das Meer ist tief.",
    a: "Ich sehe das Meer.",
    d: "Er schwimmt in dem Meer.",
    g: "Die Wellen des Meeres sind groß.",
  },
  Insel: {
    n: "Die Insel liegt im Ozean.",
    a: "Wir besuchen die Insel.",
    d: "Er wohnt auf einer Insel.",
    g: "Das Ufer der Insel ist schön.",
  },
  Wüste: {
    n: "Die Wüste ist trocken.",
    a: "Er durchquert die Wüste.",
    d: "In der Wüste ist es heiß.",
    g: "Der Sand der Wüste glüht.",
  },
  Tal: {
    n: "Das Tal ist grün.",
    a: "Wir durchwandern das Tal.",
    d: "Das Dorf liegt in dem Tal.",
    g: "Der Boden des Tals ist fruchtbar.",
  },
  Feld: {
    n: "Das Feld ist weit.",
    a: "Der Bauer pflügt das Feld.",
    d: "Er arbeitet auf dem Feld.",
    g: "Die Ernte des Felds ist groß.",
  },
  Wiese: {
    n: "Die Wiese blüht.",
    a: "Ich sehe die Wiese.",
    d: "Die Kühe grasen auf der Wiese.",
    g: "Das Gras der Wiese ist hoch.",
  },
  Pflanze: {
    n: "Die Pflanze braucht Wasser.",
    a: "Ich gieße die Pflanze.",
    d: "Er spricht mit der Pflanze.",
    g: "Die Blätter der Pflanze sind grün.",
  },
  Rose: {
    n: "Die Rose duftet gut.",
    a: "Ich pflücke eine Rose.",
    d: "Sie freut sich über die Rose.",
    g: "Die Dornen der Rose sind spitz.",
  },
  Frühling: {
    n: "Der Frühling beginnt im März.",
    a: "Ich genieße den Frühling.",
    d: "Im Frühling blühen die Blumen.",
    g: "Der Beginn des Frühlings ist schön.",
  },
  Sommer: {
    n: "Der Sommer ist heiß.",
    a: "Ich liebe den Sommer.",
    d: "Im Sommer fahren wir ans Meer.",
    g: "Die Hitze des Sommers ist groß.",
  },
  Herbst: {
    n: "Der Herbst bringt Wind.",
    a: "Ich mag den Herbst.",
    d: "Im Herbst fallen die Blätter.",
    g: "Die Farben des Herbstes sind bunt.",
  },
  Winter: {
    n: "Der Winter ist kalt.",
    a: "Ich sehe den Winter kommen.",
    d: "Im Winter schneit es oft.",
    g: "Die Kälte des Winters ist streng.",
  },
  Supermarkt: {
    n: "Der Supermarkt ist groß.",
    a: "Ich besuche den Supermarkt.",
    d: "Ich kaufe in dem Supermarkt ein.",
    g: "Die Parkplätze des Supermarktes sind voll.",
  },
  Bäckerei: {
    n: "Die Bäckerei duftet nach Brot.",
    a: "Ich suche die Bäckerei.",
    d: "Ich kaufe bei der Bäckerei ein.",
    g: "Die Auswahl der Bäckerei ist groß.",
  },
  Rathaus: {
    n: "Das Rathaus steht am Marktplatz.",
    a: "Ich besuche das Rathaus.",
    d: "Er arbeitet im Rathaus.",
    g: "Der Turm des Rathauses ist hoch.",
  },
  Kirche: {
    n: "Die Kirche ist alt.",
    a: "Wir besichtigen die Kirche.",
    d: "Die Glocken läuten in der Kirche.",
    g: "Die Fenster der Kirche sind bunt.",
  },
  Moschee: {
    n: "Die Moschee ist wunderschön.",
    a: "Wir besuchen die Moschee.",
    d: "Die Gläubigen beten in der Moschee.",
    g: "Das Minarett der Moschee ist hoch.",
  },
  Museum: {
    n: "Das Museum zeigt Kunst.",
    a: "Ich besuche das Museum.",
    d: "Er arbeitet in dem Museum.",
    g: "Die Exponate des Museums sind wertvoll.",
  },
  Bibliothek: {
    n: "Die Bibliothek ist ruhig.",
    a: "Ich brauche die Bibliothek.",
    d: "Ich lerne in der Bibliothek.",
    g: "Die Bücher der Bibliothek sind alt.",
  },
  Polizei: {
    n: "Die Polizei hilft schnell.",
    a: "Ich rufe die Polizei.",
    d: "Er arbeitet bei der Polizei.",
    g: "Das Auto der Polizei parkt dort.",
  },
  Feuerwehr: {
    n: "Die Feuerwehr löscht den Brand.",
    a: "Er ruft die Feuerwehr.",
    d: "Er arbeitet bei der Feuerwehr.",
    g: "Die Sirene der Feuerwehr ist laut.",
  },
  Restaurant: {
    n: "Das Restaurant ist voll.",
    a: "Ich besuche das Restaurant.",
    d: "Er isst in dem Restaurant.",
    g: "Die Küche des Restaurants ist toll.",
  },
  Café: {
    n: "Das Café ist gemütlich.",
    a: "Ich besuche das Café.",
    d: "Wir sitzen in dem Café.",
    g: "Der Kuchen des Cafés ist lecker.",
  },
  Bank: {
    n: "Die Bank öffnet um neun Uhr.",
    a: "Ich suche eine Bank.",
    d: "Ich habe ein Konto bei der Bank.",
    g: "Die Zinsen der Bank sind niedrig.",
  },
  Post: {
    n: "Die Post bringt die Briefe.",
    a: "Ich bringe das Paket zur Post.",
    d: "Ich arbeite bei der Post.",
    g: "Der Schalter der Post ist besetzt.",
  },
  Markt: {
    n: "Der Markt findet heute statt.",
    a: "Ich besuche den Markt.",
    d: "Ich kaufe auf dem Markt ein.",
    g: "Die Stände des Marktes sind bunt.",
  },
  Kino: {
    n: "Das Kino zeigt einen neuen Film.",
    a: "Wir besuchen das Kino.",
    d: "Er arbeitet in dem Kino.",
    g: "Die Leinwand des Kinos ist groß.",
  },
  Theater: {
    n: "Das Theater ist prachtvoll.",
    a: "Wir besuchen das Theater.",
    d: "Sie spielt in dem Theater.",
    g: "Die Bühne des Theaters ist bereit.",
  },
  Büro: {
    n: "Das Büro ist heute sehr ruhig.",
    a: "Er verlässt das Büro um 18 Uhr.",
    d: "Im Büro trinkt sie viel Kaffee.",
    g: "Die Fenster des Büros bieten eine schöne Aussicht.",
  },
  Besprechung: {
    n: "Die Besprechung dauert länger als geplant.",
    a: "Er bereitet sich auf die Besprechung vor.",
    d: "In der Besprechung werden Entscheidungen getroffen.",
    g: "Das Ergebnis der Besprechung ist positiv.",
  },
  Kollege: {
    n: "Der Kollege hilft ihr beim Projekt.",
    a: "Sie trifft den Kollegen in der Pause.",
    d: "Mit dem Kollegen isst er oft zu Mittag.",
    g: "Das Büro des Kollegen ist nebenan.",
  },
  Chefin: {
    n: "Die Chefin leitet das Team.",
    a: "Ich frage die Chefin.",
    d: "Er antwortet der Chefin.",
    g: "Die Entscheidung der Chefin ist endgültig.",
  },
  Chef: {
    n: "Der Chef ist zufrieden.",
    a: "Ich sehe den Chef.",
    d: "Er arbeitet mit dem Chef.",
    g: "Das Auto des Chefs ist neu.",
  },
  Anwalt: {
    n: "Der Anwalt berät seinen Mandanten.",
    a: "Ich brauche einen Anwalt.",
    d: "Ich vertraue dem Anwalt.",
    g: "Die Kanzlei des Anwalts ist teuer.",
  },
  Zahnarzt: {
    n: "Der Zahnarzt kontrolliert die Zähne.",
    a: "Ich besuche den Zahnarzt.",
    d: "Ich habe einen Termin beim Zahnarzt.",
    g: "Die Praxis des Zahnarztes ist sauber.",
  },
  Tierarzt: {
    n: "Der Tierarzt hilft dem Hund.",
    a: "Ich rufe den Tierarzt.",
    d: "Ich bin mit der Katze beim Tierarzt.",
    g: "Die Diagnose des Tierarztes war richtig.",
  },
  Hobby: {
    n: "Das Hobby macht Spaß.",
    a: "Ich habe ein neues Hobby.",
    d: "Er widmet sich seinem Hobby.",
    g: "Die Kosten des Hobbys sind gering.",
  },
  Spiel: {
    n: "Das Spiel ist spannend.",
    a: "Ich gewinne das Spiel.",
    d: "Die Kinder freuen sich bei dem Spiel.",
    g: "Die Regeln des Spiels sind klar.",
  },
  Konzert: {
    n: "Das Konzert beginnt um acht Uhr.",
    a: "Er kauft das Ticket für das Konzert.",
    d: "Im Konzert singt das Publikum mit.",
    g: "Die Stimmung des Konzerts war toll.",
  },
  Ausstellung: {
    n: "Die Ausstellung ist noch bis nächste Woche offen.",
    a: "Sie besucht die Ausstellung mit Freunden.",
    d: "In der Ausstellung sieht man viele moderne Bilder.",
    g: "Die Thema der Ausstellung ist die Natur.",
  },
  Schwimmen: {
    n: "Das Schwimmen hält fit.",
    a: "Ich liebe das Schwimmen.",
    d: "Er ist gut im Schwimmen.",
    g: "Der Stil des Schwimmens ist wichtig.",
  },
  Laufen: {
    n: "Das Laufen macht den Kopf frei.",
    a: "Ich trainiere das Laufen.",
    d: "Er hat Spaß beim Laufen.",
    g: "Das Tempo des Laufens ist hoch.",
  },
  Tanzen: {
    n: "Das Tanzen ist seine Leidenschaft.",
    a: "Ich lerne das Tanzen.",
    d: "Sie ist Profi beim Tanzen.",
    g: "Der Rhythmus des Tanzens ist schnell.",
  },
  Lesen: {
    n: "Das Lesen bildet.",
    a: "Ich liebe das Lesen.",
    d: "Er entspannt sich beim Lesen.",
    g: "Die Freude des Lesens ist groß.",
  },
  Kochen: {
    n: "Das Kochen ist sein Hobby.",
    a: "Ich lerne das Kochen.",
    d: "Er hat Spaß am Kochen.",
    g: "Die Kunst des Kochens ist kreativ.",
  },
  Prüfung: {
    n: "Die Prüfung ist schwer.",
    a: "Ich lerne für die Prüfung.",
    d: "Er bereitet sich auf die Prüfung vor.",
    g: "Das Ergebnis der Prüfung kommt morgen.",
  },
  Note: {
    n: "Die Note ist sehr gut.",
    a: "Er bekommt eine Note.",
    d: "Er ist zufrieden mit der Note.",
    g: "Die Bedeutung der Note ist groß.",
  },
  Unterricht: {
    n: "Der Unterricht beginnt um acht Uhr.",
    a: "Sie verpasst den Unterricht wegen Krankheit.",
    d: "Im Unterricht lernt er neue Grammatik.",
    g: "Das Ende des Unterrichts ist um zwei Uhr.",
  },
  Hausaufgabe: {
    n: "Die Hausaufgabe ist für morgen fällig.",
    a: "Er macht die Hausaufgabe nach dem Essen.",
    d: "Bei der Hausaufgabe hilft ihm die Mutter.",
    g: "Die Schwierigkeit der Hausaufgabe ist okay.",
  },
  Bleistift: {
    n: "Der Bleistift liegt auf dem Tisch.",
    a: "Ich spitze den Bleistift.",
    d: "Er schreibt mit dem Bleistift.",
    g: "Die Mine des Bleistiftes ist gebrochen.",
  },
  Lineal: {
    n: "Das Lineal ist aus Plastik.",
    a: "Ich benutze das Lineal.",
    d: "Ich messe mit dem Lineal.",
    g: "Die Länge des Lineals ist 30 cm.",
  },
  Rucksack: {
    n: "Der Rucksack ist blau.",
    a: "Ich trage den Rucksack.",
    d: "In dem Rucksack sind Bücher.",
    g: "Die Träger des Rucksackes sind stabil.",
  },
  Klasse: {
    n: "Die Klasse ist heute laut.",
    a: "Ich kenne die Klasse.",
    d: "Er unterrichtet in der Klasse.",
    g: "Die Schüler der Klasse sind fleißig.",
  },
  Sprache: {
    n: "Die Sprache ist wichtig für die Kommunikation.",
    a: "Ich lerne eine Sprache.",
    d: "In der Sprache gibt es viele Regeln.",
    g: "Die Schönheit der Sprache ist bekannt.",
  },
  Wörterbuch: {
    n: "Das Wörterbuch hilft beim Übersetzen.",
    a: "Ich benutze das Wörterbuch.",
    d: "Ich suche in dem Wörterbuch.",
    g: "Die Qualität des Wörterbuchs ist gut.",
  },
  Bus: {
    n: "Der Bus kommt pünktlich.",
    a: "Ich nehme den Bus.",
    d: "Er fährt mit dem Bus.",
    g: "Die Route des Busses ist lang.",
  },
  Taxi: {
    n: "Das Taxi kommt in fünf Minuten.",
    a: "Ich rufe das Taxi per App.",
    d: "Mit dem Taxi fahren wir zum Flughafen.",
    g: "Der Fahrer des Taxis kennt die Stadt gut.",
  },
  Zug: {
    n: "Der Zug fährt schnell.",
    a: "Ich nehme den Zug.",
    d: "Er reist mit dem Zug.",
    g: "Der Fahrplan des Zuges ist genau.",
  },
  "U-Bahn": {
    n: "Die U-Bahn fährt alle fünf Minuten.",
    a: "Ich nehme die U-Bahn zur Arbeit.",
    d: "In der U-Bahn gibt es viele Menschen.",
    g: "Die Linie der U-Bahn fährt durch die Stadt.",
  },
  Hafen: {
    n: "Der Hafen ist voller großer Schiffe.",
    a: "Das Boot fährt in den Hafen ein.",
    d: "Im Hafen werden Waren geladen.",
    g: "Die Einfahrt des Hafens ist markiert.",
  },
  Schiff: {
    n: "Das Schiff fährt langsam in den Hafen.",
    a: "Wir besteigen das Schiff am Morgen.",
    d: "Mit dem Schiff reist man gemütlich.",
    g: "Der Kapitän des Schiffes steht vorne.",
  },
  Motorrad: {
    n: "Das Motorrad ist schnell.",
    a: "Er fährt ein Motorrad.",
    d: "Er kommt mit dem Motorrad.",
    g: "Der Motor des Motorrads ist laut.",
  },
  Ampel: {
    n: "Die Ampel zeigt Rot.",
    a: "Ich warte an der Ampel.",
    d: "Er steht vor der Ampel und wartet.",
    g: "Das Licht der Ampel wechselt auf Grün.",
  },
  Führerschein: {
    n: "Der Führerschein liegt im Auto.",
    a: "Ich mache meinen Führerschein.",
    d: "Er zeigt dem Polizisten seinen Führerschein.",
    g: "Die Gültigkeit des Führerscheines ist abgelaufen.",
  },
  Stau: {
    n: "Der Stau ist fünf Kilometer lang.",
    a: "Ich hasse den Stau.",
    d: "Wir stehen im Stau.",
    g: "Die Ursache des Staues ist eine Baustelle.",
  },
  Fernseher: {
    n: "Der Fernseher ist neu.",
    a: "Ich schalte den Fernseher an.",
    d: "Er schaut auf dem Fernseher einen Film.",
    g: "Das Bild des Fernseheres ist scharf.",
  },
  Radio: {
    n: "Das Radio spielt Musik.",
    a: "Ich höre Radio.",
    d: "Er hört die Nachrichten im Radio.",
    g: "Die Lautstärke des Radios ist hoch.",
  },
  Internet: {
    n: "Das Internet ist heute langsam.",
    a: "Ich nutze das Internet.",
    d: "Er surft im Internet.",
    g: "Die Geschwindigkeit des Internets ist wichtig.",
  },
  App: {
    n: "Die App ist sehr nützlich.",
    a: "Ich installiere die App.",
    d: "Er arbeitet mit der App.",
    g: "Das Design der App ist modern.",
  },
  Drucker: {
    n: "Der Drucker druckt das Dokument.",
    a: "Ich brauche den Drucker.",
    d: "Er arbeitet mit dem Drucker.",
    g: "Die Tinte des Druckeres ist leer.",
  },
  Tastatur: {
    n: "Die Tastatur ist kabellos.",
    a: "Ich benutze die Tastatur.",
    d: "Er schreibt auf der Tastatur.",
    g: "Die Tasten der Tastatur sind sauber.",
  },
  Bildschirm: {
    n: "Der Bildschirm ist groß.",
    a: "Ich putze den Bildschirm.",
    d: "Ich schaue auf den Bildschirm.",
    g: "Die Auflösung des Bildschirmes ist hoch.",
  },
  Kopfhörer: {
    n: "Der Kopfhörer dämpft den Lärm.",
    a: "Ich trage den Kopfhörer.",
    d: "Ich höre Musik mit dem Kopfhörer.",
    g: "Der Klang des Kopfhöreres ist gut.",
  },
  Ladekabel: {
    n: "Das Ladekabel ist zu kurz.",
    a: "Ich suche das Ladekabel.",
    d: "Er lädt das Handy mit dem Ladekabel.",
    g: "Der Stecker des Ladekabels ist verbogen.",
  },
  Passwort: {
    n: "Das Passwort ist sicher.",
    a: "Ich ändere das Passwort.",
    d: "Ich schütze mich mit dem Passwort.",
    g: "Die Länge des Passworts ist ausreichend.",
  },
  Zeitung: {
    n: "Die Zeitung liegt vor der Tür.",
    a: "Ich lese die Zeitung.",
    d: "In der Zeitung steht ein Bericht.",
    g: "Die Schlagzeile der Zeitung ist groß.",
  },
  Formular: {
    n: "Das Formular muss ausgefüllt werden.",
    a: "Ich unterschreibe das Formular.",
    d: "Er hilft mir bei dem Formular.",
    g: "Der Zweck des Formulars ist klar.",
  },
  Wartezimmer: {
    n: "Das Wartezimmer beim Arzt ist voll.",
    a: "Ich betrete das Wartezimmer.",
    d: "Wir sitzen in dem Wartezimmer.",
    g: "Die Stühle des Wartezimmers sind unbequem.",
  },
  Einkauf: {
    n: "Der Einkauf war teuer.",
    a: "Ich erledige den Einkauf.",
    d: "Nach dem Einkauf gehe ich nach Hause.",
    g: "Die Taschen des Einkaufes sind schwer.",
  },
  Quittung: {
    n: "Die Quittung dient als Beleg.",
    a: "Ich nehme die Quittung.",
    d: "Auf der Quittung steht der Preis.",
    g: "Das Datum der Quittung ist von heute.",
  },
  Karte: {
    n: "Die Karte zeigt den Weg.",
    a: "Ich lese die Karte.",
    d: "Er orientiert sich auf der Karte.",
    g: "Der Maßstab der Karte ist groß.",
  },
  Kalender: {
    n: "Der Kalender hängt an der Wand.",
    a: "Ich schaue in den Kalender.",
    d: "Er sucht einen Termin im Kalender.",
    g: "Die Einträge des Kalenderes sind zahlreich.",
  },
  Adresse: {
    n: "Die Adresse ist korrekt.",
    a: "Ich schreibe die Adresse auf.",
    d: "Er wohnt an dieser Adresse.",
    g: "Die Hausnummer der Adresse fehlt.",
  },
  Nachricht: {
    n: "Die Nachricht ist wichtig.",
    a: "Ich erhalte eine Nachricht.",
    d: "Er antwortet auf die Nachricht.",
    g: "Der Inhalt der Nachricht ist privat.",
  },
  Anruf: {
    n: "Der Anruf kommt zur richtigen Zeit.",
    a: "Ich erwarte einen Anruf.",
    d: "Er freut sich über den Anruf.",
    g: "Die Dauer des Anrufes war kurz.",
  },
  Magen: {
    n: "Der Magen knurrt vor Hunger.",
    a: "Er hält sich den Magen vor Schmerzen.",
    d: "Mit vollem Magen schläft man schlecht.",
    g: "Die Beschwerden des Magens gehen nicht weg.",
  },
  Hals: {
    n: "Der Hals tut weh beim Schlucken.",
    a: "Der Arzt untersucht den Hals.",
    d: "Am Hals trägt sie eine Kette.",
    g: "Die Schmerzen des Halses werden schlimmer.",
  },
  Haut: {
    n: "Die Haut ist trocken im Winter.",
    a: "Sie pflegt die Haut mit Creme.",
    d: "An der Haut sieht man die Sonne.",
    g: "Die Farbe der Haut verändert sich im Sommer.",
  },
  Knochen: {
    n: "Der Knochen ist bei dem Sturz gebrochen.",
    a: "Das Röntgenbild zeigt den Knochen.",
    d: "Am Knochen ist der Schmerz sehr stark.",
    g: "Die Festigkeit des Knochens nimmt mit dem Alter ab.",
  },
  Muskel: {
    n: "Der Muskel ist verspannt.",
    a: "Er trainiert den Muskel.",
    d: "Er hat Schmerzen in dem Muskel.",
    g: "Die Kraft des Muskeles ist groß.",
  },
  Wunde: {
    n: "Die Wunde muss sauber verbunden werden.",
    a: "Er reinigt die Wunde mit Desinfektionsmittel.",
    d: "An der Wunde klebt ein Pflaster.",
    g: "Die Tiefe der Wunde ist nicht gefährlich.",
  },
  Pflaster: {
    n: "Das Pflaster klebt gut auf der Haut.",
    a: "Sie klebt ein Pflaster auf den Finger.",
    d: "Mit dem Pflaster hört die Blutung auf.",
    g: "Die Seite des Pflasters ist klebrig.",
  },
  Gemüse: {
    n: "Das Gemüse vom Markt ist immer frisch.",
    a: "Sie kauft das Gemüse beim Bauern.",
    d: "Mit Gemüse kocht man sehr gesund.",
    g: "Der Geschmack des Gemüses ist natürlich.",
  },
  Karotte: {
    n: "Die Karotte ist gut für die Augen.",
    a: "Das Kind isst die Karotte als Snack.",
    d: "Mit der Karotte bereitet er die Suppe zu.",
    g: "Die Farbe der Karotte ist leuchtend orange.",
  },
  Marmelade: {
    n: "Die Marmelade ist selbstgemacht.",
    a: "Er streicht die Marmelade aufs Brot.",
    d: "Mit der Marmelade schmeckt das Frühstück besser.",
    g: "Der Geschmack der Marmelade ist süß.",
  },
  Teller: {
    n: "Der Teller steht auf dem Tisch.",
    a: "Ich wasche den Teller.",
    d: "Das Essen liegt auf dem Teller.",
    g: "Der Rand des Telleres ist blau.",
  },
  Gabel: {
    n: "Die Gabel liegt neben dem Messer.",
    a: "Ich benutze die Gabel.",
    d: "Ich esse mit der Gabel.",
    g: "Die Zinken der Gabel sind spitz.",
  },
  Waschbecken: {
    n: "Das Waschbecken ist aus Keramik.",
    a: "Ich putze das Waschbecken.",
    d: "Er wäscht sich am Waschbecken.",
    g: "Der Abfluss des Waschbeckens ist verstopft.",
  },
  Toilette: {
    n: "Die Toilette ist gerade besetzt.",
    a: "Er putzt die Toilette jeden Samstag.",
    d: "Auf der Toilette liest er gerne.",
    g: "Die Spülung der Toilette ist kaputt.",
  },
  Decke: {
    n: "Die Decke ist weiß gestrichen.",
    a: "Ich brauche eine Decke.",
    d: "Er liegt unter der Decke.",
    g: "Die Höhe der Decke ist drei Meter.",
  },
  Dschungel: {
    n: "Der Dschungel ist dicht bewachsen.",
    a: "Wir erkunden den Dschungel.",
    d: "Es ist heiß im Dschungel.",
    g: "Die Pflanzen des Dschungeles sind exotisch.",
  },
  Vulkan: {
    n: "Der Vulkan ist aktiv.",
    a: "Wir sehen den Vulkan.",
    d: "In dem Vulkan glüht Lava.",
    g: "Der Ausbruch des Vulkanes ist gefährlich.",
  },
  Erde: {
    n: "Die Erde dreht sich um die Sonne.",
    a: "Wir schützen die Erde.",
    d: "Auf der Erde leben viele Menschen.",
    g: "Die Oberfläche der Erde besteht meist aus Wasser.",
  },
  Luft: {
    n: "Die Luft ist heute sehr klar.",
    a: "Ich atme die Luft ein.",
    d: "Er fliegt in der Luft.",
    g: "Die Qualität der Luft ist gut.",
  },
  Feuer: {
    n: "Das Feuer brennt im Kamin.",
    a: "Er löscht das Feuer.",
    d: "Wir wärmen uns am Feuer.",
    g: "Die Hitze des Feuers ist groß.",
  },
  Stein: {
    n: "Der Stein ist hart.",
    a: "Ich werfe den Stein.",
    d: "Er stolpert über einen Stein.",
    g: "Das Gewicht des Steines ist hoch.",
  },
  Sand: {
    n: "Der Sand ist heiß.",
    a: "Ich siebe den Sand.",
    d: "Die Kinder spielen im Sand.",
    g: "Die Farbe des Sandes ist hell.",
  },
  Umwelt: {
    n: "Die Umwelt ist schützenswert.",
    a: "Wir belasten die Umwelt.",
    d: "Er engagiert sich für die Umwelt.",
    g: "Der Zustand der Umwelt ist kritisch.",
  },
  Bürgersteig: {
    n: "Der Bürgersteig ist nach dem Regen rutschig.",
    a: "Das Kind läuft auf den Bürgersteig.",
    d: "Sie geht auf dem Bürgersteig spazieren.",
    g: "Die Breite des Bürgersteigs ist zu schmal.",
  },
  Kollegin: {
    n: "Die Kollegin ist sehr nett.",
    a: "Ich frage die Kollegin.",
    d: "Er arbeitet mit der Kollegin.",
    g: "Der Humor der Kollegin ist toll.",
  },
  Aufgabe: {
    n: "Die Aufgabe ist schwierig.",
    a: "Ich löse die Aufgabe.",
    d: "Er scheitert an der Aufgabe.",
    g: "Die Lösung der Aufgabe ist richtig.",
  },
  Projekt: {
    n: "Das Projekt läuft sehr gut.",
    a: "Sie leitet das Projekt seit drei Monaten.",
    d: "Am Projekt arbeiten fünf Personen.",
    g: "Das Ziel des Projekts ist klar definiert.",
  },
  Karriere: {
    n: "Die Karriere entwickelt sich sehr gut.",
    a: "Er plant seine Karriere sorgfältig.",
    d: "In seiner Karriere hat er viel erreicht.",
    g: "Das Ende der Karriere kommt irgendwann.",
  },
  Ausbildung: {
    n: "Die Ausbildung dauert drei Jahre.",
    a: "Sie beginnt die Ausbildung im Herbst.",
    d: "Nach der Ausbildung findet er schnell Arbeit.",
    g: "Die Qualität der Ausbildung ist sehr gut.",
  },
  Praktikum: {
    n: "Das Praktikum beginnt nächste Woche.",
    a: "Er macht das Praktikum bei einer großen Firma.",
    d: "Im Praktikum lernt man viel Praktisches.",
    g: "Das Ende des Praktikums ist schon nah.",
  },
  Kündigung: {
    n: "Die Kündigung kam völlig überraschend.",
    a: "Er erhält die Kündigung per Brief.",
    d: "Nach der Kündigung sucht er sofort einen neuen Job.",
    g: "Der Grund der Kündigung war unklar.",
  },
  Foto: {
    n: "Das Foto erinnert mich an den Urlaub.",
    a: "Ich mache ein Foto.",
    d: "Auf dem Foto sehe ich glücklich aus.",
    g: "Die Schärfe des Fotos ist perfekt.",
  },
  Picknick: {
    n: "Das Picknick im Park war wunderschön.",
    a: "Sie planen das Picknick für Sonntag.",
    d: "Beim Picknick essen sie Brot und Käse.",
    g: "Der Ort des Picknicks ist ein schöner Park.",
  },
  Party: {
    n: "Die Party ist laut.",
    a: "Ich besuche die Party.",
    d: "Er tanzt auf der Party.",
    g: "Die Musik der Party ist super.",
  },
  Geburtstag: {
    n: "Der Geburtstag ist morgen.",
    a: "Ich feiere den Geburtstag.",
    d: "Er gratuliert zum Geburtstag.",
    g: "Die Party des Geburtstags war toll.",
  },
  Ferien: {
    n: "Die Ferien fangen bald an.",
    a: "Ich liebe die Ferien.",
    d: "In den Ferien reisen wir.",
    g: "Die Planung der Ferien macht Spaß.",
  },
  Pause: {
    n: "Die Pause dauert zwanzig Minuten.",
    a: "Er nutzt die Pause zum Essen.",
    d: "In der Pause spielen die Kinder draußen.",
    g: "Das Ende der Pause wird durch eine Glocke angezeigt.",
  },
  Zeugnis: {
    n: "Das Zeugnis kommt am letzten Schultag.",
    a: "Sie zeigt das Zeugnis den Eltern.",
    d: "Mit dem Zeugnis bewirbt er sich um einen Praktikumsplatz.",
    g: "Die Noten des Zeugnisses sind sehr gut.",
  },
  Heft: {
    n: "Das Heft ist vollgeschrieben.",
    a: "Ich kaufe ein Heft.",
    d: "In dem Heft stehen Notizen.",
    g: "Der Umschlag des Hefts ist blau.",
  },
  Ticket: {
    n: "Das Ticket ist schon ausverkauft.",
    a: "Ich kaufe das Ticket online.",
    d: "Mit dem Ticket kommt man überall hin.",
    g: "Der Preis des Tickets ist gestiegen.",
  },
  Haltestelle: {
    n: "Die Haltestelle ist direkt vor dem Haus.",
    a: "Ich gehe zur Haltestelle.",
    d: "Er wartet an der Haltestelle auf den Bus.",
    g: "Der Name der Haltestelle ist Marktplatz.",
  },
  Landkarte: {
    n: "Die Landkarte zeigt alle Straßen.",
    a: "Er kauft sich eine neue Landkarte.",
    d: "Mit der Landkarte findet er sich zurecht.",
    g: "Die Genauigkeit der Landkarte ist wichtig.",
  },
  Kreuzung: {
    n: "Die Kreuzung ist sehr gefährlich.",
    a: "Er überquert die Kreuzung vorsichtig.",
    d: "An der Kreuzung biege ich rechts ab.",
    g: "Die Mitte der Kreuzung ist markiert.",
  },
  Autobahn: {
    n: "Die Autobahn ist heute gesperrt.",
    a: "Wir fahren die Autobahn entlang.",
    d: "Auf der Autobahn darf man schnell fahren.",
    g: "Die Ausfahrt der Autobahn ist nah.",
  },
  Tankstelle: {
    n: "Die Tankstelle ist die ganze Nacht geöffnet.",
    a: "Ich fahre zur Tankstelle.",
    d: "Er kauft an der Tankstelle Kaffee.",
    g: "Der Preis der Tankstelle ist hoch.",
  },
  Parkplatz: {
    n: "Der Parkplatz vor dem Supermarkt ist leider voll.",
    a: "Ich suche einen Parkplatz in der Nähe.",
    d: "Er wartet auf dem Parkplatz auf seine Frau.",
    g: "Die Einfahrt des Parkplatzes ist sehr eng.",
  },
  Akku: {
    n: "Der Akku ist fast leer.",
    a: "Ich lade den Akku auf.",
    d: "Es liegt am Akku.",
    g: "Die Kapazität des Akkues ist gesunken.",
  },
  Netzwerk: {
    n: "Das Netzwerk ist stabil.",
    a: "Ich richte das Netzwerk ein.",
    d: "Er arbeitet in dem Netzwerk.",
    g: "Die Sicherheit des Netzwerks ist wichtig.",
  },
  Datei: {
    n: "Die Datei wurde gespeichert.",
    a: "Ich lösche die Datei.",
    d: "Er arbeitet mit der Datei.",
    g: "Der Name der Datei ist zu lang.",
  },
  Software: {
    n: "Die Software muss aktualisiert werden.",
    a: "Ich installiere die Software.",
    d: "Mit dieser Software geht es schneller.",
    g: "Die Lizenz der Software ist abgelaufen.",
  },
};
