export const quizMainData = [
  {
    q: "Haus",
    a: "das",
    emoji: "🏠",
    en: "House",
    l: "A1",
    c: "Zuhause",
    img: require("./images/haus.png"),
  },
  {
    q: "Sonne",
    a: "die",
    emoji: "☀️",
    en: "Sun",
    l: "A1",
    c: "Natur",
    img: require("./images/sonne.png"),
  },
  {
    q: "Katze",
    a: "die",
    emoji: "🐱",
    en: "Cat",
    l: "A1",
    c: "Tiere",
    img: require("./images/katze.png"),
  },
  {
    q: "Vogel",
    a: "der",
    emoji: "🐦",
    en: "Bird",
    l: "A1",
    c: "Tiere",
    img: require("./images/vogel.png"),
  },
  {
    q: "Auto",
    a: "das",
    emoji: "🚗",
    en: "Car",
    l: "A1",
    c: "Transport",
    img: require("./images/auto.png"),
  },
  {
    q: "Tisch",
    a: "der",
    emoji: "🪑",
    en: "Table",
    l: "A1",
    c: "Zuhause",
    img: require("./images/tisch.png"),
  },
  {
    q: "Apfel",
    a: "der",
    emoji: "🍎",
    en: "Apple",
    l: "A1",
    c: "Essen",
    img: require("./images/apfel.png"),
  },
  {
    q: "Buch",
    a: "das",
    emoji: "📚",
    en: "Book",
    l: "A1",
    c: "Schule",
    img: require("./images/buch.png"),
  },
  {
    q: "Computer",
    a: "der",
    emoji: "💻",
    en: "Computer",
    l: "A1",
    c: "Technik",
    img: require("./images/computer.png"),
  },
  {
    q: "Stadt",
    a: "die",
    emoji: "🏙️",
    en: "City",
    l: "A1",
    c: "Orte",
    img: require("./images/stadt.png"),
  },
  {
    q: "Hund",
    a: "der",
    emoji: "🐶",
    en: "Dog",
    l: "A1",
    c: "Tiere",
    img: require("./images/hund.png"),
  },
  {
    q: "Blume",
    a: "die",
    emoji: "🌸",
    en: "Flower",
    l: "A1",
    c: "Natur",
    img: require("./images/blume.png"),
  },
  {
    q: "Telefon",
    a: "das",
    emoji: "📞",
    en: "Telephone",
    l: "A1",
    c: "Technik",
    img: require("./images/telefon.png"),
  },
  {
    q: "Wasser",
    a: "das",
    emoji: "💧",
    en: "Water",
    l: "A1",
    c: "Essen",
    img: require("./images/wasser.png"),
  },
  {
    q: "Kaffee",
    a: "der",
    emoji: "☕",
    en: "Coffee",
    l: "A1",
    c: "Essen",
    img: require("./images/kaffee.png"),
  },
  {
    q: "Fenster",
    a: "das",
    emoji: "🪟",
    en: "Window",
    l: "A1",
    c: "Zuhause",
    img: require("./images/fenster.png"),
  },
  {
    q: "Schule",
    a: "die",
    emoji: "🏫",
    en: "School",
    l: "A1",
    c: "Schule",
    img: require("./images/schule.png"),
  },
  {
    q: "Lampe",
    a: "die",
    emoji: "💡",
    en: "Lamp",
    l: "A1",
    c: "Zuhause",
    img: require("./images/lampe.png"),
  },
  {
    q: "Brot",
    a: "das",
    emoji: "🍞",
    en: "Bread",
    l: "A1",
    c: "Essen",
    img: require("./images/brot.png"),
  },
  {
    q: "Garten",
    a: "der",
    emoji: "🌻",
    en: "Garden",
    l: "A1",
    c: "Natur",
    img: require("./images/garten.png"),
  },
  {
    q: "Wald",
    a: "der",
    emoji: "🌲",
    en: "Forest",
    l: "A1",
    c: "Natur",
    img: require("./images/wald.png"),
  },
  {
    q: "Himmel",
    a: "der",
    emoji: "🌤️",
    en: "Sky",
    l: "A1",
    c: "Natur",
    img: require("./images/himmel.png"),
  },
  {
    q: "Maus",
    a: "die",
    emoji: "🐭",
    en: "Mouse",
    l: "A1",
    c: "Tiere",
    img: require("./images/maus.png"),
  },
  {
    q: "Gesicht",
    a: "das",
    emoji: "😊",
    en: "Face",
    l: "A1",
    c: "Körper",
    img: require("./images/gesicht.png"),
  },
  {
    q: "Brücke",
    a: "die",
    emoji: "🌉",
    en: "Bridge",
    l: "A2",
    c: "Orte",
    img: require("./images/bruecke.png"),
  },
  {
    q: "Geld",
    a: "das",
    emoji: "💰",
    en: "Money",
    l: "A1",
    c: "Alltag",
    img: require("./images/geld.png"),
  },
  {
    q: "Auge",
    a: "das",
    emoji: "👁️",
    en: "Eye",
    l: "A1",
    c: "Körper",
    img: require("./images/auge.png"),
  },
  {
    q: "Hand",
    a: "die",
    emoji: "✋",
    en: "Hand",
    l: "A1",
    c: "Körper",
    img: require("./images/hand.png"),
  },
  {
    q: "Stuhl",
    a: "der",
    emoji: "🪑",
    en: "Chair",
    l: "A1",
    c: "Zuhause",
    img: require("./images/stuhl.png"),
  },
  {
    q: "Kühlschrank",
    a: "der",
    emoji: "🧊",
    en: "Refrigerator",
    l: "A2",
    c: "Zuhause",
    img: require("./images/kuehlschrank.png"),
  },
  {
    q: "Uhr",
    a: "die",
    emoji: "⏰",
    en: "Clock",
    l: "A1",
    c: "Alltag",
    img: require("./images/uhr.png"),
  },
  {
    q: "Fisch",
    a: "der",
    emoji: "🐟",
    en: "Fish",
    l: "A1",
    c: "Tiere",
    img: require("./images/fisch.png"),
  },
  {
    q: "Flugzeug",
    a: "das",
    emoji: "✈️",
    en: "Airplane",
    l: "A1",
    c: "Transport",
    img: require("./images/flugzeug.png"),
  },
  {
    q: "Geschenk",
    a: "das",
    emoji: "🎁",
    en: "Gift",
    l: "A1",
    c: "Alltag",
    img: require("./images/geschenk.png"),
  },
  {
    q: "Laptop",
    a: "der",
    emoji: "💻",
    en: "Laptop",
    l: "A2",
    c: "Technik",
    img: require("./images/laptop.png"),
  },
  {
    q: "Straße",
    a: "die",
    emoji: "🛣️",
    en: "Street",
    l: "A1",
    c: "Orte",
    img: require("./images/strasse.png"),
  },
  {
    q: "Zimmer",
    a: "das",
    emoji: "🚪",
    en: "Room",
    l: "A1",
    c: "Zuhause",
    img: require("./images/zimmer.png"),
  },
  {
    q: "Kleid",
    a: "das",
    emoji: "👗",
    en: "Dress",
    l: "A1",
    c: "Kleidung",
    img: require("./images/kleid.png"),
  },
  {
    q: "Hose",
    a: "die",
    emoji: "👖",
    en: "Pants",
    l: "A1",
    c: "Kleidung",
    img: require("./images/hose.png"),
  },
  {
    q: "Spielzeug",
    a: "das",
    emoji: "🧸",
    en: "Toy",
    l: "A1",
    c: "Alltag",
    img: require("./images/spielzeug.png"),
  },
  {
    q: "Berg",
    a: "der",
    emoji: "⛰️",
    en: "Mountain",
    l: "A1",
    c: "Natur",
    img: require("./images/berg.png"),
  },
  {
    q: "See",
    a: "der",
    emoji: "💧",
    en: "Lake",
    l: "A2",
    c: "Natur",
    img: require("./images/see.png"),
  },
  {
    q: "Mond",
    a: "der",
    emoji: "🌙",
    en: "Moon",
    l: "A1",
    c: "Natur",
    img: require("./images/mond.png"),
  },
  {
    q: "Tür",
    a: "die",
    emoji: "🚪",
    en: "Door",
    l: "A1",
    c: "Zuhause",
    img: require("./images/tuer.png"),
  },
  {
    q: "Zahn",
    a: "der",
    emoji: "🦷",
    en: "Tooth",
    l: "A1",
    c: "Körper",
    img: require("./images/zahn.png"),
  },
  {
    q: "Wolke",
    a: "die",
    emoji: "☁️",
    en: "Cloud",
    l: "A1",
    c: "Natur",
    img: require("./images/wolke.png"),
  },
  {
    q: "Boden",
    a: "der",
    emoji: "🏠",
    en: "Floor",
    l: "A1",
    c: "Zuhause",
    img: require("./images/boden.png"),
  },
  {
    q: "Nase",
    a: "die",
    emoji: "👃",
    en: "Nose",
    l: "A1",
    c: "Körper",
    img: require("./images/nase.png"),
  },
  {
    q: "Mütze",
    a: "die",
    emoji: "🧢",
    en: "Hat",
    l: "A1",
    c: "Kleidung",
    img: require("./images/muetze.png"),
  },
  {
    q: "Zunge",
    a: "die",
    emoji: "👅",
    en: "Tongue",
    l: "A2",
    c: "Körper",
    img: require("./images/zunge.png"),
  },
  {
    q: "Kamera",
    a: "die",
    emoji: "📷",
    en: "Camera",
    l: "A2",
    c: "Technik",
    img: require("./images/kamera.png"),
  },
  {
    q: "Gitarre",
    a: "die",
    emoji: "🎸",
    en: "Guitar",
    l: "A2",
    c: "Musik",
    img: require("./images/gitarre.png"),
  },
  {
    q: "Musik",
    a: "die",
    emoji: "🎵",
    en: "Music",
    l: "A1",
    c: "Musik",
    img: require("./images/musik.png"),
  },
  {
    q: "Blatt",
    a: "das",
    emoji: "🍃",
    en: "Leaf",
    l: "A1",
    c: "Natur",
    img: require("./images/blatt.png"),
  },
  {
    q: "Sofa",
    a: "das",
    emoji: "🛋️",
    en: "Sofa",
    l: "A1",
    c: "Zuhause",
    img: require("./images/sofa.png"),
  },
  {
    q: "Glas",
    a: "das",
    emoji: "🥛",
    en: "Glass",
    l: "A1",
    c: "Essen",
    img: require("./images/glas.png"),
  },
  {
    q: "Zoo",
    a: "der",
    emoji: "🦁",
    en: "Zoo",
    l: "A1",
    c: "Orte",
    img: require("./images/zoo.png"),
  },
  {
    q: "Familie",
    a: "die",
    emoji: "👨‍👩‍👧",
    en: "Family",
    l: "A1",
    c: "Menschen",
    img: require("./images/familie.png"),
  },
  {
    q: "Tasche",
    a: "die",
    emoji: "👜",
    en: "Bag",
    l: "A1",
    c: "Alltag",
    img: require("./images/tasche.png"),
  },
  {
    q: "Dach",
    a: "das",
    emoji: "🏠",
    en: "Roof",
    l: "A2",
    c: "Zuhause",
    img: require("./images/dach.png"),
  },
  {
    q: "Hemd",
    a: "das",
    emoji: "👔",
    en: "Shirt",
    l: "A1",
    c: "Kleidung",
    img: require("./images/hemd.png"),
  },
  {
    q: "Park",
    a: "der",
    emoji: "🌳",
    en: "Park",
    l: "A1",
    c: "Orte",
    img: require("./images/park.png"),
  },
  {
    q: "Bahn",
    a: "die",
    emoji: "🚂",
    en: "Train",
    l: "A1",
    c: "Transport",
    img: require("./images/bahn.png"),
  },
  {
    q: "Brille",
    a: "die",
    emoji: "👓",
    en: "Glasses",
    l: "A1",
    c: "Alltag",
    img: require("./images/brille.png"),
  },
  {
    q: "Schnee",
    a: "der",
    emoji: "❄️",
    en: "Snow",
    l: "A1",
    c: "Natur",
    img: require("./images/schnee.png"),
  },
  {
    q: "Treppe",
    a: "die",
    emoji: "📶",
    en: "Stairs",
    l: "A2",
    c: "Zuhause",
    img: require("./images/treppe.png"),
  },
  {
    q: "Küche",
    a: "die",
    emoji: "🍳",
    en: "Kitchen",
    l: "A1",
    c: "Zuhause",
    img: require("./images/kueche.png"),
  },
  {
    q: "Fluss",
    a: "der",
    emoji: "🏞️",
    en: "River",
    l: "A1",
    c: "Natur",
    img: require("./images/fluss.png"),
  },
  {
    q: "Ei",
    a: "das",
    emoji: "🥚",
    en: "Egg",
    l: "A1",
    c: "Essen",
    img: require("./images/ei.png"),
  },
  {
    q: "Lehrer",
    a: "der",
    emoji: "👨‍🏫",
    en: "Teacher (male)",
    l: "A1",
    c: "Berufe",
    img: require("./images/lehrer.png"),
  },
  {
    q: "Lehrerin",
    a: "die",
    emoji: "👩‍🏫",
    en: "Teacher (female)",
    l: "A1",
    c: "Berufe",
    img: require("./images/lehrerin.png"),
  },
  {
    q: "Tafel",
    a: "die",
    emoji: "📋",
    en: "Blackboard",
    l: "A1",
    c: "Schule",
    img: require("./images/tafel.png"),
  },
  {
    q: "Feder",
    a: "die",
    emoji: "🪶",
    en: "Feather",
    l: "A2",
    c: "Natur",
    img: require("./images/feder.png"),
  },
  {
    q: "Schlüssel",
    a: "der",
    emoji: "🔑",
    en: "Key",
    l: "A1",
    c: "Alltag",
    img: require("./images/schluessel.png"),
  },
  {
    q: "Spiegel",
    a: "der",
    emoji: "🪞",
    en: "Mirror",
    l: "A1",
    c: "Zuhause",
    img: require("./images/spiegel.png"),
  },
  {
    q: "Hut",
    a: "der",
    emoji: "🎩",
    en: "Hat",
    l: "A1",
    c: "Kleidung",
    img: require("./images/hut.png"),
  },
  {
    q: "Kuchen",
    a: "der",
    emoji: "🎂",
    en: "Cake",
    l: "A1",
    c: "Essen",
    img: require("./images/kuchen.png"),
  },
  {
    q: "Schlange",
    a: "die",
    emoji: "🐍",
    en: "Snake",
    l: "A2",
    c: "Tiere",
    img: require("./images/schlange.png"),
  },
  {
    q: "Schuh",
    a: "der",
    emoji: "👟",
    en: "Shoe",
    l: "A1",
    c: "Kleidung",
    img: require("./images/schuh.png"),
  },
  {
    q: "Fahrrad",
    a: "das",
    emoji: "🚲",
    en: "Bicycle",
    l: "A1",
    c: "Transport",
    img: require("./images/fahrrad.png"),
  },
  {
    q: "Messer",
    a: "das",
    emoji: "🔪",
    en: "Knife",
    l: "A1",
    c: "Essen",
    img: require("./images/messer.png"),
  },
  {
    q: "Schal",
    a: "der",
    emoji: "🧣",
    en: "Scarf",
    l: "A1",
    c: "Kleidung",
    img: require("./images/schal.png"),
  },
  {
    q: "Handschuh",
    a: "der",
    emoji: "🧤",
    en: "Glove",
    l: "A1",
    c: "Kleidung",
    img: require("./images/handschuh.png"),
  },
  {
    q: "Papier",
    a: "das",
    emoji: "📄",
    en: "Paper",
    l: "A1",
    c: "Schule",
    img: require("./images/papier.png"),
  },
  {
    q: "Brief",
    a: "der",
    emoji: "✉️",
    en: "Letter",
    l: "A1",
    c: "Alltag",
    img: require("./images/brief.png"),
  },
  {
    q: "Schlafzimmer",
    a: "das",
    emoji: "🛏️",
    en: "Bedroom",
    l: "A1",
    c: "Zuhause",
    img: require("./images/schlafzimmer.png"),
  },
  {
    q: "Handy",
    a: "das",
    emoji: "📱",
    en: "Mobile Phone",
    l: "A1",
    c: "Technik",
    img: require("./images/handy.png"),
  },
  {
    q: "Keller",
    a: "der",
    emoji: "🏚️",
    en: "Basement",
    l: "A2",
    c: "Zuhause",
    img: require("./images/keller.png"),
  },
  {
    q: "Müll",
    a: "der",
    emoji: "🗑️",
    en: "Trash",
    l: "A1",
    c: "Alltag",
    img: require("./images/muell.png"),
  },
  {
    q: "Mauer",
    a: "die",
    emoji: "🧱",
    en: "Wall",
    l: "A2",
    c: "Orte",
    img: require("./images/mauer.png"),
  },
  {
    q: "Eule",
    a: "die",
    emoji: "🦉",
    en: "Owl",
    l: "A2",
    c: "Tiere",
    img: require("./images/eule.png"),
  },
  {
    q: "Bahnsteig",
    a: "der",
    emoji: "🚉",
    en: "Platform",
    l: "A2",
    c: "Transport",
    img: require("./images/bahnsteig.png"),
  },
  {
    q: "Bier",
    a: "das",
    emoji: "🍺",
    en: "Beer",
    l: "A1",
    c: "Essen",
    img: require("./images/bier.png"),
  },
  {
    q: "Stift",
    a: "der",
    emoji: "✏️",
    en: "Pen",
    l: "A1",
    c: "Schule",
    img: require("./images/stift.png"),
  },
  {
    q: "Löffel",
    a: "der",
    emoji: "🥄",
    en: "Spoon",
    l: "A1",
    c: "Essen",
    img: require("./images/loeffel.png"),
  },
  {
    q: "Schere",
    a: "die",
    emoji: "✂️",
    en: "Scissors",
    l: "A1",
    c: "Alltag",
    img: require("./images/schere.png"),
  },
  {
    q: "Kissen",
    a: "das",
    emoji: "😴",
    en: "Pillow",
    l: "A1",
    c: "Zuhause",
    img: require("./images/kissen.png"),
  },
  {
    q: "Regen",
    a: "der",
    emoji: "🌧️",
    en: "Rain",
    l: "A1",
    c: "Natur",
    img: require("./images/regen.png"),
  },
  {
    q: "Papiere",
    a: "die",
    emoji: "📋",
    en: "Papers",
    l: "A2",
    c: "Alltag",
    img: require("./images/papiere.png"),
  },
  {
    q: "Schuhe",
    a: "die",
    emoji: "👟",
    en: "Shoes",
    l: "A1",
    c: "Kleidung",
    img: require("./images/schuhe.png"),
  },
  {
    q: "Pferd",
    a: "das",
    emoji: "🐴",
    en: "Horse",
    l: "A1",
    c: "Tiere",
    img: require("./images/pferd.png"),
  },
  {
    q: "Kuh",
    a: "die",
    emoji: "🐄",
    en: "Cow",
    l: "A1",
    c: "Tiere",
    img: require("./images/kuh.png"),
  },
  {
    q: "Huhn",
    a: "das",
    emoji: "🐔",
    en: "Chicken",
    l: "A1",
    c: "Tiere",
    img: require("./images/huhn.png"),
  },
  {
    q: "Hahn",
    a: "der",
    emoji: "🐓",
    en: "Rooster",
    l: "A2",
    c: "Tiere",
    img: require("./images/hahn.png"),
  },
  {
    q: "Schaf",
    a: "das",
    emoji: "🐑",
    en: "Sheep",
    l: "A1",
    c: "Tiere",
    img: require("./images/schaf.png"),
  },
  {
    q: "Ziege",
    a: "die",
    emoji: "🐐",
    en: "Goat",
    l: "A2",
    c: "Tiere",
    img: require("./images/ziege.png"),
  },
  {
    q: "Ente",
    a: "die",
    emoji: "🦆",
    en: "Duck",
    l: "A1",
    c: "Tiere",
    img: require("./images/ente.png"),
  },
  {
    q: "Hase",
    a: "der",
    emoji: "🐰",
    en: "Hare",
    l: "A1",
    c: "Tiere",
    img: require("./images/hase.png"),
  },
  {
    q: "Fuchs",
    a: "der",
    emoji: "🦊",
    en: "Fox",
    l: "A2",
    c: "Tiere",
    img: require("./images/fuchs.png"),
  },
  {
    q: "Wolf",
    a: "der",
    emoji: "🐺",
    en: "Wolf",
    l: "A2",
    c: "Tiere",
    img: require("./images/wolf.png"),
  },
  {
    q: "Bär",
    a: "der",
    emoji: "🐻",
    en: "Bear",
    l: "A1",
    c: "Tiere",
    img: require("./images/baer.png"),
  },
  {
    q: "Eichhörnchen",
    a: "das",
    emoji: "🐿️",
    en: "Squirrel",
    l: "A2",
    c: "Tiere",
    img: require("./images/eichhoernchen.png"),
  },
  {
    q: "Igel",
    a: "der",
    emoji: "🦔",
    en: "Hedgehog",
    l: "A2",
    c: "Tiere",
    img: require("./images/igel.png"),
  },
  {
    q: "Elefant",
    a: "der",
    emoji: "🐘",
    en: "Elephant",
    l: "A1",
    c: "Tiere",
    img: require("./images/elefant.png"),
  },
  {
    q: "Löwe",
    a: "der",
    emoji: "🦁",
    en: "Lion",
    l: "A1",
    c: "Tiere",
    img: require("./images/loewe.png"),
  },
  {
    q: "Tiger",
    a: "der",
    emoji: "🐯",
    en: "Tiger",
    l: "A1",
    c: "Tiere",
    img: require("./images/tiger.png"),
  },
  {
    q: "Affe",
    a: "der",
    emoji: "🐒",
    en: "Monkey",
    l: "A1",
    c: "Tiere",
    img: require("./images/affe.png"),
  },
  {
    q: "Giraffe",
    a: "die",
    emoji: "🦒",
    en: "Giraffe",
    l: "A1",
    c: "Tiere",
    img: require("./images/giraffe.png"),
  },
  {
    q: "Zebra",
    a: "das",
    emoji: "🦓",
    en: "Zebra",
    l: "A1",
    c: "Tiere",
    img: require("./images/zebra.png"),
  },
  {
    q: "Pinguin",
    a: "der",
    emoji: "🐧",
    en: "Penguin",
    l: "A1",
    c: "Tiere",
    img: require("./images/pinguin.png"),
  },
  {
    q: "Kamel",
    a: "das",
    emoji: "🐫",
    en: "Camel",
    l: "A2",
    c: "Tiere",
    img: require("./images/kamel.png"),
  },
  {
    q: "Biene",
    a: "die",
    emoji: "🐝",
    en: "Bee",
    l: "A2",
    c: "Tiere",
    img: require("./images/biene.png"),
  },
  {
    q: "Schmetterling",
    a: "der",
    emoji: "🦋",
    en: "Butterfly",
    l: "A2",
    c: "Tiere",
    img: require("./images/schmetterling.png"),
  },
  {
    q: "Frosch",
    a: "der",
    emoji: "🐸",
    en: "Frog",
    l: "A2",
    c: "Tiere",
    img: require("./images/frosch.png"),
  },
  {
    q: "Krokodil",
    a: "das",
    emoji: "🐊",
    en: "Crocodile",
    l: "A2",
    c: "Tiere",
    img: require("./images/krokodil.png"),
  },
  {
    q: "Esel",
    a: "der",
    emoji: "🫏",
    en: "Donkey",
    l: "A2",
    c: "Tiere",
    img: require("./images/esel.png"),
  },
  {
    q: "Papagei",
    a: "der",
    emoji: "🦜",
    en: "Parrot",
    l: "A2",
    c: "Tiere",
    img: require("./images/papagei.png"),
  },
  {
    q: "Känguru",
    a: "das",
    emoji: "🦘",
    en: "Kangaroo",
    l: "A2",
    c: "Tiere",
    img: require("./images/kaenguru.png"),
  },
  {
    q: "Koala",
    a: "der",
    emoji: "🐨",
    en: "Koala",
    l: "A2",
    c: "Tiere",
    img: require("./images/koala.png"),
  },
  {
    q: "Delphin",
    a: "der",
    emoji: "🐬",
    en: "Dolphin",
    l: "A2",
    c: "Tiere",
    img: require("./images/delphin.png"),
  },
  {
    q: "Wal",
    a: "der",
    emoji: "🐋",
    en: "Whale",
    l: "A2",
    c: "Tiere",
    img: require("./images/wal.png"),
  },
  {
    q: "Krabbe",
    a: "die",
    emoji: "🦀",
    en: "Crab",
    l: "A2",
    c: "Tiere",
    img: require("./images/krabbe.png"),
  },
  {
    q: "Schildkröte",
    a: "die",
    emoji: "🐢",
    en: "Turtle",
    l: "A2",
    c: "Tiere",
    img: require("./images/schildkroete.png"),
  },
  {
    q: "Arzt",
    a: "der",
    emoji: "👨‍⚕️",
    en: "Doctor (male)",
    l: "A2",
    c: "Berufe",
    img: require("./images/arzt.png"),
  },
  {
    q: "Ärztin",
    a: "die",
    emoji: "👩‍⚕️",
    en: "Doctor (female)",
    l: "A2",
    c: "Berufe",
    img: require("./images/aerztin.png"),
  },
  {
    q: "Kellner",
    a: "der",
    emoji: "🧑‍🍳",
    en: "Waiter",
    l: "A2",
    c: "Berufe",
    img: require("./images/kellner.png"),
  },
  {
    q: "Kellnerin",
    a: "die",
    emoji: "🧑‍🍳",
    en: "Waitress",
    l: "A2",
    c: "Berufe",
    img: require("./images/kellnerin.png"),
  },
  {
    q: "Polizist",
    a: "der",
    emoji: "👮",
    en: "Police Officer (male)",
    l: "A2",
    c: "Berufe",
    img: require("./images/polizist.png"),
  },
  {
    q: "Polizistin",
    a: "die",
    emoji: "👮‍♀️",
    en: "Police Officer (female)",
    l: "A2",
    c: "Berufe",
    img: require("./images/polizistin.png"),
  },
  {
    q: "Verkäufer",
    a: "der",
    emoji: "🛍️",
    en: "Salesman",
    l: "A2",
    c: "Berufe",
    img: require("./images/verkaeufer.png"),
  },
  {
    q: "Verkäuferin",
    a: "die",
    emoji: "🛍️",
    en: "Saleswoman",
    l: "A2",
    c: "Berufe",
    img: require("./images/verkaeuferin.png"),
  },
  {
    q: "Ingenieur",
    a: "der",
    emoji: "👷",
    en: "Engineer (male)",
    l: "B1",
    c: "Berufe",
    img: require("./images/ingenieur.png"),
  },
  {
    q: "Ingenieurin",
    a: "die",
    emoji: "👷‍♀️",
    en: "Engineer (female)",
    l: "B1",
    c: "Berufe",
    img: require("./images/ingenieurin.png"),
  },
  {
    q: "Koch",
    a: "der",
    emoji: "👨‍🍳",
    en: "Cook (male)",
    l: "A2",
    c: "Berufe",
    img: require("./images/koch.png"),
  },
  {
    q: "Köchin",
    a: "die",
    emoji: "👩‍🍳",
    en: "Cook (female)",
    l: "A2",
    c: "Berufe",
    img: require("./images/koechin.png"),
  },
  {
    q: "Bäcker",
    a: "der",
    emoji: "🥖",
    en: "Baker (male)",
    l: "A2",
    c: "Berufe",
    img: require("./images/baecker.png"),
  },
  {
    q: "Bäckerin",
    a: "die",
    emoji: "🥖",
    en: "Baker (female)",
    l: "A2",
    c: "Berufe",
    img: require("./images/baeckerin.png"),
  },
  {
    q: "Friseurin",
    a: "die",
    emoji: "💇",
    en: "Hairdresser (female)",
    l: "A2",
    c: "Berufe",
    img: require("./images/friseurin.png"),
  },
  {
    q: "Mechaniker",
    a: "der",
    emoji: "🔧",
    en: "Mechanic (male)",
    l: "A2",
    c: "Berufe",
    img: require("./images/mechaniker.png"),
  },
  {
    q: "Künstlerin",
    a: "die",
    emoji: "🎨",
    en: "Artist (female)",
    l: "B1",
    c: "Berufe",
    img: require("./images/kuenstlerin.png"),
  },
  {
    q: "Architekt",
    a: "der",
    emoji: "🏗️",
    en: "Architect (male)",
    l: "B1",
    c: "Berufe",
    img: require("./images/architekt.png"),
  },
  {
    q: "Schüler",
    a: "der",
    emoji: "👨‍🎓",
    en: "Student male school",
    l: "A1",
    c: "Schule",
    img: require("./images/schueler.png"),
  },
  {
    q: "Schülerin",
    a: "die",
    emoji: "👩‍🎓",
    en: "Student female school",
    l: "A1",
    c: "Schule",
    img: require("./images/schuelerin.png"),
  },
  {
    q: "Student",
    a: "der",
    emoji: "👨‍🎓",
    en: "University Student male",
    l: "A2",
    c: "Schule",
    img: require("./images/student.png"),
  },
  {
    q: "Studentin",
    a: "die",
    emoji: "👩‍🎓",
    en: "University Student female",
    l: "A2",
    c: "Schule",
    img: require("./images/studentin.png"),
  },
  {
    q: "Krankenschwester",
    a: "die",
    emoji: "👩‍⚕️",
    en: "Nurse female",
    l: "A2",
    c: "Berufe",
    img: require("./images/krankenschwester.png"),
  },
  {
    q: "Krankenpflegerin",
    a: "die",
    emoji: "👩‍⚕️",
    en: "Home Nurse female",
    l: "B1",
    c: "Berufe",
    img: require("./images/krankenpflegerin.png"),
  },
  {
    q: "Bauer",
    a: "der",
    emoji: "👨‍🌾",
    en: "Farmer male",
    l: "A2",
    c: "Berufe",
    img: require("./images/bauer.png"),
  },
  {
    q: "Bäuerin",
    a: "die",
    emoji: "👩‍🌾",
    en: "Farmer female",
    l: "A2",
    c: "Berufe",
    img: require("./images/baeuerin.png"),
  },
  {
    q: "Pilot",
    a: "der",
    emoji: "👨‍✈️",
    en: "Pilot male",
    l: "A2",
    c: "Berufe",
    img: require("./images/pilot.png"),
  },
  {
    q: "Sekretärin",
    a: "die",
    emoji: "💼",
    en: "Secretary female",
    l: "B1",
    c: "Berufe",
    img: require("./images/sekretaerin.png"),
  },
  {
    q: "Journalistin",
    a: "die",
    emoji: "📰",
    en: "Journalist female",
    l: "B1",
    c: "Berufe",
    img: require("./images/journalistin.png"),
  },
  {
    q: "Musiker",
    a: "der",
    emoji: "🎸",
    en: "Musician male",
    l: "A2",
    c: "Berufe",
    img: require("./images/musiker.png"),
  },
  {
    q: "Busfahrer",
    a: "der",
    emoji: "🚌",
    en: "Bus Driver male",
    l: "A2",
    c: "Berufe",
    img: require("./images/busfahrer.png"),
  },
  {
    q: "Feuerwehrmann",
    a: "der",
    emoji: "🧑‍🚒",
    en: "Firefighter male",
    l: "A2",
    c: "Berufe",
    img: require("./images/feuerwehrmann.png"),
  },
  {
    q: "Postbote",
    a: "der",
    emoji: "📬",
    en: "Mail Carrier male",
    l: "A2",
    c: "Berufe",
    img: require("./images/postbote.png"),
  },
  {
    q: "Fotograf",
    a: "der",
    emoji: "📸",
    en: "Photographer male",
    l: "A2",
    c: "Berufe",
    img: require("./images/fotograf.png"),
  },
  { q: "Vertrag", a: "der", emoji: "📄", en: "Contract", l: "B1", c: "Alltag" },
  {
    q: "Bewerbung",
    a: "die",
    emoji: "📋",
    en: "Application",
    l: "B1",
    c: "Berufe",
  },
  { q: "Rechnung", a: "die", emoji: "🧾", en: "Invoice", l: "B1", c: "Alltag" },
  {
    q: "Versicherung",
    a: "die",
    emoji: "🛡️",
    en: "Insurance",
    l: "B1",
    c: "Alltag",
  },
  {
    q: "Krankenhaus",
    a: "das",
    emoji: "🏥",
    en: "Hospital",
    l: "B1",
    c: "Gesundheit",
  },
  {
    q: "Medikament",
    a: "das",
    emoji: "💊",
    en: "Medicine",
    l: "B1",
    c: "Gesundheit",
  },
  {
    q: "Rezept",
    a: "das",
    emoji: "📝",
    en: "Prescription",
    l: "B1",
    c: "Gesundheit",
  },
  {
    q: "Termin",
    a: "der",
    emoji: "📅",
    en: "Appointment",
    l: "B1",
    c: "Alltag",
  },
  { q: "Gehalt", a: "das", emoji: "💰", en: "Salary", l: "B1", c: "Berufe" },
  { q: "Urlaub", a: "der", emoji: "🏖️", en: "Vacation", l: "B1", c: "Reisen" },
  {
    q: "Reisepass",
    a: "der",
    emoji: "🛂",
    en: "Passport",
    l: "B1",
    c: "Reisen",
  },
  { q: "Koffer", a: "der", emoji: "🧳", en: "Suitcase", l: "B1", c: "Reisen" },
  { q: "Hotel", a: "das", emoji: "🏨", en: "Hotel", l: "B1", c: "Reisen" },
  {
    q: "Flughafen",
    a: "der",
    emoji: "✈️",
    en: "Airport",
    l: "B1",
    c: "Reisen",
  },
  { q: "Grenze", a: "die", emoji: "🚧", en: "Border", l: "B1", c: "Reisen" },
  {
    q: "Gewitter",
    a: "das",
    emoji: "⛈️",
    en: "Thunderstorm",
    l: "B1",
    c: "Wetter",
  },
  {
    q: "Temperatur",
    a: "die",
    emoji: "🌡️",
    en: "Temperature",
    l: "B1",
    c: "Wetter",
  },
  {
    q: "Umgebung",
    a: "die",
    emoji: "🗺️",
    en: "Surroundings",
    l: "B1",
    c: "Orte",
  },
  {
    q: "Gesellschaft",
    a: "die",
    emoji: "👥",
    en: "Society",
    l: "B1",
    c: "Alltag",
  },
  {
    q: "Wirtschaft",
    a: "die",
    emoji: "📊",
    en: "Economy",
    l: "B1",
    c: "Alltag",
  },
  { q: "Ball", a: "der", emoji: "⚽", en: "Ball", l: "A1", c: "Sport" },
  { q: "Fußball", a: "der", emoji: "⚽", en: "Football", l: "A1", c: "Sport" },
  {
    q: "Schwimmbad",
    a: "das",
    emoji: "🏊",
    en: "Swimming pool",
    l: "A2",
    c: "Sport",
  },
  { q: "Stadion", a: "das", emoji: "🏟️", en: "Stadium", l: "A2", c: "Sport" },
  { q: "Mannschaft", a: "die", emoji: "👥", en: "Team", l: "A2", c: "Sport" },
  { q: "Sonne", a: "die", emoji: "☀️", en: "Sun", l: "A1", c: "Wetter" },
  { q: "Wind", a: "der", emoji: "💨", en: "Wind", l: "A1", c: "Wetter" },
  { q: "Nebel", a: "der", emoji: "🌫️", en: "Fog", l: "A2", c: "Wetter" },
  { q: "Frost", a: "der", emoji: "🥶", en: "Frost", l: "B1", c: "Wetter" },
  { q: "Sturm", a: "der", emoji: "🌪️", en: "Storm", l: "B1", c: "Wetter" },
  { q: "Mutter", a: "die", emoji: "👩", en: "Mother", l: "A1", c: "Familie" },
  { q: "Vater", a: "der", emoji: "👨", en: "Father", l: "A1", c: "Familie" },
  { q: "Kind", a: "das", emoji: "👶", en: "Child", l: "A1", c: "Familie" },
  { q: "Bruder", a: "der", emoji: "👦", en: "Brother", l: "A1", c: "Familie" },
  {
    q: "Schwester",
    a: "die",
    emoji: "👧",
    en: "Sister",
    l: "A1",
    c: "Familie",
  },
  { q: "Opa", a: "der", emoji: "👴", en: "Grandpa", l: "A1", c: "Familie" },
  { q: "Oma", a: "die", emoji: "👵", en: "Grandma", l: "A1", c: "Familie" },
  { q: "Baby", a: "das", emoji: "🍼", en: "Baby", l: "A1", c: "Familie" },
  {
    q: "Arztpraxis",
    a: "die",
    emoji: "🏥",
    en: "Doctor's office",
    l: "A2",
    c: "Gesundheit",
  },
  { q: "Fieber", a: "das", emoji: "🤒", en: "Fever", l: "A2", c: "Gesundheit" },
  { q: "Husten", a: "der", emoji: "😷", en: "Cough", l: "A2", c: "Gesundheit" },
  {
    q: "Kopfschmerz",
    a: "der",
    emoji: "🤕",
    en: "Headache",
    l: "A2",
    c: "Gesundheit",
  },
  {
    q: "Apotheke",
    a: "die",
    emoji: "💊",
    en: "Pharmacy",
    l: "A2",
    c: "Gesundheit",
  },
  { q: "Suppe", a: "die", emoji: "🍜", en: "Soup", l: "A1", c: "Essen" },
  { q: "Salat", a: "der", emoji: "🥗", en: "Salad", l: "A1", c: "Essen" },
  { q: "Käse", a: "der", emoji: "🧀", en: "Cheese", l: "A1", c: "Essen" },
  { q: "Butter", a: "die", emoji: "🧈", en: "Butter", l: "A1", c: "Essen" },
  { q: "Fleisch", a: "das", emoji: "🥩", en: "Meat", l: "A2", c: "Essen" },
  { q: "Obst", a: "das", emoji: "🍓", en: "Fruit", l: "A1", c: "Essen" },
  { q: "Arm", a: "der", emoji: "💪", en: "Arm", l: "A1", c: "Körper" },
  { q: "Bein", a: "das", emoji: "🦵", en: "Leg", l: "A1", c: "Körper" },
  { q: "Kopf", a: "der", emoji: "🧠", en: "Head", l: "A1", c: "Körper" },
  { q: "Rücken", a: "der", emoji: "🔙", en: "Back", l: "A2", c: "Körper" },
  { q: "Bauch", a: "der", emoji: "🤰", en: "Belly", l: "A1", c: "Körper" },
  { q: "Ohr", a: "das", emoji: "👂", en: "Ear", l: "A1", c: "Körper" },
  { q: "Mund", a: "der", emoji: "👄", en: "Mouth", l: "A1", c: "Körper" },
  { q: "Haar", a: "das", emoji: "💇", en: "Hair", l: "A1", c: "Körper" },
  {
    q: "Schulter",
    a: "die",
    emoji: "🤷",
    en: "Shoulder",
    l: "A2",
    c: "Körper",
  },
  { q: "Knie", a: "das", emoji: "🦵", en: "Knee", l: "A2", c: "Körper" },
  { q: "Fuß", a: "der", emoji: "🦶", en: "Foot", l: "A1", c: "Körper" },
  { q: "Finger", a: "der", emoji: "☝️", en: "Finger", l: "A1", c: "Körper" },
  { q: "Herz", a: "das", emoji: "❤️", en: "Heart", l: "A1", c: "Körper" },
  { q: "Blut", a: "das", emoji: "🩸", en: "Blood", l: "B1", c: "Gesundheit" },
  { q: "Schmerz", a: "der", emoji: "😣", en: "Pain", l: "B1", c: "Gesundheit" },
  {
    q: "Allergie",
    a: "die",
    emoji: "🤧",
    en: "Allergy",
    l: "B1",
    c: "Gesundheit",
  },
  {
    q: "Impfung",
    a: "die",
    emoji: "💉",
    en: "Vaccination",
    l: "B1",
    c: "Gesundheit",
  },
  {
    q: "Operation",
    a: "die",
    emoji: "🏥",
    en: "Surgery",
    l: "B1",
    c: "Gesundheit",
  },
  { q: "Kartoffel", a: "die", emoji: "🥔", en: "Potato", l: "A1", c: "Essen" },
  { q: "Tomate", a: "die", emoji: "🍅", en: "Tomato", l: "A1", c: "Essen" },
  { q: "Zwiebel", a: "die", emoji: "🧅", en: "Onion", l: "A1", c: "Essen" },
  { q: "Möhre", a: "die", emoji: "🥕", en: "Carrot", l: "A1", c: "Essen" },
  { q: "Gurke", a: "die", emoji: "🥒", en: "Cucumber", l: "A1", c: "Essen" },
  { q: "Paprika", a: "die", emoji: "🫑", en: "Pepper", l: "A1", c: "Essen" },
  { q: "Pilz", a: "der", emoji: "🍄", en: "Mushroom", l: "A2", c: "Essen" },
  { q: "Banane", a: "die", emoji: "🍌", en: "Banana", l: "A1", c: "Essen" },
  { q: "Orange", a: "die", emoji: "🍊", en: "Orange", l: "A1", c: "Essen" },
  {
    q: "Erdbeere",
    a: "die",
    emoji: "🍓",
    en: "Strawberry",
    l: "A1",
    c: "Essen",
  },
  { q: "Trauben", a: "die", emoji: "🍇", en: "Grapes", l: "A2", c: "Essen" },
  { q: "Zitrone", a: "die", emoji: "🍋", en: "Lemon", l: "A2", c: "Essen" },
  { q: "Reis", a: "der", emoji: "🍚", en: "Rice", l: "A1", c: "Essen" },
  { q: "Nudeln", a: "die", emoji: "🍝", en: "Pasta", l: "A1", c: "Essen" },
  { q: "Joghurt", a: "der", emoji: "🥛", en: "Yogurt", l: "A1", c: "Essen" },
  { q: "Milch", a: "die", emoji: "🥛", en: "Milk", l: "A1", c: "Essen" },
  { q: "Saft", a: "der", emoji: "🧃", en: "Juice", l: "A1", c: "Essen" },
  { q: "Tee", a: "der", emoji: "🍵", en: "Tea", l: "A1", c: "Essen" },
  { q: "Wein", a: "der", emoji: "🍷", en: "Wine", l: "A2", c: "Essen" },
  { q: "Zucker", a: "der", emoji: "🍬", en: "Sugar", l: "A1", c: "Essen" },
  { q: "Salz", a: "das", emoji: "🧂", en: "Salt", l: "A1", c: "Essen" },
  { q: "Öl", a: "das", emoji: "🫙", en: "Oil", l: "A2", c: "Essen" },
  {
    q: "Schokolade",
    a: "die",
    emoji: "🍫",
    en: "Chocolate",
    l: "A1",
    c: "Essen",
  },
  { q: "Eis", a: "das", emoji: "🍦", en: "Ice cream", l: "A1", c: "Essen" },
  { q: "Pizza", a: "die", emoji: "🍕", en: "Pizza", l: "A1", c: "Essen" },
  { q: "Hamburger", a: "der", emoji: "🍔", en: "Burger", l: "A1", c: "Essen" },
  { q: "Hähnchen", a: "das", emoji: "🍗", en: "Chicken", l: "A2", c: "Essen" },
  {
    q: "Schrank",
    a: "der",
    emoji: "🗄️",
    en: "Wardrobe",
    l: "A1",
    c: "Zuhause",
  },
  { q: "Regal", a: "das", emoji: "📚", en: "Shelf", l: "A2", c: "Zuhause" },
  { q: "Vorhang", a: "der", emoji: "🪟", en: "Curtain", l: "A2", c: "Zuhause" },
  { q: "Teppich", a: "der", emoji: "🟫", en: "Carpet", l: "A2", c: "Zuhause" },
  { q: "Bett", a: "das", emoji: "🛏️", en: "Bed", l: "A1", c: "Zuhause" },
  {
    q: "Badezimmer",
    a: "das",
    emoji: "🚿",
    en: "Bathroom",
    l: "A1",
    c: "Zuhause",
  },
  { q: "Dusche", a: "die", emoji: "🚿", en: "Shower", l: "A1", c: "Zuhause" },
  {
    q: "Badewanne",
    a: "die",
    emoji: "🛁",
    en: "Bathtub",
    l: "A2",
    c: "Zuhause",
  },
  {
    q: "Waschmaschine",
    a: "die",
    emoji: "🫧",
    en: "Washing machine",
    l: "A2",
    c: "Zuhause",
  },
  { q: "Herd", a: "der", emoji: "🍳", en: "Stove", l: "A2", c: "Zuhause" },
  {
    q: "Mikrowelle",
    a: "die",
    emoji: "📡",
    en: "Microwave",
    l: "A2",
    c: "Zuhause",
  },
  {
    q: "Spülmaschine",
    a: "die",
    emoji: "🍽️",
    en: "Dishwasher",
    l: "B1",
    c: "Zuhause",
  },
  { q: "Heizung", a: "die", emoji: "🌡️", en: "Heating", l: "A2", c: "Zuhause" },
  { q: "Balkon", a: "der", emoji: "🏠", en: "Balcony", l: "A2", c: "Zuhause" },
  { q: "Garage", a: "die", emoji: "🏎️", en: "Garage", l: "A2", c: "Zuhause" },
  {
    q: "Klingel",
    a: "die",
    emoji: "🔔",
    en: "Doorbell",
    l: "A2",
    c: "Zuhause",
  },
  {
    q: "Steckdose",
    a: "die",
    emoji: "🔌",
    en: "Socket",
    l: "B1",
    c: "Zuhause",
  },
  { q: "Baum", a: "der", emoji: "🌳", en: "Tree", l: "A1", c: "Natur" },
  { q: "Strand", a: "der", emoji: "🏖️", en: "Beach", l: "A1", c: "Natur" },
  { q: "Meer", a: "das", emoji: "🌊", en: "Sea", l: "A1", c: "Natur" },
  { q: "Insel", a: "die", emoji: "🏝️", en: "Island", l: "A2", c: "Natur" },
  { q: "Wüste", a: "die", emoji: "🏜️", en: "Desert", l: "B1", c: "Natur" },
  { q: "Tal", a: "das", emoji: "🏞️", en: "Valley", l: "B1", c: "Natur" },
  { q: "Feld", a: "das", emoji: "🌾", en: "Field", l: "A2", c: "Natur" },
  { q: "Wiese", a: "die", emoji: "🌿", en: "Meadow", l: "A2", c: "Natur" },
  { q: "Pflanze", a: "die", emoji: "🪴", en: "Plant", l: "A1", c: "Natur" },
  { q: "Rose", a: "die", emoji: "🌹", en: "Rose", l: "A1", c: "Natur" },
  { q: "Frühling", a: "der", emoji: "🌸", en: "Spring", l: "A1", c: "Natur" },
  { q: "Sommer", a: "der", emoji: "☀️", en: "Summer", l: "A1", c: "Natur" },
  { q: "Herbst", a: "der", emoji: "🍂", en: "Autumn", l: "A1", c: "Natur" },
  { q: "Winter", a: "der", emoji: "❄️", en: "Winter", l: "A1", c: "Natur" },
  {
    q: "Supermarkt",
    a: "der",
    emoji: "🛒",
    en: "Supermarket",
    l: "A1",
    c: "Orte",
  },
  { q: "Bäckerei", a: "die", emoji: "🥖", en: "Bakery", l: "A1", c: "Orte" },
  { q: "Rathaus", a: "das", emoji: "🏛️", en: "Town hall", l: "B1", c: "Orte" },
  { q: "Kirche", a: "die", emoji: "⛪", en: "Church", l: "A2", c: "Orte" },
  { q: "Moschee", a: "die", emoji: "🕌", en: "Mosque", l: "A2", c: "Orte" },
  { q: "Museum", a: "das", emoji: "🏛️", en: "Museum", l: "A2", c: "Orte" },
  { q: "Bibliothek", a: "die", emoji: "📚", en: "Library", l: "A2", c: "Orte" },
  {
    q: "Krankenhaus",
    a: "das",
    emoji: "🏥",
    en: "Hospital",
    l: "A2",
    c: "Orte",
  },
  { q: "Polizei", a: "die", emoji: "👮", en: "Police", l: "A2", c: "Orte" },
  {
    q: "Feuerwehr",
    a: "die",
    emoji: "🚒",
    en: "Fire brigade",
    l: "A2",
    c: "Orte",
  },
  {
    q: "Restaurant",
    a: "das",
    emoji: "🍽️",
    en: "Restaurant",
    l: "A1",
    c: "Orte",
  },
  { q: "Café", a: "das", emoji: "☕", en: "Café", l: "A1", c: "Orte" },
  { q: "Bank", a: "die", emoji: "🏦", en: "Bank", l: "A2", c: "Orte" },
  { q: "Post", a: "die", emoji: "📮", en: "Post office", l: "A2", c: "Orte" },
  { q: "Markt", a: "der", emoji: "🛍️", en: "Market", l: "A1", c: "Orte" },
  { q: "Kino", a: "das", emoji: "🎬", en: "Cinema", l: "A1", c: "Freizeit" },
  {
    q: "Theater",
    a: "das",
    emoji: "🎭",
    en: "Theatre",
    l: "A2",
    c: "Freizeit",
  },
  { q: "Büro", a: "das", emoji: "🏢", en: "Office", l: "A2", c: "Berufe" },
  {
    q: "Besprechung",
    a: "die",
    emoji: "👥",
    en: "Meeting",
    l: "B1",
    c: "Berufe",
  },
  {
    q: "Kollege",
    a: "der",
    emoji: "🤝",
    en: "Colleague",
    l: "A2",
    c: "Berufe",
  },
  {
    q: "Chefin",
    a: "die",
    emoji: "👩‍💼",
    en: "Boss female",
    l: "B1",
    c: "Berufe",
  },
  { q: "Chef", a: "der", emoji: "👨‍💼", en: "Boss", l: "B1", c: "Berufe" },
  { q: "Anwalt", a: "der", emoji: "⚖️", en: "Lawyer", l: "B1", c: "Berufe" },
  { q: "Zahnarzt", a: "der", emoji: "🦷", en: "Dentist", l: "A2", c: "Berufe" },
  { q: "Tierarzt", a: "der", emoji: "🐾", en: "Vet", l: "A2", c: "Berufe" },
  { q: "Urlaub", a: "der", emoji: "🏖️", en: "Holiday", l: "A1", c: "Freizeit" },
  { q: "Hobby", a: "das", emoji: "🎯", en: "Hobby", l: "A1", c: "Freizeit" },
  { q: "Spiel", a: "das", emoji: "🎮", en: "Game", l: "A1", c: "Freizeit" },
  {
    q: "Konzert",
    a: "das",
    emoji: "🎵",
    en: "Concert",
    l: "A2",
    c: "Freizeit",
  },
  {
    q: "Ausstellung",
    a: "die",
    emoji: "🖼️",
    en: "Exhibition",
    l: "B1",
    c: "Freizeit",
  },
  {
    q: "Schwimmen",
    a: "das",
    emoji: "🏊",
    en: "Swimming",
    l: "A1",
    c: "Sport",
  },
  { q: "Laufen", a: "das", emoji: "🏃", en: "Running", l: "A1", c: "Sport" },
  { q: "Tanzen", a: "das", emoji: "💃", en: "Dancing", l: "A2", c: "Freizeit" },
  { q: "Lesen", a: "das", emoji: "📖", en: "Reading", l: "A1", c: "Freizeit" },
  { q: "Kochen", a: "das", emoji: "🍳", en: "Cooking", l: "A1", c: "Freizeit" },
  { q: "Prüfung", a: "die", emoji: "📝", en: "Exam", l: "A2", c: "Schule" },
  { q: "Note", a: "die", emoji: "💯", en: "Grade", l: "A2", c: "Schule" },
  {
    q: "Unterricht",
    a: "der",
    emoji: "📚",
    en: "Lesson",
    l: "A2",
    c: "Schule",
  },
  {
    q: "Hausaufgabe",
    a: "die",
    emoji: "📋",
    en: "Homework",
    l: "A1",
    c: "Schule",
  },
  { q: "Bleistift", a: "der", emoji: "✏️", en: "Pencil", l: "A1", c: "Schule" },
  { q: "Lineal", a: "das", emoji: "📏", en: "Ruler", l: "A1", c: "Schule" },
  {
    q: "Rucksack",
    a: "der",
    emoji: "🎒",
    en: "Backpack",
    l: "A1",
    c: "Schule",
  },
  { q: "Klasse", a: "die", emoji: "🏫", en: "Class", l: "A1", c: "Schule" },
  { q: "Sprache", a: "die", emoji: "🗣️", en: "Language", l: "A2", c: "Schule" },
  {
    q: "Wörterbuch",
    a: "das",
    emoji: "📖",
    en: "Dictionary",
    l: "A2",
    c: "Schule",
  },
  { q: "Bus", a: "der", emoji: "🚌", en: "Bus", l: "A1", c: "Transport" },
  { q: "Taxi", a: "das", emoji: "🚕", en: "Taxi", l: "A1", c: "Transport" },
  { q: "Zug", a: "der", emoji: "🚂", en: "Train", l: "A1", c: "Transport" },
  { q: "U-Bahn", a: "die", emoji: "🚇", en: "Subway", l: "A2", c: "Transport" },
  { q: "Hafen", a: "der", emoji: "⚓", en: "Port", l: "B1", c: "Transport" },
  { q: "Schiff", a: "das", emoji: "🚢", en: "Ship", l: "A2", c: "Transport" },
  {
    q: "Motorrad",
    a: "das",
    emoji: "🏍️",
    en: "Motorcycle",
    l: "A2",
    c: "Transport",
  },
  {
    q: "Ampel",
    a: "die",
    emoji: "🚦",
    en: "Traffic light",
    l: "A2",
    c: "Transport",
  },
  {
    q: "Führerschein",
    a: "der",
    emoji: "🪪",
    en: "Driving licence",
    l: "B1",
    c: "Transport",
  },
  {
    q: "Stau",
    a: "der",
    emoji: "🚗",
    en: "Traffic jam",
    l: "B1",
    c: "Transport",
  },
  { q: "Fernseher", a: "der", emoji: "📺", en: "TV", l: "A1", c: "Technik" },
  { q: "Radio", a: "das", emoji: "📻", en: "Radio", l: "A1", c: "Technik" },
  {
    q: "Internet",
    a: "das",
    emoji: "🌐",
    en: "Internet",
    l: "A1",
    c: "Technik",
  },
  { q: "App", a: "die", emoji: "📱", en: "App", l: "A1", c: "Technik" },
  { q: "Drucker", a: "der", emoji: "🖨️", en: "Printer", l: "A2", c: "Technik" },
  {
    q: "Tastatur",
    a: "die",
    emoji: "⌨️",
    en: "Keyboard",
    l: "A2",
    c: "Technik",
  },
  {
    q: "Bildschirm",
    a: "der",
    emoji: "🖥️",
    en: "Screen",
    l: "A2",
    c: "Technik",
  },
  {
    q: "Kopfhörer",
    a: "der",
    emoji: "🎧",
    en: "Headphones",
    l: "A2",
    c: "Technik",
  },
  {
    q: "Ladekabel",
    a: "das",
    emoji: "🔌",
    en: "Charging cable",
    l: "A2",
    c: "Technik",
  },
  {
    q: "Passwort",
    a: "das",
    emoji: "🔐",
    en: "Password",
    l: "A2",
    c: "Technik",
  },
  {
    q: "Zeitung",
    a: "die",
    emoji: "📰",
    en: "Newspaper",
    l: "A2",
    c: "Alltag",
  },
  { q: "Formular", a: "das", emoji: "📋", en: "Form", l: "B1", c: "Alltag" },
  {
    q: "Wartezimmer",
    a: "das",
    emoji: "🪑",
    en: "Waiting room",
    l: "B1",
    c: "Alltag",
  },
  { q: "Einkauf", a: "der", emoji: "🛍️", en: "Shopping", l: "A1", c: "Alltag" },
  { q: "Quittung", a: "die", emoji: "🧾", en: "Receipt", l: "B1", c: "Alltag" },
  { q: "Karte", a: "die", emoji: "💳", en: "Card", l: "A1", c: "Alltag" },
  {
    q: "Kalender",
    a: "der",
    emoji: "📅",
    en: "Calendar",
    l: "A1",
    c: "Alltag",
  },
  { q: "Adresse", a: "die", emoji: "📍", en: "Address", l: "A1", c: "Alltag" },
  {
    q: "Nachricht",
    a: "die",
    emoji: "💬",
    en: "Message",
    l: "A1",
    c: "Alltag",
  },
  { q: "Anruf", a: "der", emoji: "📞", en: "Call", l: "A1", c: "Alltag" },
  { q: "Arm", a: "der", emoji: "💪", en: "Arm", l: "A1", c: "Körper" },
  { q: "Bein", a: "das", emoji: "🦵", en: "Leg", l: "A1", c: "Körper" },
  { q: "Rücken", a: "der", emoji: "🧍", en: "Back", l: "A2", c: "Körper" },
  {
    q: "Schulter",
    a: "die",
    emoji: "🧍",
    en: "Shoulder",
    l: "A2",
    c: "Körper",
  },
  { q: "Knie", a: "das", emoji: "🦵", en: "Knee", l: "A2", c: "Körper" },
  { q: "Fuß", a: "der", emoji: "🦶", en: "Foot", l: "A1", c: "Körper" },
  { q: "Finger", a: "der", emoji: "👆", en: "Finger", l: "A1", c: "Körper" },
  { q: "Ohr", a: "das", emoji: "👂", en: "Ear", l: "A1", c: "Körper" },
  { q: "Mund", a: "der", emoji: "👄", en: "Mouth", l: "A1", c: "Körper" },
  { q: "Kopf", a: "der", emoji: "🤯", en: "Head", l: "A1", c: "Körper" },
  { q: "Herz", a: "das", emoji: "❤️", en: "Heart", l: "A1", c: "Körper" },
  { q: "Magen", a: "der", emoji: "🫃", en: "Stomach", l: "A2", c: "Körper" },
  { q: "Hals", a: "der", emoji: "🧣", en: "Throat/Neck", l: "A2", c: "Körper" },
  { q: "Haut", a: "die", emoji: "🩹", en: "Skin", l: "B1", c: "Körper" },
  { q: "Blut", a: "das", emoji: "🩸", en: "Blood", l: "B1", c: "Körper" },
  { q: "Knochen", a: "der", emoji: "🦴", en: "Bone", l: "B1", c: "Körper" },
  { q: "Muskel", a: "der", emoji: "💪", en: "Muscle", l: "B1", c: "Körper" },
  { q: "Wunde", a: "die", emoji: "🩹", en: "Wound", l: "B1", c: "Gesundheit" },
  {
    q: "Allergie",
    a: "die",
    emoji: "🤧",
    en: "Allergy",
    l: "B1",
    c: "Gesundheit",
  },
  {
    q: "Impfung",
    a: "die",
    emoji: "💉",
    en: "Vaccination",
    l: "B1",
    c: "Gesundheit",
  },
  {
    q: "Operation",
    a: "die",
    emoji: "🏥",
    en: "Operation",
    l: "B1",
    c: "Gesundheit",
  },
  {
    q: "Pflaster",
    a: "das",
    emoji: "🩹",
    en: "Band-aid",
    l: "A2",
    c: "Gesundheit",
  },
  { q: "Gemüse", a: "das", emoji: "🥦", en: "Vegetables", l: "A1", c: "Essen" },
  { q: "Kartoffel", a: "die", emoji: "🥔", en: "Potato", l: "A1", c: "Essen" },
  { q: "Tomate", a: "die", emoji: "🍅", en: "Tomato", l: "A1", c: "Essen" },
  { q: "Zwiebel", a: "die", emoji: "🧅", en: "Onion", l: "A2", c: "Essen" },
  { q: "Karotte", a: "die", emoji: "🥕", en: "Carrot", l: "A1", c: "Essen" },
  { q: "Gurke", a: "die", emoji: "🥒", en: "Cucumber", l: "A1", c: "Essen" },
  {
    q: "Paprika",
    a: "die",
    emoji: "🫑",
    en: "Bell pepper",
    l: "A2",
    c: "Essen",
  },
  { q: "Banane", a: "die", emoji: "🍌", en: "Banana", l: "A1", c: "Essen" },
  { q: "Orange", a: "die", emoji: "🍊", en: "Orange", l: "A1", c: "Essen" },
  {
    q: "Erdbeere",
    a: "die",
    emoji: "🍓",
    en: "Strawberry",
    l: "A1",
    c: "Essen",
  },
  { q: "Tee", a: "der", emoji: "🍵", en: "Tea", l: "A1", c: "Essen" },
  { q: "Saft", a: "der", emoji: "🥤", en: "Juice", l: "A1", c: "Essen" },
  { q: "Milch", a: "die", emoji: "🥛", en: "Milk", l: "A1", c: "Essen" },
  { q: "Zucker", a: "der", emoji: "🍬", en: "Sugar", l: "A1", c: "Essen" },
  { q: "Salz", a: "das", emoji: "🧂", en: "Salt", l: "A1", c: "Essen" },
  { q: "Öl", a: "das", emoji: "🫙", en: "Oil", l: "A2", c: "Essen" },
  { q: "Nudeln", a: "die", emoji: "🍝", en: "Pasta", l: "A1", c: "Essen" },
  { q: "Reis", a: "der", emoji: "🍚", en: "Rice", l: "A1", c: "Essen" },
  {
    q: "Schokolade",
    a: "die",
    emoji: "🍫",
    en: "Chocolate",
    l: "A1",
    c: "Essen",
  },
  { q: "Eis", a: "das", emoji: "🍦", en: "Ice cream", l: "A1", c: "Essen" },
  { q: "Marmelade", a: "die", emoji: "🍯", en: "Jam", l: "A2", c: "Essen" },
  { q: "Wein", a: "der", emoji: "🍷", en: "Wine", l: "A2", c: "Essen" },
  { q: "Teller", a: "der", emoji: "🍽️", en: "Plate", l: "A1", c: "Essen" },
  { q: "Gabel", a: "die", emoji: "🍴", en: "Fork", l: "A1", c: "Essen" },
  {
    q: "Schrank",
    a: "der",
    emoji: "🪞",
    en: "Wardrobe",
    l: "A1",
    c: "Zuhause",
  },
  { q: "Regal", a: "das", emoji: "📚", en: "Shelf", l: "A2", c: "Zuhause" },
  { q: "Vorhang", a: "der", emoji: "🪟", en: "Curtain", l: "A2", c: "Zuhause" },
  { q: "Teppich", a: "der", emoji: "🟫", en: "Carpet", l: "A2", c: "Zuhause" },
  {
    q: "Badewanne",
    a: "die",
    emoji: "🛁",
    en: "Bathtub",
    l: "A2",
    c: "Zuhause",
  },
  { q: "Dusche", a: "die", emoji: "🚿", en: "Shower", l: "A2", c: "Zuhause" },
  {
    q: "Waschbecken",
    a: "das",
    emoji: "🚰",
    en: "Sink",
    l: "A2",
    c: "Zuhause",
  },
  { q: "Toilette", a: "die", emoji: "🚽", en: "Toilet", l: "A1", c: "Zuhause" },
  { q: "Bett", a: "das", emoji: "🛏️", en: "Bed", l: "A1", c: "Zuhause" },
  { q: "Decke", a: "die", emoji: "🛌", en: "Blanket", l: "A2", c: "Zuhause" },
  {
    q: "Waschmaschine",
    a: "die",
    emoji: "🫧",
    en: "Washing machine",
    l: "A2",
    c: "Zuhause",
  },
  { q: "Herd", a: "der", emoji: "🔥", en: "Stove", l: "A2", c: "Zuhause" },
  {
    q: "Mikrowelle",
    a: "die",
    emoji: "📻",
    en: "Microwave",
    l: "A2",
    c: "Zuhause",
  },
  {
    q: "Spülmaschine",
    a: "die",
    emoji: "🍽️",
    en: "Dishwasher",
    l: "B1",
    c: "Zuhause",
  },
  {
    q: "Steckdose",
    a: "die",
    emoji: "🔌",
    en: "Power outlet",
    l: "B1",
    c: "Zuhause",
  },
  { q: "Balkon", a: "der", emoji: "🏠", en: "Balcony", l: "A2", c: "Zuhause" },
  { q: "Garage", a: "die", emoji: "🏠", en: "Garage", l: "A2", c: "Zuhause" },
  {
    q: "Klingel",
    a: "die",
    emoji: "🔔",
    en: "Doorbell",
    l: "A2",
    c: "Zuhause",
  },
  { q: "Frühling", a: "der", emoji: "🌸", en: "Spring", l: "A1", c: "Natur" },
  { q: "Sommer", a: "der", emoji: "☀️", en: "Summer", l: "A1", c: "Natur" },
  { q: "Herbst", a: "der", emoji: "🍂", en: "Autumn", l: "A1", c: "Natur" },
  { q: "Winter", a: "der", emoji: "❄️", en: "Winter", l: "A1", c: "Natur" },
  { q: "Pflanze", a: "die", emoji: "🌱", en: "Plant", l: "A1", c: "Natur" },
  { q: "Baum", a: "der", emoji: "🌳", en: "Tree", l: "A1", c: "Natur" },
  { q: "Meer", a: "das", emoji: "🌊", en: "Sea", l: "A1", c: "Natur" },
  { q: "Strand", a: "der", emoji: "🏖️", en: "Beach", l: "A1", c: "Natur" },
  { q: "Insel", a: "die", emoji: "🏝️", en: "Island", l: "A2", c: "Natur" },
  { q: "Wüste", a: "die", emoji: "🏜️", en: "Desert", l: "B1", c: "Natur" },
  { q: "Dschungel", a: "der", emoji: "🌴", en: "Jungle", l: "B1", c: "Natur" },
  { q: "Vulkan", a: "der", emoji: "🌋", en: "Volcano", l: "B1", c: "Natur" },
  { q: "Erde", a: "die", emoji: "🌍", en: "Earth", l: "A1", c: "Natur" },
  { q: "Luft", a: "die", emoji: "💨", en: "Air", l: "A1", c: "Natur" },
  { q: "Feuer", a: "das", emoji: "🔥", en: "Fire", l: "A1", c: "Natur" },
  { q: "Stein", a: "der", emoji: "🪨", en: "Stone", l: "A1", c: "Natur" },
  { q: "Sand", a: "der", emoji: "🏖️", en: "Sand", l: "A1", c: "Natur" },
  {
    q: "Umwelt",
    a: "die",
    emoji: "🌍",
    en: "Environment",
    l: "B1",
    c: "Natur",
  },
  { q: "Rathaus", a: "das", emoji: "🏛️", en: "City hall", l: "A2", c: "Orte" },
  { q: "Kirche", a: "die", emoji: "⛪", en: "Church", l: "A2", c: "Orte" },
  {
    q: "Supermarkt",
    a: "der",
    emoji: "🛒",
    en: "Supermarket",
    l: "A1",
    c: "Orte",
  },
  {
    q: "Krankenhaus",
    a: "das",
    emoji: "🏥",
    en: "Hospital",
    l: "A1",
    c: "Orte",
  },
  { q: "Polizei", a: "die", emoji: "🚔", en: "Police", l: "A2", c: "Orte" },
  {
    q: "Feuerwehr",
    a: "die",
    emoji: "🚒",
    en: "Fire station",
    l: "A2",
    c: "Orte",
  },
  { q: "Museum", a: "das", emoji: "🏛️", en: "Museum", l: "A2", c: "Orte" },
  {
    q: "Theater",
    a: "das",
    emoji: "🎭",
    en: "Theater",
    l: "A2",
    c: "Freizeit",
  },
  { q: "Bibliothek", a: "die", emoji: "📚", en: "Library", l: "A2", c: "Orte" },
  { q: "Apotheke", a: "die", emoji: "💊", en: "Pharmacy", l: "A2", c: "Orte" },
  { q: "Bank", a: "die", emoji: "🏦", en: "Bank", l: "A2", c: "Orte" },
  { q: "Post", a: "die", emoji: "📮", en: "Post office", l: "A2", c: "Orte" },
  { q: "Markt", a: "der", emoji: "🛍️", en: "Market", l: "A1", c: "Orte" },
  {
    q: "Restaurant",
    a: "das",
    emoji: "🍽️",
    en: "Restaurant",
    l: "A1",
    c: "Freizeit",
  },
  { q: "Café", a: "das", emoji: "☕", en: "Café", l: "A1", c: "Freizeit" },
  {
    q: "Ampel",
    a: "die",
    emoji: "🚦",
    en: "Traffic light",
    l: "A2",
    c: "Orte",
  },
  {
    q: "Bürgersteig",
    a: "der",
    emoji: "🚶",
    en: "Sidewalk",
    l: "B1",
    c: "Orte",
  },
  { q: "Büro", a: "das", emoji: "🏢", en: "Office", l: "A2", c: "Berufe" },
  {
    q: "Kollege",
    a: "der",
    emoji: "🤝",
    en: "Colleague",
    l: "A2",
    c: "Berufe",
  },
  {
    q: "Kollegin",
    a: "die",
    emoji: "🤝",
    en: "Colleague(f)",
    l: "A2",
    c: "Berufe",
  },
  { q: "Chef", a: "der", emoji: "👔", en: "Boss", l: "A2", c: "Berufe" },
  { q: "Chefin", a: "die", emoji: "👔", en: "Boss(f)", l: "A2", c: "Berufe" },
  {
    q: "Besprechung",
    a: "die",
    emoji: "📊",
    en: "Meeting",
    l: "B1",
    c: "Berufe",
  },
  { q: "Aufgabe", a: "die", emoji: "📋", en: "Task", l: "B1", c: "Berufe" },
  { q: "Projekt", a: "das", emoji: "📁", en: "Project", l: "B1", c: "Berufe" },
  { q: "Karriere", a: "die", emoji: "📈", en: "Career", l: "B1", c: "Berufe" },
  {
    q: "Ausbildung",
    a: "die",
    emoji: "🎓",
    en: "Training",
    l: "B1",
    c: "Berufe",
  },
  {
    q: "Praktikum",
    a: "das",
    emoji: "🎒",
    en: "Internship",
    l: "B1",
    c: "Berufe",
  },
  {
    q: "Kündigung",
    a: "die",
    emoji: "📄",
    en: "Resignation",
    l: "B1",
    c: "Berufe",
  },
  { q: "Kino", a: "das", emoji: "🎬", en: "Cinema", l: "A1", c: "Freizeit" },
  {
    q: "Konzert",
    a: "das",
    emoji: "🎵",
    en: "Concert",
    l: "A2",
    c: "Freizeit",
  },
  {
    q: "Ausstellung",
    a: "die",
    emoji: "🖼️",
    en: "Exhibition",
    l: "B1",
    c: "Freizeit",
  },
  { q: "Spiel", a: "das", emoji: "🎮", en: "Game", l: "A1", c: "Freizeit" },
  { q: "Buch", a: "das", emoji: "📖", en: "Book", l: "A1", c: "Freizeit" },
  { q: "Foto", a: "das", emoji: "📸", en: "Photo", l: "A1", c: "Freizeit" },
  { q: "Urlaub", a: "der", emoji: "🌴", en: "Holiday", l: "A2", c: "Freizeit" },
  {
    q: "Picknick",
    a: "das",
    emoji: "🧺",
    en: "Picnic",
    l: "A2",
    c: "Freizeit",
  },
  { q: "Hobby", a: "das", emoji: "🎨", en: "Hobby", l: "A1", c: "Freizeit" },
  { q: "Party", a: "die", emoji: "🎉", en: "Party", l: "A1", c: "Freizeit" },
  {
    q: "Geburtstag",
    a: "der",
    emoji: "🎂",
    en: "Birthday",
    l: "A1",
    c: "Freizeit",
  },
  {
    q: "Ferien",
    a: "die",
    emoji: "🏖️",
    en: "School holiday",
    l: "A1",
    c: "Freizeit",
  },
  { q: "Prüfung", a: "die", emoji: "📝", en: "Exam", l: "A2", c: "Schule" },
  { q: "Note", a: "die", emoji: "⭐", en: "Grade", l: "A2", c: "Schule" },
  {
    q: "Unterricht",
    a: "der",
    emoji: "📚",
    en: "Lesson",
    l: "A2",
    c: "Schule",
  },
  {
    q: "Hausaufgabe",
    a: "die",
    emoji: "✏️",
    en: "Homework",
    l: "A1",
    c: "Schule",
  },
  { q: "Klasse", a: "die", emoji: "🏫", en: "Class", l: "A1", c: "Schule" },
  { q: "Pause", a: "die", emoji: "⏸️", en: "Break", l: "A1", c: "Schule" },
  {
    q: "Zeugnis",
    a: "das",
    emoji: "📄",
    en: "Report card",
    l: "B1",
    c: "Schule",
  },
  {
    q: "Wörterbuch",
    a: "das",
    emoji: "📖",
    en: "Dictionary",
    l: "A2",
    c: "Schule",
  },
  { q: "Bleistift", a: "der", emoji: "✏️", en: "Pencil", l: "A1", c: "Schule" },
  { q: "Heft", a: "das", emoji: "📓", en: "Notebook", l: "A1", c: "Schule" },
  { q: "Lineal", a: "das", emoji: "📏", en: "Ruler", l: "A2", c: "Schule" },
  {
    q: "Rucksack",
    a: "der",
    emoji: "🎒",
    en: "Backpack",
    l: "A1",
    c: "Schule",
  },
  { q: "Bus", a: "der", emoji: "🚌", en: "Bus", l: "A1", c: "Transport" },
  { q: "Taxi", a: "das", emoji: "🚕", en: "Taxi", l: "A1", c: "Transport" },
  { q: "U-Bahn", a: "die", emoji: "🚇", en: "Subway", l: "A2", c: "Transport" },
  { q: "Schiff", a: "das", emoji: "🚢", en: "Ship", l: "A1", c: "Transport" },
  { q: "Hafen", a: "der", emoji: "⚓", en: "Harbor", l: "A2", c: "Transport" },
  { q: "Ticket", a: "das", emoji: "🎫", en: "Ticket", l: "A1", c: "Transport" },
  {
    q: "Haltestelle",
    a: "die",
    emoji: "🚏",
    en: "Bus stop",
    l: "A2",
    c: "Transport",
  },
  { q: "Landkarte", a: "die", emoji: "🗺️", en: "Map", l: "A2", c: "Transport" },
  {
    q: "Kreuzung",
    a: "die",
    emoji: "🔀",
    en: "Intersection",
    l: "B1",
    c: "Transport",
  },
  {
    q: "Autobahn",
    a: "die",
    emoji: "🛣️",
    en: "Motorway",
    l: "B1",
    c: "Transport",
  },
  {
    q: "Tankstelle",
    a: "die",
    emoji: "⛽",
    en: "Gas station",
    l: "A2",
    c: "Transport",
  },
  {
    q: "Parkplatz",
    a: "der",
    emoji: "🅿️",
    en: "Parking lot",
    l: "A2",
    c: "Transport",
  },
  { q: "Fernseher", a: "der", emoji: "📺", en: "TV", l: "A1", c: "Technik" },
  { q: "Radio", a: "das", emoji: "📻", en: "Radio", l: "A1", c: "Technik" },
  {
    q: "Internet",
    a: "das",
    emoji: "🌐",
    en: "Internet",
    l: "A1",
    c: "Technik",
  },
  { q: "App", a: "die", emoji: "📱", en: "App", l: "A2", c: "Technik" },
  {
    q: "Passwort",
    a: "das",
    emoji: "🔐",
    en: "Password",
    l: "A2",
    c: "Technik",
  },
  {
    q: "Bildschirm",
    a: "der",
    emoji: "🖥️",
    en: "Screen",
    l: "A2",
    c: "Technik",
  },
  {
    q: "Tastatur",
    a: "die",
    emoji: "⌨️",
    en: "Keyboard",
    l: "A2",
    c: "Technik",
  },
  { q: "Drucker", a: "der", emoji: "🖨️", en: "Printer", l: "A2", c: "Technik" },
  {
    q: "Kopfhörer",
    a: "der",
    emoji: "🎧",
    en: "Headphones",
    l: "A2",
    c: "Technik",
  },
  {
    q: "Ladekabel",
    a: "das",
    emoji: "🔌",
    en: "Charging cable",
    l: "A2",
    c: "Technik",
  },
  { q: "Akku", a: "der", emoji: "🔋", en: "Battery", l: "A2", c: "Technik" },
  {
    q: "Netzwerk",
    a: "das",
    emoji: "🌐",
    en: "Network",
    l: "B1",
    c: "Technik",
  },
  { q: "Datei", a: "die", emoji: "📁", en: "File", l: "B1", c: "Technik" },
  {
    q: "Software",
    a: "die",
    emoji: "💾",
    en: "Software",
    l: "B1",
    c: "Technik",
  },
];
