export const quizMainData = [
  {
    question: "Haus",
    correctAnswer: "das",
    image: require("./images/haus.png"),
    englishName: "House",
    level: "A1",
    category: "Zuhause",
    translations: {
      ru: "Дом",
      tr: "Ev",
      ar: "بيت",
      fr: "Maison",
      es: "Casa",
      uk: "Будинок",
    },
  },
  {
    question: "Sonne",
    correctAnswer: "die",
    image: require("./images/sonne.png"),
    englishName: "Sun",
    level: "A1",
    category: "Natur",
    translations: {
      ru: "Солнце",
      tr: "Güneş",
      ar: "شمس",
      fr: "Soleil",
      es: "Sol",
      uk: "Сонце",
    },
  },
  {
    question: "Katze",
    correctAnswer: "die",
    image: require("./images/katze.png"),
    englishName: "Cat",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Кошка",
      tr: "Kedi",
      ar: "قطة",
      fr: "Chat",
      es: "Gato",
      uk: "Кішка",
    },
  },
  {
    question: "Vogel",
    correctAnswer: "der",
    image: require("./images/vogel.png"),
    englishName: "Bird",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Птица",
      tr: "Kuş",
      ar: "طائر",
      fr: "Oiseau",
      es: "Pájaro",
      uk: "Птах",
    },
  },
  {
    question: "Auto",
    correctAnswer: "das",
    image: require("./images/auto.png"),
    englishName: "Car",
    level: "A1",
    category: "Transport",
    translations: {
      ru: "Машина",
      tr: "Araba",
      ar: "سيارة",
      fr: "Voiture",
      es: "Coche",
      uk: "Машина",
    },
  },
  {
    question: "Tisch",
    correctAnswer: "der",
    image: require("./images/tisch.png"),
    englishName: "Table",
    level: "A1",
    category: "Zuhause",
    translations: {
      ru: "Стол",
      tr: "Masa",
      ar: "طاولة",
      fr: "Table",
      es: "Mesa",
      uk: "Стіл",
    },
  },
  {
    question: "Apfel",
    correctAnswer: "der",
    image: require("./images/apfel.png"),
    englishName: "Apple",
    level: "A1",
    category: "Essen",
    translations: {
      ru: "Яблоко",
      tr: "Elma",
      ar: "تفاحة",
      fr: "Pomme",
      es: "Manzana",
      uk: "Яблуко",
    },
  },
  {
    question: "Buch",
    correctAnswer: "das",
    image: require("./images/buch.png"),
    englishName: "Book",
    level: "A1",
    category: "Schule",
    translations: {
      ru: "Книга",
      tr: "Kitap",
      ar: "كتاب",
      fr: "Livre",
      es: "Libro",
      uk: "Книга",
    },
  },
  {
    question: "Computer",
    correctAnswer: "der",
    image: require("./images/computer.png"),
    englishName: "Computer",
    level: "A1",
    category: "Technik",
    translations: {
      ru: "Компьютер",
      tr: "Bilgisayar",
      ar: "حاسوب",
      fr: "Ordinateur",
      es: "Ordenador",
      uk: "Комп'ютер",
    },
  },
  {
    question: "Stadt",
    correctAnswer: "die",
    image: require("./images/stadt.png"),
    englishName: "City",
    level: "A1",
    category: "Orte",
    translations: {
      ru: "Город",
      tr: "Şehir",
      ar: "مدينة",
      fr: "Ville",
      es: "Ciudad",
      uk: "Місто",
    },
  },
  {
    question: "Hund",
    correctAnswer: "der",
    image: require("./images/hund.png"),
    englishName: "Dog",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Собака",
      tr: "Köpek",
      ar: "كلب",
      fr: "Chien",
      es: "Perro",
      uk: "Собака",
    },
  },
  {
    question: "Blume",
    correctAnswer: "die",
    image: require("./images/blume.png"),
    englishName: "Flower",
    level: "A1",
    category: "Natur",
    translations: {
      ru: "Цветок",
      tr: "Çiçek",
      ar: "زهرة",
      fr: "Fleur",
      es: "Flor",
      uk: "Квітка",
    },
  },
  {
    question: "Telefon",
    correctAnswer: "das",
    image: require("./images/telefon.png"),
    englishName: "Telephone",
    level: "A1",
    category: "Technik",
    translations: {
      ru: "Телефон",
      tr: "Telefon",
      ar: "هاتف",
      fr: "Téléphone",
      es: "Teléfono",
      uk: "Телефон",
    },
  },
  {
    question: "Wasser",
    correctAnswer: "das",
    image: require("./images/wasser.png"),
    englishName: "Water",
    level: "A1",
    category: "Essen",
    translations: {
      ru: "Вода",
      tr: "Su",
      ar: "ماء",
      fr: "Eau",
      es: "Agua",
      uk: "Вода",
    },
  },
  {
    question: "Kaffee",
    correctAnswer: "der",
    image: require("./images/kaffee.png"),
    englishName: "Coffee",
    level: "A1",
    category: "Essen",
    translations: {
      ru: "Кофе",
      tr: "Kahve",
      ar: "قهوة",
      fr: "Café",
      es: "Café",
      uk: "Кава",
    },
  },
  {
    question: "Fenster",
    correctAnswer: "das",
    image: require("./images/fenster.png"),
    englishName: "Window",
    level: "A1",
    category: "Zuhause",
    translations: {
      ru: "Окно",
      tr: "Pencere",
      ar: "نافذة",
      fr: "Fenêtre",
      es: "Ventana",
      uk: "Вікно",
    },
  },
  {
    question: "Schule",
    correctAnswer: "die",
    image: require("./images/schule.png"),
    englishName: "School",
    level: "A1",
    category: "Schule",
    translations: {
      ru: "Школа",
      tr: "Okul",
      ar: "مدرسة",
      fr: "École",
      es: "Escuela",
      uk: "Школа",
    },
  },
  {
    question: "Lampe",
    correctAnswer: "die",
    image: require("./images/lampe.png"),
    englishName: "Lamp",
    level: "A1",
    category: "Zuhause",
    translations: {
      ru: "Лампа",
      tr: "Lamba",
      ar: "مصباح",
      fr: "Lampe",
      es: "Lámpara",
      uk: "Лампа",
    },
  },
  {
    question: "Brot",
    correctAnswer: "das",
    image: require("./images/brot.png"),
    englishName: "Bread",
    level: "A1",
    category: "Essen",
    translations: {
      ru: "Хлеб",
      tr: "Ekmek",
      ar: "خبز",
      fr: "Pain",
      es: "Pan",
      uk: "Хліб",
    },
  },
  {
    question: "Garten",
    correctAnswer: "der",
    image: require("./images/garten.png"),
    englishName: "Garden",
    level: "A1",
    category: "Natur",
    translations: {
      ru: "Сад",
      tr: "Bahçe",
      ar: "حديقة",
      fr: "Jardin",
      es: "Jardín",
      uk: "Сад",
    },
  },
  {
    question: "Wald",
    correctAnswer: "der",
    image: require("./images/wald.png"),
    englishName: "Forest",
    level: "A1",
    category: "Natur",
    translations: {
      ru: "Лес",
      tr: "Orman",
      ar: "غابة",
      fr: "Forêt",
      es: "Bosque",
      uk: "Ліс",
    },
  },
  {
    question: "Himmel",
    correctAnswer: "der",
    image: require("./images/himmel.png"),
    englishName: "Sky",
    level: "A1",
    category: "Natur",
    translations: {
      ru: "Небо",
      tr: "Gökyüzü",
      ar: "سماء",
      fr: "Ciel",
      es: "Cielo",
      uk: "Небо",
    },
  },
  {
    question: "Maus",
    correctAnswer: "die",
    image: require("./images/maus.png"),
    englishName: "Mouse",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Мышь",
      tr: "Fare",
      ar: "فأر",
      fr: "Souris",
      es: "Ratón",
      uk: "Миша",
    },
  },
  {
    question: "Gesicht",
    correctAnswer: "das",
    image: require("./images/gesicht.png"),
    englishName: "Face",
    level: "A1",
    category: "Körper",
    translations: {
      ru: "Лицо",
      tr: "Yüz",
      ar: "وجه",
      fr: "Visage",
      es: "Cara",
      uk: "Обличчя",
    },
  },
  {
    question: "Brücke",
    correctAnswer: "die",
    image: require("./images/bruecke.png"),
    englishName: "Bridge",
    level: "A2",
    category: "Orte",
    translations: {
      ru: "Мост",
      tr: "Köprü",
      ar: "جسر",
      fr: "Pont",
      es: "Puente",
      uk: "Міст",
    },
  },
  {
    question: "Geld",
    correctAnswer: "das",
    image: require("./images/geld.png"),
    englishName: "Money",
    level: "A1",
    category: "Alltag",
    translations: {
      ru: "Деньги",
      tr: "Para",
      ar: "مال",
      fr: "Argent",
      es: "Dinero",
      uk: "Гроші",
    },
  },
  {
    question: "Auge",
    correctAnswer: "das",
    image: require("./images/auge.png"),
    englishName: "Eye",
    level: "A1",
    category: "Körper",
    translations: {
      ru: "Глаз",
      tr: "Göz",
      ar: "عين",
      fr: "Œil",
      es: "Ojo",
      uk: "Око",
    },
  },
  {
    question: "Hand",
    correctAnswer: "die",
    image: require("./images/hand.png"),
    englishName: "Hand",
    level: "A1",
    category: "Körper",
    translations: {
      ru: "Рука",
      tr: "El",
      ar: "يد",
      fr: "Main",
      es: "Mano",
      uk: "Рука",
    },
  },
  {
    question: "Stuhl",
    correctAnswer: "der",
    image: require("./images/stuhl.png"),
    englishName: "Chair",
    level: "A1",
    category: "Zuhause",
    translations: {
      ru: "Стул",
      tr: "Sandalye",
      ar: "كرسي",
      fr: "Chaise",
      es: "Silla",
      uk: "Стілець",
    },
  },
  {
    question: "Kühlschrank",
    correctAnswer: "der",
    image: require("./images/kuehlschrank.png"),
    englishName: "Refrigerator",
    level: "A2",
    category: "Zuhause",
    translations: {
      ru: "Холодильник",
      tr: "Buzdolabı",
      ar: "ثلاجة",
      fr: "Réfrigérateur",
      es: "Nevera",
      uk: "Холодильник",
    },
  },
  {
    question: "Uhr",
    correctAnswer: "die",
    image: require("./images/uhr.png"),
    englishName: "Clock",
    level: "A1",
    category: "Alltag",
    translations: {
      ru: "Часы",
      tr: "Saat",
      ar: "ساعة",
      fr: "Montre",
      es: "Reloj",
      uk: "Годинник",
    },
  },
  {
    question: "Fisch",
    correctAnswer: "der",
    image: require("./images/fisch.png"),
    englishName: "Fish",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Рыба",
      tr: "Balık",
      ar: "سمكة",
      fr: "Poisson",
      es: "Pez",
      uk: "Риба",
    },
  },
  {
    question: "Flugzeug",
    correctAnswer: "das",
    image: require("./images/flugzeug.png"),
    englishName: "Airplane",
    level: "A1",
    category: "Transport",
    translations: {
      ru: "Самолёт",
      tr: "Uçak",
      ar: "طائرة",
      fr: "Avion",
      es: "Avión",
      uk: "Літак",
    },
  },
  {
    question: "Geschenk",
    correctAnswer: "das",
    image: require("./images/geschenk.png"),
    englishName: "Gift",
    level: "A1",
    category: "Alltag",
    translations: {
      ru: "Подарок",
      tr: "Hediye",
      ar: "هدية",
      fr: "Cadeau",
      es: "Regalo",
      uk: "Подарунок",
    },
  },
  {
    question: "Laptop",
    correctAnswer: "der",
    image: require("./images/laptop.png"),
    englishName: "Laptop",
    level: "A2",
    category: "Technik",
    translations: {
      ru: "Ноутбук",
      tr: "Dizüstü bilgisayar",
      ar: "حاسوب محمول",
      fr: "Ordinateur portable",
      es: "Portátil",
      uk: "Ноутбук",
    },
  },
  {
    question: "Straße",
    correctAnswer: "die",
    image: require("./images/strasse.png"),
    englishName: "Street",
    level: "A1",
    category: "Orte",
    translations: {
      ru: "Улица",
      tr: "Sokak",
      ar: "شارع",
      fr: "Rue",
      es: "Calle",
      uk: "Вулиця",
    },
  },
  {
    question: "Zimmer",
    correctAnswer: "das",
    image: require("./images/zimmer.png"),
    englishName: "Room",
    level: "A1",
    category: "Zuhause",
    translations: {
      ru: "Комната",
      tr: "Oda",
      ar: "غرفة",
      fr: "Chambre",
      es: "Habitación",
      uk: "Кімната",
    },
  },
  {
    question: "Kleid",
    correctAnswer: "das",
    image: require("./images/kleid.png"),
    englishName: "Dress",
    level: "A1",
    category: "Kleidung",
    translations: {
      ru: "Платье",
      tr: "Elbise",
      ar: "فستان",
      fr: "Robe",
      es: "Vestido",
      uk: "Сукня",
    },
  },
  {
    question: "Hose",
    correctAnswer: "die",
    image: require("./images/hose.png"),
    englishName: "Pants",
    level: "A1",
    category: "Kleidung",
    translations: {
      ru: "Брюки",
      tr: "Pantolon",
      ar: "بنطلون",
      fr: "Pantalon",
      es: "Pantalón",
      uk: "Штани",
    },
  },
  {
    question: "Spielzeug",
    correctAnswer: "das",
    image: require("./images/spielzeug.png"),
    englishName: "Toy",
    level: "A1",
    category: "Alltag",
    translations: {
      ru: "Игрушка",
      tr: "Oyuncak",
      ar: "لعبة",
      fr: "Jouet",
      es: "Juguete",
      uk: "Іграшка",
    },
  },
  {
    question: "Berg",
    correctAnswer: "der",
    image: require("./images/berg.png"),
    englishName: "Mountain",
    level: "A1",
    category: "Natur",
    translations: {
      ru: "Гора",
      tr: "Dağ",
      ar: "جبل",
      fr: "Montagne",
      es: "Montaña",
      uk: "Гора",
    },
  },
  {
    question: "See",
    correctAnswer: "der",
    image: require("./images/see.png"),
    englishName: "Lake",
    level: "A2",
    category: "Natur",
    translations: {
      ru: "Озеро",
      tr: "Göl",
      ar: "بحيرة",
      fr: "Lac",
      es: "Lago",
      uk: "Озеро",
    },
  },
  {
    question: "Mond",
    correctAnswer: "der",
    image: require("./images/mond.png"),
    englishName: "Moon",
    level: "A1",
    category: "Natur",
    translations: {
      ru: "Луна",
      tr: "Ay",
      ar: "قمر",
      fr: "Lune",
      es: "Luna",
      uk: "Місяць",
    },
  },
  {
    question: "Tür",
    correctAnswer: "die",
    image: require("./images/tuer.png"),
    englishName: "Door",
    level: "A1",
    category: "Zuhause",
    translations: {
      ru: "Дверь",
      tr: "Kapı",
      ar: "باب",
      fr: "Porte",
      es: "Puerta",
      uk: "Двері",
    },
  },
  {
    question: "Zahn",
    correctAnswer: "der",
    image: require("./images/zahn.png"),
    englishName: "Tooth",
    level: "A1",
    category: "Körper",
    translations: {
      ru: "Зуб",
      tr: "Diş",
      ar: "سن",
      fr: "Dent",
      es: "Diente",
      uk: "Зуб",
    },
  },
  {
    question: "Wolke",
    correctAnswer: "die",
    image: require("./images/wolke.png"),
    englishName: "Cloud",
    level: "A1",
    category: "Natur",
    translations: {
      ru: "Облако",
      tr: "Bulut",
      ar: "سحابة",
      fr: "Nuage",
      es: "Nube",
      uk: "Хмара",
    },
  },
  {
    question: "Boden",
    correctAnswer: "der",
    image: require("./images/boden.png"),
    englishName: "Floor",
    level: "A1",
    category: "Zuhause",
    translations: {
      ru: "Пол",
      tr: "Zemin",
      ar: "أرضية",
      fr: "Sol",
      es: "Suelo",
      uk: "Підлога",
    },
  },
  {
    question: "Nase",
    correctAnswer: "die",
    image: require("./images/nase.png"),
    englishName: "Nose",
    level: "A1",
    category: "Körper",
    translations: {
      ru: "Нос",
      tr: "Burun",
      ar: "أنف",
      fr: "Nez",
      es: "Nariz",
      uk: "Ніс",
    },
  },
  {
    question: "Mütze",
    correctAnswer: "die",
    image: require("./images/muetze.png"),
    englishName: "Hat",
    level: "A1",
    category: "Kleidung",
    translations: {
      ru: "Шапка",
      tr: "Bere",
      ar: "قبعة",
      fr: "Bonnet",
      es: "Gorro",
      uk: "Шапка",
    },
  },
  {
    question: "Zunge",
    correctAnswer: "die",
    image: require("./images/zunge.png"),
    englishName: "Tongue",
    level: "A2",
    category: "Körper",
    translations: {
      ru: "Язык",
      tr: "Dil",
      ar: "لسان",
      fr: "Langue",
      es: "Lengua",
      uk: "Язик",
    },
  },
  {
    question: "Kamera",
    correctAnswer: "die",
    image: require("./images/kamera.png"),
    englishName: "Camera",
    level: "A2",
    category: "Technik",
    translations: {
      ru: "Камера",
      tr: "Kamera",
      ar: "كاميرا",
      fr: "Caméra",
      es: "Cámara",
      uk: "Камера",
    },
  },
  {
    question: "Gitarre",
    correctAnswer: "die",
    image: require("./images/gitarre.png"),
    englishName: "Guitar",
    level: "A2",
    category: "Musik",
    translations: {
      ru: "Гитара",
      tr: "Gitar",
      ar: "غيتار",
      fr: "Guitare",
      es: "Guitarra",
      uk: "Гітара",
    },
  },
  {
    question: "Musik",
    correctAnswer: "die",
    image: require("./images/musik.png"),
    englishName: "Music",
    level: "A1",
    category: "Musik",
    translations: {
      ru: "Музыка",
      tr: "Müzik",
      ar: "موسيقى",
      fr: "Musique",
      es: "Música",
      uk: "Музика",
    },
  },
  {
    question: "Blatt",
    correctAnswer: "das",
    image: require("./images/blatt.png"),
    englishName: "Leaf",
    level: "A1",
    category: "Natur",
    translations: {
      ru: "Лист",
      tr: "Yaprak",
      ar: "ورقة",
      fr: "Feuille",
      es: "Hoja",
      uk: "Листок",
    },
  },
  {
    question: "Sofa",
    correctAnswer: "das",
    image: require("./images/sofa.png"),
    englishName: "Sofa",
    level: "A1",
    category: "Zuhause",
    translations: {
      ru: "Диван",
      tr: "Kanepe",
      ar: "أريكة",
      fr: "Canapé",
      es: "Sofá",
      uk: "Диван",
    },
  },
  {
    question: "Glas",
    correctAnswer: "das",
    image: require("./images/glas.png"),
    englishName: "Glass",
    level: "A1",
    category: "Essen",
    translations: {
      ru: "Стакан",
      tr: "Bardak",
      ar: "كوب",
      fr: "Verre",
      es: "Vaso",
      uk: "Склянка",
    },
  },
  {
    question: "Zoo",
    correctAnswer: "der",
    image: require("./images/zoo.png"),
    englishName: "Zoo",
    level: "A1",
    category: "Orte",
    translations: {
      ru: "Зоопарк",
      tr: "Hayvanat bahçesi",
      ar: "حديقة حيوان",
      fr: "Zoo",
      es: "Zoológico",
      uk: "Зоопарк",
    },
  },
  {
    question: "Familie",
    correctAnswer: "die",
    image: require("./images/familie.png"),
    englishName: "Family",
    level: "A1",
    category: "Menschen",
    translations: {
      ru: "Семья",
      tr: "Aile",
      ar: "عائلة",
      fr: "Famille",
      es: "Familia",
      uk: "Сім'я",
    },
  },
  {
    question: "Tasche",
    correctAnswer: "die",
    image: require("./images/tasche.png"),
    englishName: "Bag",
    level: "A1",
    category: "Alltag",
    translations: {
      ru: "Сумка",
      tr: "Çanta",
      ar: "حقيبة",
      fr: "Sac",
      es: "Bolsa",
      uk: "Сумка",
    },
  },
  {
    question: "Dach",
    correctAnswer: "das",
    image: require("./images/dach.png"),
    englishName: "Roof",
    level: "A2",
    category: "Zuhause",
    translations: {
      ru: "Крыша",
      tr: "Çatı",
      ar: "سقف",
      fr: "Toit",
      es: "Tejado",
      uk: "Дах",
    },
  },
  {
    question: "Hemd",
    correctAnswer: "das",
    image: require("./images/hemd.png"),
    englishName: "Shirt",
    level: "A1",
    category: "Kleidung",
    translations: {
      ru: "Рубашка",
      tr: "Gömlek",
      ar: "قميص",
      fr: "Chemise",
      es: "Camisa",
      uk: "Сорочка",
    },
  },
  {
    question: "Park",
    correctAnswer: "der",
    image: require("./images/park.png"),
    englishName: "Park",
    level: "A1",
    category: "Orte",
    translations: {
      ru: "Парк",
      tr: "Park",
      ar: "حديقة عامة",
      fr: "Parc",
      es: "Parque",
      uk: "Парк",
    },
  },
  {
    question: "Bahn",
    correctAnswer: "die",
    image: require("./images/bahn.png"),
    englishName: "Train",
    level: "A1",
    category: "Transport",
    translations: {
      ru: "Поезд",
      tr: "Tren",
      ar: "قطار",
      fr: "Train",
      es: "Tren",
      uk: "Поїзд",
    },
  },
  {
    question: "Brille",
    correctAnswer: "die",
    image: require("./images/brille.png"),
    englishName: "Glasses",
    level: "A1",
    category: "Alltag",
    translations: {
      ru: "Очки",
      tr: "Gözlük",
      ar: "نظارة",
      fr: "Lunettes",
      es: "Gafas",
      uk: "Окуляри",
    },
  },
  {
    question: "Schnee",
    correctAnswer: "der",
    image: require("./images/schnee.png"),
    englishName: "Snow",
    level: "A1",
    category: "Natur",
    translations: {
      ru: "Снег",
      tr: "Kar",
      ar: "ثلج",
      fr: "Neige",
      es: "Nieve",
      uk: "Сніг",
    },
  },
  {
    question: "Treppe",
    correctAnswer: "die",
    image: require("./images/treppe.png"),
    englishName: "Stairs",
    level: "A2",
    category: "Zuhause",
    translations: {
      ru: "Лестница",
      tr: "Merdiven",
      ar: "درج",
      fr: "Escalier",
      es: "Escaleras",
      uk: "Сходи",
    },
  },
  {
    question: "Küche",
    correctAnswer: "die",
    image: require("./images/kueche.png"),
    englishName: "Kitchen",
    level: "A1",
    category: "Zuhause",
    translations: {
      ru: "Кухня",
      tr: "Mutfak",
      ar: "مطبخ",
      fr: "Cuisine",
      es: "Cocina",
      uk: "Кухня",
    },
  },
  {
    question: "Fluss",
    correctAnswer: "der",
    image: require("./images/fluss.png"),
    englishName: "River",
    level: "A1",
    category: "Natur",
    translations: {
      ru: "Река",
      tr: "Nehir",
      ar: "نهر",
      fr: "Rivière",
      es: "Río",
      uk: "Річка",
    },
  },
  {
    question: "Ei",
    correctAnswer: "das",
    image: require("./images/ei.png"),
    englishName: "Egg",
    level: "A1",
    category: "Essen",
    translations: {
      ru: "Яйцо",
      tr: "Yumurta",
      ar: "بيضة",
      fr: "Œuf",
      es: "Huevo",
      uk: "Яйце",
    },
  },
  {
    question: "Lehrer",
    correctAnswer: "der",
    image: require("./images/lehrer.png"),
    englishName: "Teacher (male)",
    level: "A1",
    category: "Berufe",
    translations: {
      ru: "Учитель",
      tr: "Öğretmen",
      ar: "معلم",
      fr: "Professeur",
      es: "Profesor",
      uk: "Вчитель",
    },
  },
  {
    question: "Lehrerin",
    correctAnswer: "die",
    image: require("./images/lehrerin.png"),
    englishName: "Teacher (female)",
    level: "A1",
    category: "Berufe",
    translations: {
      ru: "Учительница",
      tr: "Öğretmen",
      ar: "معلمة",
      fr: "Professeure",
      es: "Profesora",
      uk: "Вчителька",
    },
  },
  {
    question: "Tafel",
    correctAnswer: "die",
    image: require("./images/tafel.png"),
    englishName: "Blackboard",
    level: "A1",
    category: "Schule",
    translations: {
      ru: "Доска",
      tr: "Tahta",
      ar: "سبورة",
      fr: "Tableau",
      es: "Pizarra",
      uk: "Дошка",
    },
  },
  {
    question: "Feder",
    correctAnswer: "die",
    image: require("./images/feder.png"),
    englishName: "Feather",
    level: "A2",
    category: "Natur",
    translations: {
      ru: "Перо",
      tr: "Tüy",
      ar: "ريشة",
      fr: "Plume",
      es: "Pluma",
      uk: "Перо",
    },
  },
  {
    question: "Schlüssel",
    correctAnswer: "der",
    image: require("./images/schluessel.png"),
    englishName: "Key",
    level: "A1",
    category: "Alltag",
    translations: {
      ru: "Ключ",
      tr: "Anahtar",
      ar: "مفتاح",
      fr: "Clé",
      es: "Llave",
      uk: "Ключ",
    },
  },
  {
    question: "Spiegel",
    correctAnswer: "der",
    image: require("./images/spiegel.png"),
    englishName: "Mirror",
    level: "A1",
    category: "Zuhause",
    translations: {
      ru: "Зеркало",
      tr: "Ayna",
      ar: "مرآة",
      fr: "Miroir",
      es: "Espejo",
      uk: "Дзеркало",
    },
  },
  {
    question: "Hut",
    correctAnswer: "der",
    image: require("./images/hut.png"),
    englishName: "Hat",
    level: "A1",
    category: "Kleidung",
    translations: {
      ru: "Шляпа",
      tr: "Şapka",
      ar: "قبعة",
      fr: "Chapeau",
      es: "Sombrero",
      uk: "Капелюх",
    },
  },
  {
    question: "Kuchen",
    correctAnswer: "der",
    image: require("./images/kuchen.png"),
    englishName: "Cake",
    level: "A1",
    category: "Essen",
    translations: {
      ru: "Торт",
      tr: "Pasta",
      ar: "كعكة",
      fr: "Gâteau",
      es: "Pastel",
      uk: "Торт",
    },
  },
  {
    question: "Schlange",
    correctAnswer: "die",
    image: require("./images/schlange.png"),
    englishName: "Snake",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Змея",
      tr: "Yılan",
      ar: "ثعبان",
      fr: "Serpent",
      es: "Serpiente",
      uk: "Змія",
    },
  },
  {
    question: "Schuh",
    correctAnswer: "der",
    image: require("./images/schuh.png"),
    englishName: "Shoe",
    level: "A1",
    category: "Kleidung",
    translations: {
      ru: "Ботинок",
      tr: "Ayakkabı",
      ar: "حذاء",
      fr: "Chaussure",
      es: "Zapato",
      uk: "Черевик",
    },
  },
  {
    question: "Fahrrad",
    correctAnswer: "das",
    image: require("./images/fahrrad.png"),
    englishName: "Bicycle",
    level: "A1",
    category: "Transport",
    translations: {
      ru: "Велосипед",
      tr: "Bisiklet",
      ar: "دراجة",
      fr: "Vélo",
      es: "Bicicleta",
      uk: "Велосипед",
    },
  },
  {
    question: "Messer",
    correctAnswer: "das",
    image: require("./images/messer.png"),
    englishName: "Knife",
    level: "A1",
    category: "Essen",
    translations: {
      ru: "Нож",
      tr: "Bıçak",
      ar: "سكين",
      fr: "Couteau",
      es: "Cuchillo",
      uk: "Ніж",
    },
  },
  {
    question: "Schal",
    correctAnswer: "der",
    image: require("./images/schal.png"),
    englishName: "Scarf",
    level: "A1",
    category: "Kleidung",
    translations: {
      ru: "Шарф",
      tr: "Atkı",
      ar: "وشاح",
      fr: "Écharpe",
      es: "Bufanda",
      uk: "Шарф",
    },
  },
  {
    question: "Handschuh",
    correctAnswer: "der",
    image: require("./images/handschuh.png"),
    englishName: "Glove",
    level: "A1",
    category: "Kleidung",
    translations: {
      ru: "Перчатка",
      tr: "Eldiven",
      ar: "قفاز",
      fr: "Gant",
      es: "Guante",
      uk: "Рукавичка",
    },
  },
  {
    question: "Papier",
    correctAnswer: "das",
    image: require("./images/papier.png"),
    englishName: "Paper",
    level: "A1",
    category: "Schule",
    translations: {
      ru: "Бумага",
      tr: "Kağıt",
      ar: "ورق",
      fr: "Papier",
      es: "Papel",
      uk: "Папір",
    },
  },
  {
    question: "Brief",
    correctAnswer: "der",
    image: require("./images/brief.png"),
    englishName: "Letter",
    level: "A1",
    category: "Alltag",
    translations: {
      ru: "Письмо",
      tr: "Mektup",
      ar: "رسالة",
      fr: "Lettre",
      es: "Carta",
      uk: "Лист",
    },
  },
  {
    question: "Schlafzimmer",
    correctAnswer: "das",
    image: require("./images/schlafzimmer.png"),
    englishName: "Bedroom",
    level: "A1",
    category: "Zuhause",
    translations: {
      ru: "Спальня",
      tr: "Yatak odası",
      ar: "غرفة نوم",
      fr: "Chambre à coucher",
      es: "Dormitorio",
      uk: "Спальня",
    },
  },
  {
    question: "Handy",
    correctAnswer: "das",
    image: require("./images/handy.png"),
    englishName: "Mobile Phone",
    level: "A1",
    category: "Technik",
    translations: {
      ru: "Мобильный телефон",
      tr: "Cep telefonu",
      ar: "هاتف محمول",
      fr: "Téléphone portable",
      es: "Móvil",
      uk: "Мобільний телефон",
    },
  },
  {
    question: "Keller",
    correctAnswer: "der",
    image: require("./images/keller.png"),
    englishName: "Basement",
    level: "A2",
    category: "Zuhause",
    translations: {
      ru: "Подвал",
      tr: "Bodrum",
      ar: "قبو",
      fr: "Cave",
      es: "Sótano",
      uk: "Підвал",
    },
  },
  {
    question: "Müll",
    correctAnswer: "der",
    image: require("./images/muell.png"),
    englishName: "Trash",
    level: "A1",
    category: "Alltag",
    translations: {
      ru: "Мусор",
      tr: "Çöp",
      ar: "قمامة",
      fr: "Ordures",
      es: "Basura",
      uk: "Сміття",
    },
  },
  {
    question: "Mauer",
    correctAnswer: "die",
    image: require("./images/mauer.png"),
    englishName: "Wall",
    level: "A2",
    category: "Orte",
    translations: {
      ru: "Стена",
      tr: "Duvar",
      ar: "جدار",
      fr: "Mur",
      es: "Muro",
      uk: "Стіна",
    },
  },
  {
    question: "Eule",
    correctAnswer: "die",
    image: require("./images/eule.png"),
    englishName: "Owl",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Сова",
      tr: "Baykuş",
      ar: "بومة",
      fr: "Hibou",
      es: "Búho",
      uk: "Сова",
    },
  },
  {
    question: "Bahnsteig",
    correctAnswer: "der",
    image: require("./images/bahnsteig.png"),
    englishName: "Platform",
    level: "A2",
    category: "Transport",
    translations: {
      ru: "Платформа",
      tr: "Peron",
      ar: "رصيف",
      fr: "Quai",
      es: "Andén",
      uk: "Перон",
    },
  },
  {
    question: "Bier",
    correctAnswer: "das",
    image: require("./images/bier.png"),
    englishName: "Beer",
    level: "A1",
    category: "Essen",
    translations: {
      ru: "Пиво",
      tr: "Bira",
      ar: "بيرة",
      fr: "Bière",
      es: "Cerveza",
      uk: "Пиво",
    },
  },
  {
    question: "Stift",
    correctAnswer: "der",
    image: require("./images/stift.png"),
    englishName: "Pen",
    level: "A1",
    category: "Schule",
    translations: {
      ru: "Ручка",
      tr: "Kalem",
      ar: "قلم",
      fr: "Stylo",
      es: "Bolígrafo",
      uk: "Ручка",
    },
  },
  {
    question: "Löffel",
    correctAnswer: "der",
    image: require("./images/loeffel.png"),
    englishName: "Spoon",
    level: "A1",
    category: "Essen",
    translations: {
      ru: "Ложка",
      tr: "Kaşık",
      ar: "ملعقة",
      fr: "Cuillère",
      es: "Cuchara",
      uk: "Ложка",
    },
  },
  {
    question: "Schere",
    correctAnswer: "die",
    image: require("./images/schere.png"),
    englishName: "Scissors",
    level: "A1",
    category: "Alltag",
    translations: {
      ru: "Ножницы",
      tr: "Makas",
      ar: "مقص",
      fr: "Ciseaux",
      es: "Tijeras",
      uk: "Ножиці",
    },
  },
  {
    question: "Kissen",
    correctAnswer: "das",
    image: require("./images/kissen.png"),
    englishName: "Pillow",
    level: "A1",
    category: "Zuhause",
    translations: {
      ru: "Подушка",
      tr: "Yastık",
      ar: "وسادة",
      fr: "Oreiller",
      es: "Almohada",
      uk: "Подушка",
    },
  },
  {
    question: "Regen",
    correctAnswer: "der",
    image: require("./images/regen.png"),
    englishName: "Rain",
    level: "A1",
    category: "Natur",
    translations: {
      ru: "Дождь",
      tr: "Yağmur",
      ar: "مطر",
      fr: "Pluie",
      es: "Lluvia",
      uk: "Дощ",
    },
  },
  {
    question: "Papiere",
    correctAnswer: "die",
    image: require("./images/papiere.png"),
    englishName: "Papers",
    level: "A2",
    category: "Alltag",
    translations: {
      ru: "Документы",
      tr: "Belgeler",
      ar: "أوراق",
      fr: "Papiers",
      es: "Papeles",
      uk: "Документи",
    },
  },
  {
    question: "Schuhe",
    correctAnswer: "die",
    image: require("./images/schuhe.png"),
    englishName: "Shoes",
    level: "A1",
    category: "Kleidung",
    translations: {
      ru: "Обувь",
      tr: "Ayakkabılar",
      ar: "أحذية",
      fr: "Chaussures",
      es: "Zapatos",
      uk: "Взуття",
    },
  },
  {
    question: "Pferd",
    correctAnswer: "das",
    image: require("./images/pferd.png"),
    englishName: "Horse",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Лошадь",
      tr: "At",
      ar: "حصان",
      fr: "Cheval",
      es: "Caballo",
      uk: "Кінь",
    },
  },
  {
    question: "Kuh",
    correctAnswer: "die",
    image: require("./images/kuh.png"),
    englishName: "Cow",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Корова",
      tr: "İnek",
      ar: "بقرة",
      fr: "Vache",
      es: "Vaca",
      uk: "Корова",
    },
  },
  {
    question: "Huhn",
    correctAnswer: "das",
    image: require("./images/huhn.png"),
    englishName: "Chicken",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Курица",
      tr: "Tavuk",
      ar: "دجاجة",
      fr: "Poulet",
      es: "Pollo",
      uk: "Курка",
    },
  },
  {
    question: "Hahn",
    correctAnswer: "der",
    image: require("./images/hahn.png"),
    englishName: "Rooster",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Петух",
      tr: "Horoz",
      ar: "ديك",
      fr: "Coq",
      es: "Gallo",
      uk: "Півень",
    },
  },
  {
    question: "Schaf",
    correctAnswer: "das",
    image: require("./images/schaf.png"),
    englishName: "Sheep",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Овца",
      tr: "Koyun",
      ar: "خروف",
      fr: "Mouton",
      es: "Oveja",
      uk: "Вівця",
    },
  },
  {
    question: "Ziege",
    correctAnswer: "die",
    image: require("./images/ziege.png"),
    englishName: "Goat",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Коза",
      tr: "Keçi",
      ar: "ماعز",
      fr: "Chèvre",
      es: "Cabra",
      uk: "Коза",
    },
  },
  {
    question: "Ente",
    correctAnswer: "die",
    image: require("./images/ente.png"),
    englishName: "Duck",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Утка",
      tr: "Ördek",
      ar: "بطة",
      fr: "Canard",
      es: "Pato",
      uk: "Качка",
    },
  },
  {
    question: "Hase",
    correctAnswer: "der",
    image: require("./images/hase.png"),
    englishName: "Hare",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Заяц",
      tr: "Tavşan",
      ar: "أرنب",
      fr: "Lièvre",
      es: "Liebre",
      uk: "Заєць",
    },
  },
  {
    question: "Fuchs",
    correctAnswer: "der",
    image: require("./images/fuchs.png"),
    englishName: "Fox",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Лиса",
      tr: "Tilki",
      ar: "ثعلب",
      fr: "Renard",
      es: "Zorro",
      uk: "Лисиця",
    },
  },
  {
    question: "Wolf",
    correctAnswer: "der",
    image: require("./images/wolf.png"),
    englishName: "Wolf",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Волк",
      tr: "Kurt",
      ar: "ذئب",
      fr: "Loup",
      es: "Lobo",
      uk: "Вовк",
    },
  },
  {
    question: "Bär",
    correctAnswer: "der",
    image: require("./images/baer.png"),
    englishName: "Bear",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Медведь",
      tr: "Ayı",
      ar: "دب",
      fr: "Ours",
      es: "Oso",
      uk: "Ведмідь",
    },
  },
  {
    question: "Eichhörnchen",
    correctAnswer: "das",
    image: require("./images/eichhoernchen.png"),
    englishName: "Squirrel",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Белка",
      tr: "Sincap",
      ar: "سنجاب",
      fr: "Écureuil",
      es: "Ardilla",
      uk: "Білка",
    },
  },
  {
    question: "Igel",
    correctAnswer: "der",
    image: require("./images/igel.png"),
    englishName: "Hedgehog",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Ёж",
      tr: "Kirpi",
      ar: "قنفذ",
      fr: "Hérisson",
      es: "Erizo",
      uk: "Їжак",
    },
  },
  {
    question: "Elefant",
    correctAnswer: "der",
    image: require("./images/elefant.png"),
    englishName: "Elephant",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Слон",
      tr: "Fil",
      ar: "فيل",
      fr: "Éléphant",
      es: "Elefante",
      uk: "Слон",
    },
  },
  {
    question: "Löwe",
    correctAnswer: "der",
    image: require("./images/loewe.png"),
    englishName: "Lion",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Лев",
      tr: "Aslan",
      ar: "أسد",
      fr: "Lion",
      es: "León",
      uk: "Лев",
    },
  },
  {
    question: "Tiger",
    correctAnswer: "der",
    image: require("./images/tiger.png"),
    englishName: "Tiger",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Тигр",
      tr: "Kaplan",
      ar: "نمر",
      fr: "Tigre",
      es: "Tigre",
      uk: "Тигр",
    },
  },
  {
    question: "Affe",
    correctAnswer: "der",
    image: require("./images/affe.png"),
    englishName: "Monkey",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Обезьяна",
      tr: "Maymun",
      ar: "قرد",
      fr: "Singe",
      es: "Mono",
      uk: "Мавпа",
    },
  },
  {
    question: "Giraffe",
    correctAnswer: "die",
    image: require("./images/giraffe.png"),
    englishName: "Giraffe",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Жираф",
      tr: "Zürafa",
      ar: "زرافة",
      fr: "Girafe",
      es: "Jirafa",
      uk: "Жираф",
    },
  },
  {
    question: "Zebra",
    correctAnswer: "das",
    image: require("./images/zebra.png"),
    englishName: "Zebra",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Зебра",
      tr: "Zebra",
      ar: "حمار وحشي",
      fr: "Zèbre",
      es: "Cebra",
      uk: "Зебра",
    },
  },
  {
    question: "Pinguin",
    correctAnswer: "der",
    image: require("./images/pinguin.png"),
    englishName: "Penguin",
    level: "A1",
    category: "Tiere",
    translations: {
      ru: "Пингвин",
      tr: "Penguen",
      ar: "بطريق",
      fr: "Pingouin",
      es: "Pingüino",
      uk: "Пінгвін",
    },
  },
  {
    question: "Kamel",
    correctAnswer: "das",
    image: require("./images/kamel.png"),
    englishName: "Camel",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Верблюд",
      tr: "Deve",
      ar: "جمل",
      fr: "Chameau",
      es: "Camello",
      uk: "Верблюд",
    },
  },
  {
    question: "Biene",
    correctAnswer: "die",
    image: require("./images/biene.png"),
    englishName: "Bee",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Пчела",
      tr: "Arı",
      ar: "نحلة",
      fr: "Abeille",
      es: "Abeja",
      uk: "Бджола",
    },
  },
  {
    question: "Schmetterling",
    correctAnswer: "der",
    image: require("./images/schmetterling.png"),
    englishName: "Butterfly",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Бабочка",
      tr: "Kelebek",
      ar: "فراشة",
      fr: "Papillon",
      es: "Mariposa",
      uk: "Метелик",
    },
  },
  {
    question: "Frosch",
    correctAnswer: "der",
    image: require("./images/frosch.png"),
    englishName: "Frog",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Лягушка",
      tr: "Kurbağa",
      ar: "ضفدع",
      fr: "Grenouille",
      es: "Rana",
      uk: "Жаба",
    },
  },
  {
    question: "Krokodil",
    correctAnswer: "das",
    image: require("./images/krokodil.png"),
    englishName: "Crocodile",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Крокодил",
      tr: "Timsah",
      ar: "تمساح",
      fr: "Crocodile",
      es: "Cocodrilo",
      uk: "Крокодил",
    },
  },
  {
    question: "Esel",
    correctAnswer: "der",
    image: require("./images/esel.png"),
    englishName: "Donkey",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Осёл",
      tr: "Eşek",
      ar: "حمار",
      fr: "Âne",
      es: "Burro",
      uk: "Осел",
    },
  },
  {
    question: "Papagei",
    correctAnswer: "der",
    image: require("./images/papagei.png"),
    englishName: "Parrot",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Попугай",
      tr: "Papağan",
      ar: "ببغاء",
      fr: "Perroquet",
      es: "Loro",
      uk: "Папуга",
    },
  },
  {
    question: "Känguru",
    correctAnswer: "das",
    image: require("./images/kaenguru.png"),
    englishName: "Kangaroo",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Кенгуру",
      tr: "Kanguru",
      ar: "كنغر",
      fr: "Kangourou",
      es: "Canguro",
      uk: "Кенгуру",
    },
  },
  {
    question: "Koala",
    correctAnswer: "der",
    image: require("./images/koala.png"),
    englishName: "Koala",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Коала",
      tr: "Koala",
      ar: "كوالا",
      fr: "Koala",
      es: "Koala",
      uk: "Коала",
    },
  },
  {
    question: "Delphin",
    correctAnswer: "der",
    image: require("./images/delphin.png"),
    englishName: "Dolphin",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Дельфин",
      tr: "Yunus",
      ar: "دلفين",
      fr: "Dauphin",
      es: "Delfín",
      uk: "Дельфін",
    },
  },
  {
    question: "Wal",
    correctAnswer: "der",
    image: require("./images/wal.png"),
    englishName: "Whale",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Кит",
      tr: "Balina",
      ar: "حوت",
      fr: "Baleine",
      es: "Ballena",
      uk: "Кит",
    },
  },
  {
    question: "Krabbe",
    correctAnswer: "die",
    image: require("./images/krabbe.png"),
    englishName: "Crab",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Краб",
      tr: "Yengeç",
      ar: "سرطان البحر",
      fr: "Crabe",
      es: "Cangrejo",
      uk: "Краб",
    },
  },
  {
    question: "Schildkröte",
    correctAnswer: "die",
    image: require("./images/schildkroete.png"),
    englishName: "Turtle",
    level: "A2",
    category: "Tiere",
    translations: {
      ru: "Черепаха",
      tr: "Kaplumbağa",
      ar: "سلحفاة",
      fr: "Tortue",
      es: "Tortuga",
      uk: "Черепаха",
    },
  },
  {
    question: "Arzt",
    correctAnswer: "der",
    image: require("./images/arzt.png"),
    englishName: "Doctor (male)",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Врач",
      tr: "Doktor",
      ar: "طبيب",
      fr: "Médecin",
      es: "Médico",
      uk: "Лікар",
    },
  },
  {
    question: "Ärztin",
    correctAnswer: "die",
    image: require("./images/aerztin.png"),
    englishName: "Doctor (female)",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Врач (жен.)",
      tr: "Kadın Doktor",
      ar: "طبيبة",
      fr: "Médecin (f)",
      es: "Médica",
      uk: "Лікарка",
    },
  },
  {
    question: "Kellner",
    correctAnswer: "der",
    image: require("./images/kellner.png"),
    englishName: "Waiter",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Официант",
      tr: "Garson",
      ar: "نادل",
      fr: "Serveur",
      es: "Camarero",
      uk: "Офіціант",
    },
  },
  {
    question: "Kellnerin",
    correctAnswer: "die",
    image: require("./images/kellnerin.png"),
    englishName: "Waitress",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Официантка",
      tr: "Garson (kadın)",
      ar: "نادلة",
      fr: "Serveuse",
      es: "Camarera",
      uk: "Офіціантка",
    },
  },
  {
    question: "Polizist",
    correctAnswer: "der",
    image: require("./images/polizist.png"),
    englishName: "Police Officer (male)",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Полицейский",
      tr: "Polis",
      ar: "شرطي",
      fr: "Policier",
      es: "Policía",
      uk: "Поліцейський",
    },
  },
  {
    question: "Polizistin",
    correctAnswer: "die",
    image: require("./images/polizistin.png"),
    englishName: "Police Officer (female)",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Полицейская",
      tr: "Kadın Polis",
      ar: "شرطية",
      fr: "Policière",
      es: "Policía (f)",
      uk: "Поліцейська",
    },
  },
  {
    question: "Verkäufer",
    correctAnswer: "der",
    image: require("./images/verkaeufer.png"),
    englishName: "Salesman",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Продавец",
      tr: "Satıcı",
      ar: "بائع",
      fr: "Vendeur",
      es: "Vendedor",
      uk: "Продавець",
    },
  },
  {
    question: "Verkäuferin",
    correctAnswer: "die",
    image: require("./images/verkaeuferin.png"),
    englishName: "Saleswoman",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Продавщица",
      tr: "Satıcı (kadın)",
      ar: "بائعة",
      fr: "Vendeuse",
      es: "Vendedora",
      uk: "Продавщиця",
    },
  },
  {
    question: "Ingenieur",
    correctAnswer: "der",
    image: require("./images/ingenieur.png"),
    englishName: "Engineer (male)",
    level: "B1",
    category: "Berufe",
    translations: {
      ru: "Инженер",
      tr: "Mühendis",
      ar: "مهندس",
      fr: "Ingénieur",
      es: "Ingeniero",
      uk: "Інженер",
    },
  },
  {
    question: "Ingenieurin",
    correctAnswer: "die",
    image: require("./images/ingenieurin.png"),
    englishName: "Engineer (female)",
    level: "B1",
    category: "Berufe",
    translations: {
      ru: "Инженер (жен.)",
      tr: "Mühendis (kadın)",
      ar: "مهندسة",
      fr: "Ingénieure",
      es: "Ingeniera",
      uk: "Інженерка",
    },
  },
  {
    question: "Koch",
    correctAnswer: "der",
    image: require("./images/koch.png"),
    englishName: "Cook (male)",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Повар",
      tr: "Aşçı",
      ar: "طاهٍ",
      fr: "Cuisinier",
      es: "Cocinero",
      uk: "Кухар",
    },
  },
  {
    question: "Köchin",
    correctAnswer: "die",
    image: require("./images/koechin.png"),
    englishName: "Cook (female)",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Повариха",
      tr: "Aşçı (kadın)",
      ar: "طاهية",
      fr: "Cuisinière",
      es: "Cocinera",
      uk: "Кухарка",
    },
  },
  {
    question: "Bäcker",
    correctAnswer: "der",
    image: require("./images/baecker.png"),
    englishName: "Baker (male)",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Пекарь",
      tr: "Fırıncı",
      ar: "خباز",
      fr: "Boulanger",
      es: "Panadero",
      uk: "Пекар",
    },
  },
  {
    question: "Bäckerin",
    correctAnswer: "die",
    image: require("./images/baeckerin.png"),
    englishName: "Baker (female)",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Пекарь (жен.)",
      tr: "Fırıncı (kadın)",
      ar: "خبازة",
      fr: "Boulangère",
      es: "Panadera",
      uk: "Пекарка",
    },
  },
  {
    question: "Friseurin",
    correctAnswer: "die",
    image: require("./images/friseurin.png"),
    englishName: "Hairdresser (female)",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Парикмахер",
      tr: "Kuaför",
      ar: "مصففة شعر",
      fr: "Coiffeuse",
      es: "Peluquera",
      uk: "Перукарка",
    },
  },
  {
    question: "Mechaniker",
    correctAnswer: "der",
    image: require("./images/mechaniker.png"),
    englishName: "Mechanic (male)",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Механик",
      tr: "Mekanik",
      ar: "ميكانيكي",
      fr: "Mécanicien",
      es: "Mecánico",
      uk: "Механік",
    },
  },
  {
    question: "Künstlerin",
    correctAnswer: "die",
    image: require("./images/kuenstlerin.png"),
    englishName: "Artist (female)",
    level: "B1",
    category: "Berufe",
    translations: {
      ru: "Художница",
      tr: "Sanatçı (kadın)",
      ar: "فنانة",
      fr: "Artiste",
      es: "Artista",
      uk: "Художниця",
    },
  },
  {
    question: "Architekt",
    correctAnswer: "der",
    image: require("./images/architekt.png"),
    englishName: "Architect (male)",
    level: "B1",
    category: "Berufe",
    translations: {
      ru: "Архитектор",
      tr: "Mimar",
      ar: "مهندس معماري",
      fr: "Architecte",
      es: "Arquitecto",
      uk: "Архітектор",
    },
  },
  {
    question: "Schüler",
    correctAnswer: "der",
    image: require("./images/schueler.png"),
    englishName: "Student male school",
    level: "A1",
    category: "Schule",
    translations: {
      ru: "Ученик",
      tr: "Öğrenci",
      ar: "تلميذ",
      fr: "Élève",
      es: "Alumno",
      uk: "Учень",
    },
  },
  {
    question: "Schülerin",
    correctAnswer: "die",
    image: require("./images/schuelerin.png"),
    englishName: "Student female school",
    level: "A1",
    category: "Schule",
    translations: {
      ru: "Ученица",
      tr: "Öğrenci (kız)",
      ar: "تلميذة",
      fr: "Élève (f)",
      es: "Alumna",
      uk: "Учениця",
    },
  },
  {
    question: "Student",
    correctAnswer: "der",
    image: require("./images/student.png"),
    englishName: "University Student male",
    level: "A2",
    category: "Schule",
    translations: {
      ru: "Студент",
      tr: "Üniversite öğrencisi",
      ar: "طالب جامعي",
      fr: "Étudiant",
      es: "Estudiante",
      uk: "Студент",
    },
  },
  {
    question: "Studentin",
    correctAnswer: "die",
    image: require("./images/studentin.png"),
    englishName: "University Student female",
    level: "A2",
    category: "Schule",
    translations: {
      ru: "Студентка",
      tr: "Üniversite öğrencisi (kız)",
      ar: "طالبة جامعية",
      fr: "Étudiante",
      es: "Estudiante (f)",
      uk: "Студентка",
    },
  },
  {
    question: "Krankenschwester",
    correctAnswer: "die",
    image: require("./images/krankenschwester.png"),
    englishName: "Nurse female",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Медсестра",
      tr: "Hemşire",
      ar: "ممرضة",
      fr: "Infirmière",
      es: "Enfermera",
      uk: "Медсестра",
    },
  },
  {
    question: "Krankenpflegerin",
    correctAnswer: "die",
    image: require("./images/krankenpflegerin.png"),
    englishName: "Home Nurse female",
    level: "B1",
    category: "Berufe",
    translations: {
      ru: "Медсестра по уходу",
      tr: "Bakıcı hemşire",
      ar: "ممرضة منزلية",
      fr: "Aide-soignante",
      es: "Enfermera a domicilio",
      uk: "Доглядальниця",
    },
  },
  {
    question: "Bauer",
    correctAnswer: "der",
    image: require("./images/bauer.png"),
    englishName: "Farmer male",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Фермер",
      tr: "Çiftçi",
      ar: "مزارع",
      fr: "Agriculteur",
      es: "Agricultor",
      uk: "Фермер",
    },
  },
  {
    question: "Bäuerin",
    correctAnswer: "die",
    image: require("./images/baeuerin.png"),
    englishName: "Farmer female",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Фермерша",
      tr: "Çiftçi (kadın)",
      ar: "مزارعة",
      fr: "Agricultrice",
      es: "Agricultora",
      uk: "Фермерка",
    },
  },
  {
    question: "Pilot",
    correctAnswer: "der",
    image: require("./images/pilot.png"),
    englishName: "Pilot male",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Пилот",
      tr: "Pilot",
      ar: "طيار",
      fr: "Pilote",
      es: "Piloto",
      uk: "Пілот",
    },
  },
  {
    question: "Sekretärin",
    correctAnswer: "die",
    image: require("./images/sekretaerin.png"),
    englishName: "Secretary female",
    level: "B1",
    category: "Berufe",
    translations: {
      ru: "Секретарь",
      tr: "Sekreter",
      ar: "سكرتيرة",
      fr: "Secrétaire",
      es: "Secretaria",
      uk: "Секретарка",
    },
  },
  {
    question: "Journalistin",
    correctAnswer: "die",
    image: require("./images/journalistin.png"),
    englishName: "Journalist female",
    level: "B1",
    category: "Berufe",
    translations: {
      ru: "Журналистка",
      tr: "Gazeteci (kadın)",
      ar: "صحفية",
      fr: "Journaliste",
      es: "Periodista",
      uk: "Журналістка",
    },
  },
  {
    question: "Musiker",
    correctAnswer: "der",
    image: require("./images/musiker.png"),
    englishName: "Musician male",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Музыкант",
      tr: "Müzisyen",
      ar: "موسيقي",
      fr: "Musicien",
      es: "Músico",
      uk: "Музикант",
    },
  },
  {
    question: "Busfahrer",
    correctAnswer: "der",
    image: require("./images/busfahrer.png"),
    englishName: "Bus Driver male",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Водитель автобуса",
      tr: "Otobüs şoförü",
      ar: "سائق حافلة",
      fr: "Chauffeur de bus",
      es: "Conductor de autobús",
      uk: "Водій автобуса",
    },
  },
  {
    question: "Feuerwehrmann",
    correctAnswer: "der",
    image: require("./images/feuerwehrmann.png"),
    englishName: "Firefighter male",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Пожарный",
      tr: "İtfaiyeci",
      ar: "رجل الإطفاء",
      fr: "Pompier",
      es: "Bombero",
      uk: "Пожежник",
    },
  },
  {
    question: "Postbote",
    correctAnswer: "der",
    image: require("./images/postbote.png"),
    englishName: "Mail Carrier male",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Почтальон",
      tr: "Postacı",
      ar: "ساعي بريد",
      fr: "Facteur",
      es: "Cartero",
      uk: "Листоноша",
    },
  },
  {
    question: "Fotograf",
    correctAnswer: "der",
    image: require("./images/fotograf.png"),
    englishName: "Photographer male",
    level: "A2",
    category: "Berufe",
    translations: {
      ru: "Фотограф",
      tr: "Fotoğrafçı",
      ar: "مصور",
      fr: "Photographe",
      es: "Fotógrafo",
      uk: "Фотограф",
    },
  },
];

export const quizWordSentence = [
  {
    question: "Vogel",
    correctAnswer: "der",
    image: require("./images/vogel.png"),
    englishName: "Bird",
    germanSentence: "Der Vogel singt im Baum.",
    englishSentence: "The bird is singing in the tree.",
  },
  {
    question: "Auto",
    correctAnswer: "das",
    image: require("./images/auto.png"),
    englishName: "Car",
    germanSentence: "Das Auto fährt schnell.",
    englishSentence: "The car is driving fast.",
  },
  {
    question: "Tisch",
    correctAnswer: "der",
    image: require("./images/tisch.png"),
    englishName: "Table",
    germanSentence: "Der Tisch ist aus Holz.",
    englishSentence: "The table is made of wood.",
  },
  {
    question: "Apfel",
    correctAnswer: "der",
    image: require("./images/apfel.png"),
    englishName: "Apple",
    germanSentence: "Der Apfel ist rot.",
    englishSentence: "The apple is red.",
  },
  {
    question: "Buch",
    correctAnswer: "das",
    image: require("./images/buch.png"),
    englishName: "Book",
    germanSentence: "Das Buch hat viele Seiten.",
    englishSentence: "The book has many pages.",
  },
  {
    question: "Computer",
    correctAnswer: "der",
    image: require("./images/computer.png"),
    englishName: "Computer",
    germanSentence: "Der Computer ist neu.",
    englishSentence: "The computer is new.",
  },
  {
    question: "Stadt",
    correctAnswer: "die",
    image: require("./images/stadt.png"),
    englishName: "City",
    germanSentence: "Die Stadt ist belebt.",
    englishSentence: "The city is bustling.",
  },
  {
    question: "Hund",
    correctAnswer: "der",
    image: require("./images/hund.png"),
    englishName: "Dog",
    germanSentence: "Der Hund bellt laut.",
    englishSentence: "The dog is barking loudly.",
  },
  {
    question: "Blume",
    correctAnswer: "die",
    image: require("./images/blume.png"),
    englishName: "Flower",
    germanSentence: "Die Blume duftet herrlich.",
    englishSentence: "The flower smells lovely.",
  },
  {
    question: "Telefon",
    correctAnswer: "das",
    image: require("./images/telefon.png"),
    englishName: "Telephone",
    germanSentence: "Das Telefon klingelt.",
    englishSentence: "The telephone is ringing.",
  },
  {
    question: "Wasser",
    correctAnswer: "das",
    image: require("./images/wasser.png"),
    englishName: "Water",
    germanSentence: "Das Wasser ist klar.",
    englishSentence: "The water is clear.",
  },
  {
    question: "Kaffee",
    correctAnswer: "der",
    image: require("./images/kaffee.png"),
    englishName: "Coffee",
    germanSentence: "Der Kaffee duftet köstlich.",
    englishSentence: "The coffee smells delicious.",
  },
  {
    question: "Fenster",
    correctAnswer: "das",
    image: require("./images/fenster.png"),
    englishName: "Window",
    germanSentence: "Das Fenster ist geschlossen.",
    englishSentence: "The window is closed.",
  },
  {
    question: "Schule",
    correctAnswer: "die",
    image: require("./images/schule.png"),
    englishName: "School",
    germanSentence: "Die Schule ist groß.",
    englishSentence: "The school is big.",
  },
  {
    question: "Lampe",
    correctAnswer: "die",
    image: require("./images/lampe.png"),
    englishName: "Lamp",
    germanSentence: "Die Lampe leuchtet hell.",
    englishSentence: "The lamp is shining brightly.",
  },
  {
    question: "Brot",
    correctAnswer: "das",
    image: require("./images/brot.png"),
    englishName: "Bread",
    germanSentence: "Das Brot ist frisch.",
    englishSentence: "The bread is fresh.",
  },
  {
    question: "Garten",
    correctAnswer: "der",
    image: require("./images/garten.png"),
    englishName: "Garden",
    germanSentence: "Der Garten ist schön.",
    englishSentence: "The garden is beautiful.",
  },
  {
    question: "Wald",
    correctAnswer: "der",
    image: require("./images/wald.png"),
    englishName: "Forest",
    germanSentence: "Der Wald ist dunkel.",
    englishSentence: "The forest is dark.",
  },
  {
    question: "Himmel",
    correctAnswer: "der",
    image: require("./images/himmel.png"),
    englishName: "Sky",
    germanSentence: "Der Himmel ist blau.",
    englishSentence: "The sky is blue.",
  },
  {
    question: "Maus",
    correctAnswer: "die",
    image: require("./images/maus.png"),
    englishName: "Mouse",
    germanSentence: "Die Maus ist klein.",
    englishSentence: "The mouse is small.",
  },
  {
    question: "Gesicht",
    correctAnswer: "das",
    image: require("./images/gesicht.png"),
    englishName: "Face",
    germanSentence: "Das Gesicht lächelt.",
    englishSentence: "The face is smiling.",
  },
  {
    question: "Brücke",
    correctAnswer: "die",
    image: require("./images/bruecke.png"),
    englishName: "Bridge",
    germanSentence: "Die Brücke führt über den Fluss.",
    englishSentence: "The bridge crosses the river.",
  },
  {
    question: "Geld",
    correctAnswer: "das",
    image: require("./images/geld.png"),
    englishName: "Money",
    germanSentence: "Das Geld ist in der Tasche.",
    englishSentence: "The money is in the wallet.",
  },
  {
    question: "Auge",
    correctAnswer: "das",
    image: require("./images/auge.png"),
    englishName: "Eye",
    germanSentence: "Das Auge sieht alles.",
    englishSentence: "The eye sees everything.",
  },
  {
    question: "Hand",
    correctAnswer: "die",
    image: require("./images/hand.png"),
    englishName: "Hand",
    germanSentence: "Die Hand greift nach dem Apfel.",
    englishSentence: "The hand reaches for the apple.",
  },
  {
    question: "Stuhl",
    correctAnswer: "der",
    image: require("./images/stuhl.png"),
    englishName: "Chair",
    germanSentence: "Der Stuhl ist bequem.",
    englishSentence: "The chair is comfortable.",
  },
  {
    question: "Kühlschrank",
    correctAnswer: "der",
    image: require("./images/kuehlschrank.png"),
    englishName: "Refrigerator",
    germanSentence: "Der Kühlschrank ist voll.",
    englishSentence: "The refrigerator is full.",
  },
  {
    question: "Uhr",
    correctAnswer: "die",
    image: require("./images/uhr.png"),
    englishName: "Clock",
    germanSentence: "Die Uhr zeigt die richtige Zeit.",
    englishSentence: "The clock shows the correct time.",
  },
  {
    question: "Fisch",
    correctAnswer: "der",
    image: require("./images/fisch.png"),
    englishName: "Fish",
    germanSentence: "Der Fisch schwimmt im Wasser.",
    englishSentence: "The fish is swimming in the water.",
  },
  {
    question: "Flugzeug",
    correctAnswer: "das",
    image: require("./images/flugzeug.png"),
    englishName: "Airplane",
    germanSentence: "Das Flugzeug fliegt hoch.",
    englishSentence: "The airplane is flying high.",
  },
  {
    question: "Geschenk",
    correctAnswer: "das",
    image: require("./images/geschenk.png"),
    englishName: "Gift",
    germanSentence: "Das Geschenk ist schön verpackt.",
    englishSentence: "The gift is nicely wrapped.",
  },
  {
    question: "Laptop",
    correctAnswer: "der",
    image: require("./images/laptop.png"),
    englishName: "Laptop",
    germanSentence: "Der Laptop ist leicht.",
    englishSentence: "The laptop is light.",
  },
  {
    question: "Straße",
    correctAnswer: "die",
    image: require("./images/strasse.png"),
    englishName: "Street",
    germanSentence: "Die Straße ist breit.",
    englishSentence: "The street is wide.",
  },
  {
    question: "Zimmer",
    correctAnswer: "das",
    image: require("./images/zimmer.png"),
    englishName: "Room",
    germanSentence: "Das Zimmer ist gemütlich.",
    englishSentence: "The room is cozy.",
  },
  {
    question: "Kleid",
    correctAnswer: "das",
    image: require("./images/kleid.png"),
    englishName: "Dress",
    germanSentence: "Das Kleid ist elegant.",
    englishSentence: "The dress is elegant.",
  },
  {
    question: "Hose",
    correctAnswer: "die",
    image: require("./images/hose.png"),
    englishName: "Pants",
    germanSentence: "Die Hose ist zu lang.",
    englishSentence: "The pants are too long.",
  },
  {
    question: "Spielzeug",
    correctAnswer: "das",
    image: require("./images/spielzeug.png"),
    englishName: "Toy",
    germanSentence: "Das Spielzeug macht Spaß.",
    englishSentence: "The toy is fun.",
  },
  {
    question: "Berg",
    correctAnswer: "der",
    image: require("./images/berg.png"),
    englishName: "Mountain",
    germanSentence: "Der Berg ist hoch.",
    englishSentence: "The mountain is high.",
  },
  {
    question: "See",
    correctAnswer: "der",
    image: require("./images/see.png"),
    englishName: "Lake",
    germanSentence: "Der See ist tief.",
    englishSentence: "The lake is deep.",
  },
  {
    question: "Mond",
    correctAnswer: "der",
    image: require("./images/mond.png"),
    englishName: "Moon",
    germanSentence: "Der Mond scheint hell.",
    englishSentence: "The moon is shining brightly.",
  },
  {
    question: "Tür",
    correctAnswer: "die",
    image: require("./images/tuer.png"),
    englishName: "Door",
    germanSentence: "Die Tür ist geschlossen.",
    englishSentence: "The door is closed.",
  },
  {
    question: "Zahn",
    correctAnswer: "der",
    image: require("./images/zahn.png"),
    englishName: "Tooth",
    germanSentence: "Der Zahn tut weh.",
    englishSentence: "The tooth hurts.",
  },
  {
    question: "Wolke",
    correctAnswer: "die",
    image: require("./images/wolke.png"),
    englishName: "Cloud",
    germanSentence: "Die Wolke ist weiß.",
    englishSentence: "The cloud is white.",
  },
  {
    question: "Boden",
    correctAnswer: "der",
    image: require("./images/boden.png"),
    englishName: "Floor",
    germanSentence: "Der Boden ist glatt.",
    englishSentence: "The floor is smooth.",
  },
  {
    question: "Nase",
    correctAnswer: "die",
    image: require("./images/nase.png"),
    englishName: "Nose",
    germanSentence: "Die Nase riecht den Kuchen.",
    englishSentence: "The nose smells the cake.",
  },
  {
    question: "Mütze",
    correctAnswer: "die",
    image: require("./images/muetze.png"),
    englishName: "Hat",
    germanSentence: "Die Mütze hält warm.",
    englishSentence: "The hat keeps warm.",
  },
  {
    question: "Zunge",
    correctAnswer: "die",
    image: require("./images/zunge.png"),
    englishName: "Tongue",
    germanSentence: "Die Zunge schmeckt die Suppe.",
    englishSentence: "The tongue tastes the soup.",
  },
  {
    question: "Kamera",
    correctAnswer: "die",
    image: require("./images/kamera.png"),
    englishName: "Camera",
    germanSentence: "Die Kamera macht gute Bilder.",
    englishSentence: "The camera takes good pictures.",
  },
  {
    question: "Gitarre",
    correctAnswer: "die",
    image: require("./images/gitarre.png"),
    englishName: "Guitar",
    germanSentence: "Die Gitarre klingt schön.",
    englishSentence: "The guitar sounds beautiful.",
  },
  {
    question: "Musik",
    correctAnswer: "die",
    image: require("./images/musik.png"),
    englishName: "Music",
    germanSentence: "Die Musik ist laut.",
    englishSentence: "The music is loud.",
  },
  {
    question: "Blatt",
    correctAnswer: "das",
    image: require("./images/blatt.png"),
    englishName: "Leaf",
    germanSentence: "Das Blatt fällt vom Baum.",
    englishSentence: "The leaf falls from the tree.",
  },
  {
    question: "Sofa",
    correctAnswer: "das",
    image: require("./images/sofa.png"),
    englishName: "Sofa",
    germanSentence: "Das Sofa ist gemütlich.",
    englishSentence: "The sofa is comfortable.",
  },
  {
    question: "Glas",
    correctAnswer: "das",
    image: require("./images/wasser.png"),
    englishName: "Glass",
    germanSentence: "Das Glas ist halb voll.",
    englishSentence: "The glass is half full.",
  },
  {
    question: "Zoo",
    correctAnswer: "der",
    image: require("./images/zoo.png"),
    englishName: "Zoo",
    germanSentence: "Der Zoo hat viele Tiere.",
    englishSentence: "The zoo has many animals.",
  },
  {
    question: "Familie",
    correctAnswer: "die",
    image: require("./images/familie.png"),
    englishName: "Family",
    germanSentence: "Die Familie isst zusammen.",
    englishSentence: "The family eats together.",
  },
  {
    question: "Tasche",
    correctAnswer: "die",
    image: require("./images/tasche.png"),
    englishName: "Bag",
    germanSentence: "Die Tasche ist schwer.",
    englishSentence: "The bag is heavy.",
  },
  {
    question: "Dach",
    correctAnswer: "das",
    image: require("./images/dach.png"),
    englishName: "Roof",
    germanSentence: "Das Dach ist rot.",
    englishSentence: "The roof is red.",
  },
  {
    question: "Hemd",
    correctAnswer: "das",
    image: require("./images/hemd.png"),
    englishName: "Shirt",
    germanSentence: "Das Hemd ist sauber.",
    englishSentence: "The shirt is clean.",
  },
  {
    question: "Park",
    correctAnswer: "der",
    image: require("./images/park.png"),
    englishName: "Park",
    germanSentence: "Der Park ist grün.",
    englishSentence: "The park is green.",
  },
  {
    question: "Bahn",
    correctAnswer: "die",
    image: require("./images/bahn.png"),
    englishName: "Train",
    germanSentence: "Die Bahn fährt schnell.",
    englishSentence: "The train is moving fast.",
  },
  {
    question: "Brille",
    correctAnswer: "die",
    image: require("./images/brille.png"),
    englishName: "Glasses",
    germanSentence: "Die Brille sitzt gut.",
    englishSentence: "The glasses fit well.",
  },
  {
    question: "Schnee",
    correctAnswer: "der",
    image: require("./images/schnee.png"),
    englishName: "Snow",
    germanSentence: "Der Schnee ist kalt.",
    englishSentence: "The snow is cold.",
  },
  {
    question: "Treppe",
    correctAnswer: "die",
    image: require("./images/treppe.png"),
    englishName: "Stairs",
    germanSentence: "Die Treppe führt nach oben.",
    englishSentence: "The stairs lead upwards.",
  },
  {
    question: "Küche",
    correctAnswer: "die",
    image: require("./images/kueche.png"),
    englishName: "Kitchen",
    germanSentence: "Die Küche ist sauber.",
    englishSentence: "The kitchen is clean.",
  },
  {
    question: "Schlüssel",
    correctAnswer: "der",
    image: require("./images/schluessel.png"),
    englishName: "Key",
    germanSentence: "Der Schlüssel öffnet die Tür.",
    englishSentence: "The key opens the door.",
  },
  {
    question: "Fluss",
    correctAnswer: "der",
    image: require("./images/fluss.png"),
    englishName: "River",
    germanSentence: "Der Fluss fließt schnell.",
    englishSentence: "The river flows fast.",
  },
  {
    question: "Löffel",
    correctAnswer: "der",
    image: require("./images/loeffel.png"),
    englishName: "Spoon",
    germanSentence: "Der Löffel ist aus Silber.",
    englishSentence: "The spoon is made of silver.",
  },
  {
    question: "Feder",
    correctAnswer: "die",
    image: require("./images/feder.png"),
    englishName: "Feather",
    germanSentence: "Die Feder schreibt gut.",
    englishSentence: "The feather writes well.",
  },
  {
    question: "Kissen",
    correctAnswer: "das",
    image: require("./images/kissen.png"),
    englishName: "Pillow",
    germanSentence: "Das Kissen ist weich.",
    englishSentence: "The pillow is soft.",
  },
  {
    question: "Tasse",
    correctAnswer: "die",
    image: require("./images/tasse.png"),
    englishName: "Cup",
    germanSentence: "Die Tasse ist leer.",
    englishSentence: "The cup is empty.",
  },
  {
    question: "Hut",
    correctAnswer: "der",
    image: require("./images/hut.png"),
    englishName: "Hat",
    germanSentence: "Der Hut ist schick.",
    englishSentence: "The hat is stylish.",
  },

  {
    question: "Papier",
    correctAnswer: "das",
    image: require("./images/papier.png"),
    englishName: "Paper",
    germanSentence: "Das Papier ist weiß.",
    englishSentence: "The paper is white.",
  },
  {
    question: "Pferd",
    correctAnswer: "das",
    image: require("./images/pferd.png"),
    englishName: "Horse",
    germanSentence: "Das Pferd läuft schnell über die Wiese.",
    englishSentence: "The horse runs quickly across the meadow.",
  },
  {
    question: "Kuh",
    correctAnswer: "die",
    image: require("./images/kuh.png"),
    englishName: "Cow",
    germanSentence: "Die Kuh steht auf dem Feld.",
    englishSentence: "The cow is standing in the field.",
  },
  {
    question: "Huhn",
    correctAnswer: "das",
    image: require("./images/huhn.png"),
    englishName: "Chicken",
    germanSentence: "Das Huhn legt ein Ei.",
    englishSentence: "The chicken lays an egg.",
  },
  {
    question: "Hahn",
    correctAnswer: "der",
    image: require("./images/hahn.png"),
    englishName: "Rooster",
    germanSentence: "Der Hahn kräht am Morgen.",
    englishSentence: "The rooster crows in the morning.",
  },
  {
    question: "Schaf",
    correctAnswer: "das",
    image: require("./images/schaf.png"),
    englishName: "Sheep",
    germanSentence: "Das Schaf hat viel Wolle.",
    englishSentence: "The sheep has a lot of wool.",
  },
  {
    question: "Ziege",
    correctAnswer: "die",
    image: require("./images/ziege.png"),
    englishName: "Goat",
    germanSentence: "Die Ziege klettert auf den Felsen.",
    englishSentence: "The goat climbs on the rock.",
  },
  {
    question: "Ente",
    correctAnswer: "die",
    image: require("./images/ente.png"),
    englishName: "Duck",
    germanSentence: "Die Ente schwimmt im Teich.",
    englishSentence: "The duck is swimming in the pond.",
  },
  {
    question: "Hase",
    correctAnswer: "der",
    image: require("./images/hase.png"),
    englishName: "Hare",
    germanSentence: "Der Hase springt über das Gras.",
    englishSentence: "The hare jumps over the grass.",
  },
  {
    question: "Fuchs",
    correctAnswer: "der",
    image: require("./images/fuchs.png"),
    englishName: "Fox",
    germanSentence: "Der Fuchs läuft durch den Wald.",
    englishSentence: "The fox runs through the forest.",
  },
  {
    question: "Wolf",
    correctAnswer: "der",
    image: require("./images/wolf.png"),
    englishName: "Wolf",
    germanSentence: "Der Wolf heult im Mondlicht.",
    englishSentence: "The wolf howls in the moonlight.",
  },
  {
    question: "Bär",
    correctAnswer: "der",
    image: require("./images/baer.png"),
    englishName: "Bear",
    germanSentence: "Der Bär schläft im Winter.",
    englishSentence: "The bear sleeps in winter.",
  },
  {
    question: "Eichhörnchen",
    correctAnswer: "das",
    image: require("./images/eichhoernchen.png"),
    englishName: "Squirrel",
    germanSentence: "Das Eichhörnchen sammelt Nüsse.",
    englishSentence: "The squirrel collects nuts.",
  },
  {
    question: "Igel",
    correctAnswer: "der",
    image: require("./images/igel.png"),
    englishName: "Hedgehog",
    germanSentence: "Der Igel rollt sich zusammen.",
    englishSentence: "The hedgehog curls up.",
  },
  {
    question: "Elefant",
    correctAnswer: "der",
    image: require("./images/elefant.png"),
    englishName: "Elephant",
    germanSentence: "Der Elefant hat einen langen Rüssel.",
    englishSentence: "The elephant has a long trunk.",
  },
  {
    question: "Löwe",
    correctAnswer: "der",
    image: require("./images/loewe.png"),
    englishName: "Lion",
    germanSentence: "Der Löwe ist der König der Tiere.",
    englishSentence: "The lion is the king of the animals.",
  },
  {
    question: "Tiger",
    correctAnswer: "der",
    image: require("./images/tiger.png"),
    englishName: "Tiger",
    germanSentence: "Der Tiger hat Streifen.",
    englishSentence: "The tiger has stripes.",
  },
  {
    question: "Affe",
    correctAnswer: "der",
    image: require("./images/affe.png"),
    englishName: "Monkey",
    germanSentence: "Der Affe klettert auf den Baum.",
    englishSentence: "The monkey climbs the tree.",
  },
  {
    question: "Giraffe",
    correctAnswer: "die",
    image: require("./images/giraffe.png"),
    englishName: "Giraffe",
    germanSentence: "Die Giraffe hat einen langen Hals.",
    englishSentence: "The giraffe has a long neck.",
  },
  {
    question: "Zebra",
    correctAnswer: "das",
    image: require("./images/zebra.png"),
    englishName: "Zebra",
    germanSentence: "Das Zebra hat schwarze und weiße Streifen.",
    englishSentence: "The zebra has black and white stripes.",
  },
  {
    question: "Pinguin",
    correctAnswer: "der",
    image: require("./images/pinguin.png"),
    englishName: "Penguin",
    germanSentence: "Der Pinguin kann nicht fliegen.",
    englishSentence: "The penguin cannot fly.",
  },
  {
    question: "Kamel",
    correctAnswer: "das",
    image: require("./images/kamel.png"),
    englishName: "Camel",
    germanSentence: "Das Kamel lebt in der Wüste.",
    englishSentence: "The camel lives in the desert.",
  },
  {
    question: "Biene",
    correctAnswer: "die",
    image: require("./images/biene.png"),
    englishName: "Bee",
    germanSentence: "Die Biene sammelt Nektar.",
    englishSentence: "The bee collects nectar.",
  },
  {
    question: "Schmetterling",
    correctAnswer: "der",
    image: require("./images/schmetterling.png"),
    englishName: "Butterfly",
    germanSentence: "Der Schmetterling fliegt von Blume zu Blume.",
    englishSentence: "The butterfly flies from flower to flower.",
  },
  {
    question: "Frosch",
    correctAnswer: "der",
    image: require("./images/frosch.png"),
    englishName: "Frog",
    germanSentence: "Der Frosch springt ins Wasser.",
    englishSentence: "The frog jumps into the water.",
  },
  {
    question: "Krokodil",
    correctAnswer: "das",
    image: require("./images/krokodil.png"),
    englishName: "Crocodile",
    germanSentence: "Das Krokodil lebt im Fluss.",
    englishSentence: "The crocodile lives in the river.",
  },
  {
    question: "Esel",
    correctAnswer: "der",
    image: require("./images/esel.png"),
    englishName: "Donkey",
    germanSentence: "Der Esel trägt schwere Taschen.",
    englishSentence: "The donkey carries heavy bags.",
  },
  {
    question: "Papagei",
    correctAnswer: "der",
    image: require("./images/papagei.png"),
    englishName: "Parrot",
    germanSentence: "Der Papagei spricht laut.",
    englishSentence: "The parrot talks loudly.",
  },
  {
    question: "Känguru",
    correctAnswer: "das",
    image: require("./images/kaenguru.png"),
    englishName: "Kangaroo",
    germanSentence: "Das Känguru springt weit.",
    englishSentence: "The kangaroo jumps far.",
  },
  {
    question: "Koala",
    correctAnswer: "der",
    image: require("./images/koala.png"),
    englishName: "Koala",
    germanSentence: "Der Koala schläft im Baum.",
    englishSentence: "The koala sleeps in the tree.",
  },
  {
    question: "Delphin",
    correctAnswer: "der",
    image: require("./images/delphin.png"),
    englishName: "Dolphin",
    germanSentence: "Der Delphin schwimmt schnell.",
    englishSentence: "The dolphin swims fast.",
  },
  {
    question: "Wal",
    correctAnswer: "der",
    image: require("./images/wal.png"),
    englishName: "Whale",
    germanSentence: "Der Wal ist ein großes Meerestier.",
    englishSentence: "The whale is a large sea animal.",
  },
  {
    question: "Krabbe",
    correctAnswer: "die",
    image: require("./images/krabbe.png"),
    englishName: "Crab",
    germanSentence: "Die Krabbe läuft seitwärts.",
    englishSentence: "The crab walks sideways.",
  },
  {
    question: "Schildkröte",
    correctAnswer: "die",
    image: require("./images/schildkroete.png"),
    englishName: "Turtle",
    germanSentence: "Die Schildkröte bewegt sich langsam.",
    englishSentence: "The turtle moves slowly.",
  },
];
