export const quizMainData = [
  {
    question: "Haus",
    correctAnswer: "das",
    image: require("./images/haus.png"),
    englishName: "House",
  },
  {
    question: "Sonne",
    correctAnswer: "die",
    image: require("./images/sonne.png"),
    englishName: "Sun",
  },
  {
    question: "Katze",
    correctAnswer: "die",
    image: require("./images/katze.png"),
    englishName: "Cat",
  },
  {
    question: "Vogel",
    correctAnswer: "der",
    image: require("./images/vogel.png"),
    englishName: "Bird",
  },
  {
    question: "Auto",
    correctAnswer: "das",
    image: require("./images/auto.png"),
    englishName: "Car",
  },
  {
    question: "Tisch",
    correctAnswer: "der",
    image: require("./images/tisch.png"),
    englishName: "Table",
  },
  {
    question: "Apfel",
    correctAnswer: "der",
    image: require("./images/apfel.png"),
    englishName: "Apple",
  },
  {
    question: "Buch",
    correctAnswer: "das",
    image: require("./images/buch.png"),
    englishName: "Book",
  },
  {
    question: "Computer",
    correctAnswer: "der",
    image: require("./images/computer.png"),
    englishName: "Computer",
  },
  {
    question: "Stadt",
    correctAnswer: "die",
    image: require("./images/stadt.png"),
    englishName: "City",
  },
  {
    question: "Hund",
    correctAnswer: "der",
    image: require("./images/hund.png"),
    englishName: "Dog",
  },
  {
    question: "Blume",
    correctAnswer: "die",
    image: require("./images/blume.png"),
    englishName: "Flower",
  },
  {
    question: "Telefon",
    correctAnswer: "das",
    image: require("./images/telefon.png"),
    englishName: "Telephone",
  },
  {
    question: "Wasser",
    correctAnswer: "das",
    image: require("./images/wasser.png"),
    englishName: "Water",
  },
  {
    question: "Kaffee",
    correctAnswer: "der",
    image: require("./images/kaffee.png"),
    englishName: "Coffee",
  },
  {
    question: "Fenster",
    correctAnswer: "das",
    image: require("./images/fenster.png"),
    englishName: "Window",
  },
  {
    question: "Schule",
    correctAnswer: "die",
    image: require("./images/schule.png"),
    englishName: "School",
  },
  {
    question: "Lampe",
    correctAnswer: "die",
    image: require("./images/lampe.png"),
    englishName: "Lamp",
  },
  {
    question: "Brot",
    correctAnswer: "das",
    image: require("./images/brot.png"),
    englishName: "Bread",
  },
  {
    question: "Garten",
    correctAnswer: "der",
    image: require("./images/garten.png"),
    englishName: "Garden",
  },
  {
    question: "Wald",
    correctAnswer: "der",
    image: require("./images/wald.png"),
    englishName: "Forest",
  },
  {
    question: "Himmel",
    correctAnswer: "der",
    image: require("./images/himmel.png"),
    englishName: "Sky",
  },
  {
    question: "Maus",
    correctAnswer: "die",
    image: require("./images/maus.png"),
    englishName: "Mouse",
  },
  {
    question: "Gesicht",
    correctAnswer: "das",
    image: require("./images/gesicht.png"),
    englishName: "Face",
  },
  {
    question: "Brücke",
    correctAnswer: "die",
    image: require("./images/bruecke.png"),
    englishName: "Bridge",
  },
  {
    question: "Geld",
    correctAnswer: "das",
    image: require("./images/geld.png"),
    englishName: "Money",
  },
  {
    question: "Auge",
    correctAnswer: "das",
    image: require("./images/auge.png"),
    englishName: "Eye",
  },
  {
    question: "Hand",
    correctAnswer: "die",
    image: require("./images/hand.png"),
    englishName: "Hand",
  },
  {
    question: "Stuhl",
    correctAnswer: "der",
    image: require("./images/stuhl.png"),
    englishName: "Chair",
  },
  {
    question: "Kühlschrank",
    correctAnswer: "der",
    image: require("./images/kuehlschrank.png"),
    englishName: "Refrigerator",
  },
  {
    question: "Uhr",
    correctAnswer: "die",
    image: require("./images/uhr.png"),
    englishName: "Clock",
  },
  {
    question: "Fisch",
    correctAnswer: "der",
    image: require("./images/fisch.png"),
    englishName: "Fish",
  },
  {
    question: "Flugzeug",
    correctAnswer: "das",
    image: require("./images/flugzeug.png"),
    englishName: "Airplane",
  },
  {
    question: "Geschenk",
    correctAnswer: "das",
    image: require("./images/geschenk.png"),
    englishName: "Gift",
  },
  {
    question: "Laptop",
    correctAnswer: "der",
    image: require("./images/laptop.png"),
    englishName: "Laptop",
  },
  {
    question: "Straße",
    correctAnswer: "die",
    image: require("./images/strasse.png"),
    englishName: "Street",
  },
  {
    question: "Zimmer",
    correctAnswer: "das",
    image: require("./images/zimmer.png"),
    englishName: "Room",
  },
  {
    question: "Kleid",
    correctAnswer: "das",
    image: require("./images/kleid.png"),
    englishName: "Dress",
  },
  {
    question: "Hose",
    correctAnswer: "die",
    image: require("./images/hose.png"),
    englishName: "Pants",
  },
  {
    question: "Spielzeug",
    correctAnswer: "das",
    image: require("./images/spielzeug.png"),
    englishName: "Toy",
  },
  {
    question: "Berg",
    correctAnswer: "der",
    image: require("./images/berg.png"),
    englishName: "Mountain",
  },
  {
    question: "See",
    correctAnswer: "der",
    image: require("./images/see.png"),
    englishName: "Lake",
  },
  {
    question: "Mond",
    correctAnswer: "der",
    image: require("./images/mond.png"),
    englishName: "Moon",
  },
  {
    question: "Tür",
    correctAnswer: "die",
    image: require("./images/tuer.png"),
    englishName: "Door",
  },
  {
    question: "Zahn",
    correctAnswer: "der",
    image: require("./images/zahn.png"),
    englishName: "Tooth",
  },
  {
    question: "Wolke",
    correctAnswer: "die",
    image: require("./images/wolke.png"),
    englishName: "Cloud",
  },
  {
    question: "Boden",
    correctAnswer: "der",
    image: require("./images/boden.png"),
    englishName: "Floor",
  },
  {
    question: "Nase",
    correctAnswer: "die",
    image: require("./images/nase.png"),
    englishName: "Nose",
  },
  {
    question: "Mütze",
    correctAnswer: "die",
    image: require("./images/muetze.png"),
    englishName: "Hat",
  },
  {
    question: "Zunge",
    correctAnswer: "die",
    image: require("./images/zunge.png"),
    englishName: "Tongue",
  },
  {
    question: "Kamera",
    correctAnswer: "die",
    image: require("./images/kamera.png"),
    englishName: "Camera",
  },
  {
    question: "Gitarre",
    correctAnswer: "die",
    image: require("./images/gitarre.png"),
    englishName: "Guitar",
  },
  {
    question: "Musik",
    correctAnswer: "die",
    image: require("./images/musik.png"),
    englishName: "Music",
  },
  {
    question: "Blatt",
    correctAnswer: "das",
    image: require("./images/blatt.png"),
    englishName: "Leaf",
  },
  {
    question: "Sofa",
    correctAnswer: "das",
    image: require("./images/sofa.png"),
    englishName: "Sofa",
  },
  {
    question: "Glas",
    correctAnswer: "das",
    image: require("./images/glas.png"),
    englishName: "Glass",
  },
  {
    question: "Zoo",
    correctAnswer: "der",
    image: require("./images/zoo.png"),
    englishName: "Zoo",
  },
  {
    question: "Familie",
    correctAnswer: "die",
    image: require("./images/familie.png"),
    englishName: "Family",
  },
  {
    question: "Tasche",
    correctAnswer: "die",
    image: require("./images/tasche.png"),
    englishName: "Bag",
  },
  {
    question: "Dach",
    correctAnswer: "das",
    image: require("./images/dach.png"),
    englishName: "Roof",
  },
  {
    question: "Hemd",
    correctAnswer: "das",
    image: require("./images/hemd.png"),
    englishName: "Shirt",
  },
  {
    question: "Park",
    correctAnswer: "der",
    image: require("./images/park.png"),
    englishName: "Park",
  },
  {
    question: "Bahn",
    correctAnswer: "die",
    image: require("./images/bahn.png"),
    englishName: "Train",
  },
  {
    question: "Brille",
    correctAnswer: "die",
    image: require("./images/brille.png"),
    englishName: "Glasses",
  },
  {
    question: "Schnee",
    correctAnswer: "der",
    image: require("./images/schnee.png"),
    englishName: "Snow",
  },
  {
    question: "Treppe",
    correctAnswer: "die",
    image: require("./images/treppe.png"),
    englishName: "Stairs",
  },
  {
    question: "Küche",
    correctAnswer: "die",
    image: require("./images/kueche.png"),
    englishName: "Kitchen",
  },
  {
    question: "Fluss",
    correctAnswer: "der",
    image: require("./images/fluss.png"),
    englishName: "River",
  },
  {
    question: "Ei",
    correctAnswer: "das",
    image: require("./images/ei.png"),
    englishName: "Egg",
  },
  {
    question: "Lehrer",
    correctAnswer: "der",
    image: require("./images/lehrer.png"),
    englishName: "Teacher",
  },
  {
    question: "Lehrerin",
    correctAnswer: "die",
    image: require("./images/lehrerin.png"),
    englishName: "Teacher",
  },
  {
    question: "Tafel",
    correctAnswer: "die",
    image: require("./images/tafel.png"),
    englishName: "Blackboard",
  },
  {
    question: "Feder",
    correctAnswer: "die",
    image: require("./images/feder.png"),
    englishName: "Feather",
  },
  {
    question: "Schlüssel",
    correctAnswer: "der",
    image: require("./images/schluessel.png"),
    englishName: "Key",
  },
  {
    question: "Spiegel",
    correctAnswer: "der",
    image: require("./images/spiegel.png"),
    englishName: "Mirror",
  },
  {
    question: "Hut",
    correctAnswer: "der",
    image: require("./images/hut.png"),
    englishName: "Hat",
  },
  {
    question: "Kuchen",
    correctAnswer: "der",
    image: require("./images/kuchen.png"),
    englishName: "Cake",
  },
  {
    question: "Schlange",
    correctAnswer: "die",
    image: require("./images/schlange.png"),
    englishName: "Snake",
  },
  {
    question: "Schuh",
    correctAnswer: "der",
    image: require("./images/schuh.png"),
    englishName: "Shoe",
  },
  {
    question: "Fahrrad",
    correctAnswer: "das",
    image: require("./images/fahrrad.png"),
    englishName: "Bicycle",
  },
  {
    question: "Messer",
    correctAnswer: "das",
    image: require("./images/messer.png"),
    englishName: "Knife",
  },
  {
    question: "Schal",
    correctAnswer: "der",
    image: require("./images/schal.png"),
    englishName: "Scarf",
  },
  {
    question: "Handschuh",
    correctAnswer: "der",
    image: require("./images/handschuh.png"),
    englishName: "Glove",
  },
  {
    question: "Papier",
    correctAnswer: "das",
    image: require("./images/papier.png"),
    englishName: "Paper",
  },

  {
    question: "Brief",
    correctAnswer: "der",
    image: require("./images/brief.png"),
    englishName: "Letter",
  },
  {
    question: "Schlafzimmer",
    correctAnswer: "das",
    image: require("./images/schlafzimmer.png"),
    englishName: "Bedroom",
  },
  {
    question: "Handy",
    correctAnswer: "das",
    image: require("./images/handy.png"),
    englishName: "Mobile Phone",
  },
  {
    question: "Keller",
    correctAnswer: "der",
    image: require("./images/keller.png"),
    englishName: "Basement",
  },
  {
    question: "Müll",
    correctAnswer: "der",
    image: require("./images/muell.png"),
    englishName: "Trash",
  },
  {
    question: "Mauer",
    correctAnswer: "die",
    image: require("./images/mauer.png"),
    englishName: "Wall",
  },
  {
    question: "Eule",
    correctAnswer: "die",
    image: require("./images/eule.png"),
    englishName: "Owl",
  },
  {
    question: "Bahnsteig",
    correctAnswer: "der",
    image: require("./images/bahnsteig.png"),
    englishName: "Platform",
  },
  {
    question: "Bier",
    correctAnswer: "das",
    image: require("./images/bier.png"),
    englishName: "Beer",
  },
  {
    question: "Stift",
    correctAnswer: "der",
    image: require("./images/stift.png"),
    englishName: "Pen",
  },
  {
    question: "Löffel",
    correctAnswer: "der",
    image: require("./images/loeffel.png"),
    englishName: "Spoon",
  },
  {
    question: "Schere",
    correctAnswer: "die",
    image: require("./images/schere.png"),
    englishName: "Scissors",
  },
  {
    question: "Kissen",
    correctAnswer: "das",
    image: require("./images/kissen.png"),
    englishName: "Pillow",
  },
  {
    question: "Regen",
    correctAnswer: "der",
    image: require("./images/regen.png"),
    englishName: "Rain",
  },
  {
    question: "Papiere",
    correctAnswer: "die",
    image: require("./images/papiere.png"),
    englishName: "Papers",
  },
  {
    question: "Schuhe",
    correctAnswer: "die",
    image: require("./images/schuhe.png"),
    englishName: "Shoes",
  },
];

export const quizWordSentence = [
  {
    question: "Vogel",
    correctAnswer: "der",
    image: require("./images/vogel.png"),
    englishName: "Bird",
    germanSentence: "Der Vogel singt im Baum.",
    englishSentence: "The bird is singing in the tree.",
  },
  {
    question: "Auto",
    correctAnswer: "das",
    image: require("./images/auto.png"),
    englishName: "Car",
    germanSentence: "Das Auto fährt schnell.",
    englishSentence: "The car is driving fast.",
  },
  {
    question: "Tisch",
    correctAnswer: "der",
    image: require("./images/tisch.png"),
    englishName: "Table",
    germanSentence: "Der Tisch ist aus Holz.",
    englishSentence: "The table is made of wood.",
  },
  {
    question: "Apfel",
    correctAnswer: "der",
    image: require("./images/apfel.png"),
    englishName: "Apple",
    germanSentence: "Der Apfel ist rot.",
    englishSentence: "The apple is red.",
  },
  {
    question: "Buch",
    correctAnswer: "das",
    image: require("./images/buch.png"),
    englishName: "Book",
    germanSentence: "Das Buch hat viele Seiten.",
    englishSentence: "The book has many pages.",
  },
  {
    question: "Computer",
    correctAnswer: "der",
    image: require("./images/computer.png"),
    englishName: "Computer",
    germanSentence: "Der Computer ist neu.",
    englishSentence: "The computer is new.",
  },
  {
    question: "Stadt",
    correctAnswer: "die",
    image: require("./images/stadt.png"),
    englishName: "City",
    germanSentence: "Die Stadt ist belebt.",
    englishSentence: "The city is bustling.",
  },
  {
    question: "Hund",
    correctAnswer: "der",
    image: require("./images/hund.png"),
    englishName: "Dog",
    germanSentence: "Der Hund bellt laut.",
    englishSentence: "The dog is barking loudly.",
  },
  {
    question: "Blume",
    correctAnswer: "die",
    image: require("./images/blume.png"),
    englishName: "Flower",
    germanSentence: "Die Blume duftet herrlich.",
    englishSentence: "The flower smells lovely.",
  },
  {
    question: "Telefon",
    correctAnswer: "das",
    image: require("./images/telefon.png"),
    englishName: "Telephone",
    germanSentence: "Das Telefon klingelt.",
    englishSentence: "The telephone is ringing.",
  },
  {
    question: "Wasser",
    correctAnswer: "das",
    image: require("./images/wasser.png"),
    englishName: "Water",
    germanSentence: "Das Wasser ist klar.",
    englishSentence: "The water is clear.",
  },
  {
    question: "Kaffee",
    correctAnswer: "der",
    image: require("./images/kaffee.png"),
    englishName: "Coffee",
    germanSentence: "Der Kaffee duftet köstlich.",
    englishSentence: "The coffee smells delicious.",
  },
  {
    question: "Fenster",
    correctAnswer: "das",
    image: require("./images/fenster.png"),
    englishName: "Window",
    germanSentence: "Das Fenster ist geschlossen.",
    englishSentence: "The window is closed.",
  },
  {
    question: "Schule",
    correctAnswer: "die",
    image: require("./images/schule.png"),
    englishName: "School",
    germanSentence: "Die Schule ist groß.",
    englishSentence: "The school is big.",
  },
  {
    question: "Lampe",
    correctAnswer: "die",
    image: require("./images/lampe.png"),
    englishName: "Lamp",
    germanSentence: "Die Lampe leuchtet hell.",
    englishSentence: "The lamp is shining brightly.",
  },
  {
    question: "Brot",
    correctAnswer: "das",
    image: require("./images/brot.png"),
    englishName: "Bread",
    germanSentence: "Das Brot ist frisch.",
    englishSentence: "The bread is fresh.",
  },
  {
    question: "Garten",
    correctAnswer: "der",
    image: require("./images/garten.png"),
    englishName: "Garden",
    germanSentence: "Der Garten ist schön.",
    englishSentence: "The garden is beautiful.",
  },
  {
    question: "Wald",
    correctAnswer: "der",
    image: require("./images/wald.png"),
    englishName: "Forest",
    germanSentence: "Der Wald ist dunkel.",
    englishSentence: "The forest is dark.",
  },
  {
    question: "Himmel",
    correctAnswer: "der",
    image: require("./images/himmel.png"),
    englishName: "Sky",
    germanSentence: "Der Himmel ist blau.",
    englishSentence: "The sky is blue.",
  },
  {
    question: "Maus",
    correctAnswer: "die",
    image: require("./images/maus.png"),
    englishName: "Mouse",
    germanSentence: "Die Maus ist klein.",
    englishSentence: "The mouse is small.",
  },
  {
    question: "Gesicht",
    correctAnswer: "das",
    image: require("./images/gesicht.png"),
    englishName: "Face",
    germanSentence: "Das Gesicht lächelt.",
    englishSentence: "The face is smiling.",
  },
  {
    question: "Brücke",
    correctAnswer: "die",
    image: require("./images/bruecke.png"),
    englishName: "Bridge",
    germanSentence: "Die Brücke führt über den Fluss.",
    englishSentence: "The bridge crosses the river.",
  },
  {
    question: "Geld",
    correctAnswer: "das",
    image: require("./images/geld.png"),
    englishName: "Money",
    germanSentence: "Das Geld ist in der Tasche.",
    englishSentence: "The money is in the wallet.",
  },
  {
    question: "Auge",
    correctAnswer: "das",
    image: require("./images/auge.png"),
    englishName: "Eye",
    germanSentence: "Das Auge sieht alles.",
    englishSentence: "The eye sees everything.",
  },
  {
    question: "Hand",
    correctAnswer: "die",
    image: require("./images/hand.png"),
    englishName: "Hand",
    germanSentence: "Die Hand greift nach dem Apfel.",
    englishSentence: "The hand reaches for the apple.",
  },
  {
    question: "Stuhl",
    correctAnswer: "der",
    image: require("./images/stuhl.png"),
    englishName: "Chair",
    germanSentence: "Der Stuhl ist bequem.",
    englishSentence: "The chair is comfortable.",
  },
  {
    question: "Kühlschrank",
    correctAnswer: "der",
    image: require("./images/kuehlschrank.png"),
    englishName: "Refrigerator",
    germanSentence: "Der Kühlschrank ist voll.",
    englishSentence: "The refrigerator is full.",
  },
  {
    question: "Uhr",
    correctAnswer: "die",
    image: require("./images/uhr.png"),
    englishName: "Clock",
    germanSentence: "Die Uhr zeigt die richtige Zeit.",
    englishSentence: "The clock shows the correct time.",
  },
  {
    question: "Fisch",
    correctAnswer: "der",
    image: require("./images/fisch.png"),
    englishName: "Fish",
    germanSentence: "Der Fisch schwimmt im Wasser.",
    englishSentence: "The fish is swimming in the water.",
  },
  {
    question: "Flugzeug",
    correctAnswer: "das",
    image: require("./images/flugzeug.png"),
    englishName: "Airplane",
    germanSentence: "Das Flugzeug fliegt hoch.",
    englishSentence: "The airplane is flying high.",
  },
  {
    question: "Geschenk",
    correctAnswer: "das",
    image: require("./images/geschenk.png"),
    englishName: "Gift",
    germanSentence: "Das Geschenk ist schön verpackt.",
    englishSentence: "The gift is nicely wrapped.",
  },
  {
    question: "Laptop",
    correctAnswer: "der",
    image: require("./images/laptop.png"),
    englishName: "Laptop",
    germanSentence: "Der Laptop ist leicht.",
    englishSentence: "The laptop is light.",
  },
  {
    question: "Straße",
    correctAnswer: "die",
    image: require("./images/strasse.png"),
    englishName: "Street",
    germanSentence: "Die Straße ist breit.",
    englishSentence: "The street is wide.",
  },
  {
    question: "Zimmer",
    correctAnswer: "das",
    image: require("./images/zimmer.png"),
    englishName: "Room",
    germanSentence: "Das Zimmer ist gemütlich.",
    englishSentence: "The room is cozy.",
  },
  {
    question: "Kleid",
    correctAnswer: "das",
    image: require("./images/kleid.png"),
    englishName: "Dress",
    germanSentence: "Das Kleid ist elegant.",
    englishSentence: "The dress is elegant.",
  },
  {
    question: "Hose",
    correctAnswer: "die",
    image: require("./images/hose.png"),
    englishName: "Pants",
    germanSentence: "Die Hose ist zu lang.",
    englishSentence: "The pants are too long.",
  },
  {
    question: "Spielzeug",
    correctAnswer: "das",
    image: require("./images/spielzeug.png"),
    englishName: "Toy",
    germanSentence: "Das Spielzeug macht Spaß.",
    englishSentence: "The toy is fun.",
  },
  {
    question: "Berg",
    correctAnswer: "der",
    image: require("./images/berg.png"),
    englishName: "Mountain",
    germanSentence: "Der Berg ist hoch.",
    englishSentence: "The mountain is high.",
  },
  {
    question: "See",
    correctAnswer: "der",
    image: require("./images/see.png"),
    englishName: "Lake",
    germanSentence: "Der See ist tief.",
    englishSentence: "The lake is deep.",
  },
  {
    question: "Mond",
    correctAnswer: "der",
    image: require("./images/mond.png"),
    englishName: "Moon",
    germanSentence: "Der Mond scheint hell.",
    englishSentence: "The moon is shining brightly.",
  },
  {
    question: "Tür",
    correctAnswer: "die",
    image: require("./images/tuer.png"),
    englishName: "Door",
    germanSentence: "Die Tür ist geschlossen.",
    englishSentence: "The door is closed.",
  },
  {
    question: "Zahn",
    correctAnswer: "der",
    image: require("./images/zahn.png"),
    englishName: "Tooth",
    germanSentence: "Der Zahn tut weh.",
    englishSentence: "The tooth hurts.",
  },
  {
    question: "Wolke",
    correctAnswer: "die",
    image: require("./images/wolke.png"),
    englishName: "Cloud",
    germanSentence: "Die Wolke ist weiß.",
    englishSentence: "The cloud is white.",
  },
  {
    question: "Boden",
    correctAnswer: "der",
    image: require("./images/boden.png"),
    englishName: "Floor",
    germanSentence: "Der Boden ist glatt.",
    englishSentence: "The floor is smooth.",
  },
  {
    question: "Nase",
    correctAnswer: "die",
    image: require("./images/nase.png"),
    englishName: "Nose",
    germanSentence: "Die Nase riecht den Kuchen.",
    englishSentence: "The nose smells the cake.",
  },
  {
    question: "Mütze",
    correctAnswer: "die",
    image: require("./images/muetze.png"),
    englishName: "Hat",
    germanSentence: "Die Mütze hält warm.",
    englishSentence: "The hat keeps warm.",
  },
  {
    question: "Zunge",
    correctAnswer: "die",
    image: require("./images/zunge.png"),
    englishName: "Tongue",
    germanSentence: "Die Zunge schmeckt die Suppe.",
    englishSentence: "The tongue tastes the soup.",
  },
  {
    question: "Kamera",
    correctAnswer: "die",
    image: require("./images/kamera.png"),
    englishName: "Camera",
    germanSentence: "Die Kamera macht gute Bilder.",
    englishSentence: "The camera takes good pictures.",
  },
  {
    question: "Gitarre",
    correctAnswer: "die",
    image: require("./images/gitarre.png"),
    englishName: "Guitar",
    germanSentence: "Die Gitarre klingt schön.",
    englishSentence: "The guitar sounds beautiful.",
  },
  {
    question: "Musik",
    correctAnswer: "die",
    image: require("./images/musik.png"),
    englishName: "Music",
    germanSentence: "Die Musik ist laut.",
    englishSentence: "The music is loud.",
  },
  {
    question: "Blatt",
    correctAnswer: "das",
    image: require("./images/blatt.png"),
    englishName: "Leaf",
    germanSentence: "Das Blatt fällt vom Baum.",
    englishSentence: "The leaf falls from the tree.",
  },
  {
    question: "Sofa",
    correctAnswer: "das",
    image: require("./images/sofa.png"),
    englishName: "Sofa",
    germanSentence: "Das Sofa ist gemütlich.",
    englishSentence: "The sofa is comfortable.",
  },
  {
    question: "Glas",
    correctAnswer: "das",
    image: require("./images/wasser.png"),
    englishName: "Glass",
    germanSentence: "Das Glas ist halb voll.",
    englishSentence: "The glass is half full.",
  },
  {
    question: "Zoo",
    correctAnswer: "der",
    image: require("./images/zoo.png"),
    englishName: "Zoo",
    germanSentence: "Der Zoo hat viele Tiere.",
    englishSentence: "The zoo has many animals.",
  },
  {
    question: "Familie",
    correctAnswer: "die",
    image: require("./images/familie.png"),
    englishName: "Family",
    germanSentence: "Die Familie isst zusammen.",
    englishSentence: "The family eats together.",
  },
  {
    question: "Tasche",
    correctAnswer: "die",
    image: require("./images/tasche.png"),
    englishName: "Bag",
    germanSentence: "Die Tasche ist schwer.",
    englishSentence: "The bag is heavy.",
  },
  {
    question: "Dach",
    correctAnswer: "das",
    image: require("./images/dach.png"),
    englishName: "Roof",
    germanSentence: "Das Dach ist rot.",
    englishSentence: "The roof is red.",
  },
  {
    question: "Hemd",
    correctAnswer: "das",
    image: require("./images/hemd.png"),
    englishName: "Shirt",
    germanSentence: "Das Hemd ist sauber.",
    englishSentence: "The shirt is clean.",
  },
  {
    question: "Park",
    correctAnswer: "der",
    image: require("./images/park.png"),
    englishName: "Park",
    germanSentence: "Der Park ist grün.",
    englishSentence: "The park is green.",
  },
  {
    question: "Bahn",
    correctAnswer: "die",
    image: require("./images/bahn.png"),
    englishName: "Train",
    germanSentence: "Die Bahn fährt schnell.",
    englishSentence: "The train is moving fast.",
  },
  {
    question: "Brille",
    correctAnswer: "die",
    image: require("./images/brille.png"),
    englishName: "Glasses",
    germanSentence: "Die Brille sitzt gut.",
    englishSentence: "The glasses fit well.",
  },
  {
    question: "Schnee",
    correctAnswer: "der",
    image: require("./images/schnee.png"),
    englishName: "Snow",
    germanSentence: "Der Schnee ist kalt.",
    englishSentence: "The snow is cold.",
  },
  {
    question: "Treppe",
    correctAnswer: "die",
    image: require("./images/treppe.png"),
    englishName: "Stairs",
    germanSentence: "Die Treppe führt nach oben.",
    englishSentence: "The stairs lead upwards.",
  },
  {
    question: "Küche",
    correctAnswer: "die",
    image: require("./images/kueche.png"),
    englishName: "Kitchen",
    germanSentence: "Die Küche ist sauber.",
    englishSentence: "The kitchen is clean.",
  },
  {
    question: "Schlüssel",
    correctAnswer: "der",
    image: require("./images/schluessel.png"),
    englishName: "Key",
    germanSentence: "Der Schlüssel öffnet die Tür.",
    englishSentence: "The key opens the door.",
  },
  {
    question: "Fluss",
    correctAnswer: "der",
    image: require("./images/fluss.png"),
    englishName: "River",
    germanSentence: "Der Fluss fließt schnell.",
    englishSentence: "The river flows fast.",
  },
  {
    question: "Löffel",
    correctAnswer: "der",
    image: require("./images/loeffel.png"),
    englishName: "Spoon",
    germanSentence: "Der Löffel ist aus Silber.",
    englishSentence: "The spoon is made of silver.",
  },
  {
    question: "Feder",
    correctAnswer: "die",
    image: require("./images/feder.png"),
    englishName: "Feather",
    germanSentence: "Die Feder schreibt gut.",
    englishSentence: "The feather writes well.",
  },
  {
    question: "Kissen",
    correctAnswer: "das",
    image: require("./images/kissen.png"),
    englishName: "Pillow",
    germanSentence: "Das Kissen ist weich.",
    englishSentence: "The pillow is soft.",
  },
  {
    question: "Tasse",
    correctAnswer: "die",
    image: require("./images/tasse.png"),
    englishName: "Cup",
    germanSentence: "Die Tasse ist leer.",
    englishSentence: "The cup is empty.",
  },
  {
    question: "Hut",
    correctAnswer: "der",
    image: require("./images/hut.png"),
    englishName: "Hat",
    germanSentence: "Der Hut ist schick.",
    englishSentence: "The hat is stylish.",
  },

  {
    question: "Papier",
    correctAnswer: "das",
    image: require("./images/papier.png"),
    englishName: "Paper",
    germanSentence: "Das Papier ist weiß.",
    englishSentence: "The paper is white.",
  },
];
